### ISSUE TITLE
Could not set unknown property 'classifier' for task ':expo-linear-gradient:androidSourcesJar'

### ISSUE THREAD

**Issue by endrits079** [gluestack/gluestack-ui#1001]
### Description

Cannot run the app in android because it gives this error:  Could not set unknown property 'classifier' for task ':expo-linear-gradient:androidSourcesJar'

### Steps to reproduce

1. Create a new app using npm create gluestack@latest
2. Select React native app
3. After project is created do npm start
4. Press A to run on android or npm run android

### gluestack-ui Version

0.1.15

### Platform

- [X] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Node version 20.0.5
Java:
java 11.0.13 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

**Comment by makkarMeenu** [comment]
@endrits079 We have removed LinearGradient as a component from `@gluestack-ui/themed` . Please update 
`@gluestack-ui/themed`  to `0.1.36`  latest. It will resolve this issue.
