### ISSUE TITLE
Slider can't slide in iOS simulator

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1006]
### Description

Slider can't slide in iOS simulator, I can change slider by click, but not slide

### Steps to reproduce

The example code is:
```
<Slider sliderTrackHeight={8}>
            <SliderTrack>
              <SliderFilledTrack />
            </SliderTrack>
            <SliderThumb />
          </Slider>
```

### gluestack-ui Version

0.1.12

### Platform

- [ ] Android
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by makkarMeenu** [comment]
@BooYeu We are fixing this. Will notify you once resolved.

**Comment by makkarMeenu** [comment]
@BooYeu Please upgrade version of `@gluestack-ui/themed`  to `0.1.36` , it will resolve this issue.
