### ISSUE TITLE
placement="top" not working for Menu component on iOS/Android..

### ISSUE THREAD

**Issue by GollyJer** [gluestack/gluestack-ui#1011]
### Description

Menu should show.

### CodeSandbox/Snack link

https://snack.expo.dev/@gollyjer/gluestack-menu-placement-bug

### Steps to reproduce

Go to snack.
Change `const PLACEMENT="top"`
Open Android or iOS simulator.
Menu won't display on button press.
Change `const PLACEMENT="bottom"`
Menu will show.

### gluestack-ui Version

0.1.21

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by makkarMeenu** [comment]
@GollyJer Thanks for reporting, we will look into this.

**Comment by makkarMeenu** [comment]
@GollyJer Please upgrade the `@gluestack-ui/themed` to 0.1.33. It will resolve the issue.
