### ISSUE TITLE
Wrapping Button and reexporting prevents ButtonGroup from working

### ISSUE THREAD

**Issue by capturetheworld** [gluestack/gluestack-ui#1037]
### Description

When Gluestack Button "GButton" is wrapped and reexported, ButtonGroup no longer work

### CodeSandbox/Snack link

https://codesandbox.io/s/example-44622s

### Steps to reproduce

1. Import Button as GButton from library
2. Export const Button with children props
3. <GButton> {children} </GButton>
4. If you wrap with a <ButtonGroup> in another component it no longer works

### gluestack-ui Version

0.1.32

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

<img width="444" alt="Screenshot 2023-09-08 at 2 07 10 PM" src="https://github.com/gluestack/gluestack-ui/assets/11341637/4657c169-0d22-45b5-8747-4fe32df0a978">

**Comment by makkarMeenu** [comment]
@capturetheworld The codesandbox is not updated, could you please update that and let us know .

**Comment by capturetheworld** [comment]
> @capturetheworld The codesandbox is not updated, could you please update that and let us know .
Hi, this is a code snippet from my project, I cannot share the entire project as the code is proprietary. This gives you enough of an idea of how I am exporting the Button component. See Lines 27-30

**Comment by makkarMeenu** [comment]
> > @capturetheworld The codesandbox is not updated, could you please update that and let us know .
> 
> Hi, this is a code snippet from my project, I cannot share the entire project as the code is proprietary. This gives you enough of an idea of how I am exporting the Button component. See Lines 27-30 @makkarMeenu

Please try this snippet for wrapping the Button. Let me know if it works.
```
export const Button = ({ children , ...props}:any) => {
  return <GButton {...props}>{children}</GButton>;
};
```
