### ISSUE TITLE
Menu (Alpha) works on iOS && Web but fails on Android Studio

### ISSUE THREAD

**Issue by davidgould6** [gluestack/gluestack-ui#1053]
### Description

Using Themed Menu does not work for android studio

### Steps to reproduce

1. Introduce Menu component 
2. Compile / bundle on android emulator via android studio
3. See error

` ERROR  Invariant Violation: requireNativeComponent: "RNSVGSvgView" was not found in the UIManager.`

### gluestack-ui Version

^0.1.36

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @davidgould6, Can you please share following commands logs.
`npm why react-native-svg` or `yarn why react-native-svg`

**Comment by surajahmed** [comment]
@davidgould6 Thanks for the info. We'll try to reproduce it. 
Can you please try the latest versions of `@gluestack-ui/themed` and `@gluestack-style/react`?

**Comment by surajahmed** [comment]
@davidgould6 Apologies for the delayed response. Could you please remove the node_modules directory and update to the latest version?

**Comment by Viraj-10** [comment]
Closing this issue. Please feel free to reopen it.
