### ISSUE TITLE
[Input] react native Performance issues during fast input

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1065]
### Description

 react native Performance issues during fast input

### Steps to reproduce

```
function App(){

  const [id, setId] = useState('');

  return (
    <FormControl>
      <Input>
        <InputField type="text" value={id} onChangeText={setId} />
      </Input>
    </FormControl>
  );
}
```

https://github.com/gluestack/gluestack-ui/assets/16587763/09c4da1b-0734-4ce1-ad31-7f4f6f05ca78

### gluestack-ui Version

0.1.38

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by BooYeu** [comment]
@Viraj-10 The input component is in Actionsheet
```
<Actionsheet isOpen>
        <ActionsheetBackdrop />
        <ActionsheetContent>
          <ActionsheetDragIndicatorWrapper>
            <ActionsheetDragIndicator />
          </ActionsheetDragIndicatorWrapper>
          <ActionsheetScrollView>
            <FormControl p="$4" w="$full">
              <Input>
                <InputIcon pl="$3">
                  <Icon as={AtSignIcon} />
                </InputIcon>
                <InputField type="text" value={id} onChangeText={setId} />
              </Input>
            </FormControl>
          </ActionsheetScrollView>
        </ActionsheetContent>
      </Actionsheet>
```

**Comment by makkarMeenu** [comment]
> @Viraj-10 The input component is in Actionsheet
> 
> ```
> <Actionsheet isOpen>
>         <ActionsheetBackdrop />
>         <ActionsheetContent>
>           <ActionsheetDragIndicatorWrapper>
>             <ActionsheetDragIndicator />
>           </ActionsheetDragIndicatorWrapper>
>           <ActionsheetScrollView>
>             <FormControl p="$4" w="$full">
>               <Input>
>                 <InputIcon pl="$3">
>                   <Icon as={AtSignIcon} />
>                 </InputIcon>
>                 <InputField type="text" value={id} onChangeText={setId} />
>               </Input>
>             </FormControl>
>           </ActionsheetScrollView>
>         </ActionsheetContent>
>       </Actionsheet>
> ```

This is working fine for me. Created a snack [here](https://snack.expo.dev/cj4pVk3tP).
It would be nice if you could share a snack link along with the issue.

**Comment by BooYeu** [comment]
I add another input without Actionsheet and run the code in my ios simulator.

https://github.com/gluestack/gluestack-ui/assets/16587763/5efb7e60-e316-4fab-8b81-8a6309a57690

@makkarMeenu

**Comment by BooYeu** [comment]
```
import {SafeAreaView, TextInput} from 'react-native';
import React, {useState} from 'react';
import {
  Box,
  GluestackUIProvider,
  Input,
  InputField,
  Actionsheet,
  ActionsheetBackdrop,
  ActionsheetContent,
  ActionsheetDragIndicatorWrapper,
  ActionsheetDragIndicator,
  ActionsheetScrollView,
  FormControl,
  InputIcon,
  Icon,
} from '@gluestack-ui/themed';

const Example = () => {
  const [text, setText] = useState('');
  const [text2, setText2] = useState('');
  return (
    <Box flex={1} h={500}>
      <Input pt="$5">
        <InputField type="text" value={text2} onChangeText={setText2} />
      </Input>
      <Actionsheet isOpen>
        <ActionsheetBackdrop />
        <ActionsheetContent h={500}>
          <ActionsheetDragIndicatorWrapper>
            <ActionsheetDragIndicator />
          </ActionsheetDragIndicatorWrapper>
          <ActionsheetScrollView>
            <FormControl p="$4" w="$full">
              <Input>
                <InputField type="text" value={text} onChangeText={setText} />
              </Input>
            </FormControl>
          </ActionsheetScrollView>
        </ActionsheetContent>
      </Actionsheet>
    </Box>
  );
};

export default function App() {
  return (
    <SafeAreaView>
      <GluestackUIProvider>
        <Example />
      </GluestackUIProvider>
    </SafeAreaView>
  );
}

```

**Comment by Viraj-10** [comment]
Hey @BooYeu, I am unable to reproduce this issue. Attaching Video for the same.
https://github.com/gluestack/gluestack-ui/assets/66306233/6be71dc7-06f4-428d-88e6-ee84edecff7e

Possible solution that might work. 

- Extract component outside `actionsheet`. This will only rerender `ActionsheetForm` when state is changed.
```
const Example = () => {
  const [text1, setText1] = useState("");
  const [text, setText] = useState("");

  return (
    <Box flex={1} h={500}>
      <FormControl p="$4" w="$full">
        <Input>
          <InputField type="text" value={text1} onChangeText={setText1} />
        </Input>
      </FormControl>
      <Actionsheet isOpen>
        <ActionsheetBackdrop />
        <ActionsheetContent h={500}>
          <ActionsheetDragIndicatorWrapper>
            <ActionsheetDragIndicator />
          </ActionsheetDragIndicatorWrapper>
          <ActionsheetScrollView>
            <ActionsheetForm />
          </ActionsheetScrollView>
        </ActionsheetContent>
      </Actionsheet>
    </Box>
  );
};

const ActionsheetForm = () => {
  const [text, setText] = useState("");

  return (
    <FormControl p="$4" w="$full">
      <Input>
        <InputField type="text" value={text} onChangeText={setText} />
      </Input>
    </FormControl>
  );
};
```
- I see that you are only typing numbers. So if you have any specific condition on on `onChangeText` which only allows number. That might be the reason. In that case I suggest you to use [`react-hooks-forms`](https://www.react-hook-form.com/).
