### ISSUE TITLE
Tabs documentation out of date?

### ISSUE THREAD

**Issue by njt1982** [gluestack/gluestack-ui#1071]
### Description

https://ui.gluestack.io/docs/components/disclosure/tabs

This doesn't seem to represent the JS code I can see in the "tabs" section of the project.

Looks like we have

    Tab,
    TabPanels
    TabList
    TabPanel
    TabTitle
    TabIcon

I don't see things like Trigger

### Problem Statement

Why? Well, I think the docs should be accurate 😉

### Proposed Solution or API

Proposition: Update the docs

**Comment by njt1982** [comment]
Looks like it works like this, now?

```
<Tabs value="tab1">
  <Tabs.TabList>
    <Tabs.Tab value="tab1">
      <Tabs.TabTitle>Tab 1</Tabs.TabTitle>
    </Tabs.Tab>
    <Tabs.Tab value="tab2">
      <Tabs.TabTitle>Tab 2</Tabs.TabTitle>
    </Tabs.Tab>
  </Tabs.TabList>

  <Tabs.TabPanels>
    <Tabs.TabPanel value="tab1">
      <Text>Some Content for Tab 1</Text>
    </Tabs.TabPanel>
    <Tabs.TabPanel value="tab2">
      <Text>Some content for Tab 2</Text>
    </Tabs.TabPanel>
  </Tabs.TabPanels>
</Tabs>
```

**Comment by Viraj-10** [comment]
Hey @njt1982, `Tabs` is in `api-draft` phase. exported tab was part of previous iteration but was drop due to issues. We will work on this in next phase of new components where api will be similar to described in docs. 
Feel free to comment on this issue for further explanation.

**Comment by njt1982** [comment]
ok - so sounds like the implementation that I have that works "today" may break in the future to be more inline with the documentation? Is that correct?

**Comment by victorcorreae** [comment]
Hey @njt1982 even if it might break in the future I'd like to know how did you personalize your tabs, I'm trying to understand how to get the active state to be able to change style, manage borderRadius and other things to make it prettier.
Currently I got this:
```
import React from 'react';
import { StyleSheet } from 'react-native';
import { Text, Tabs } from '@gluestack-ui/themed';
import Colors from '../../constants/Colors';

const SyncScreen = () => {
    return (
        <Tabs value="tab1" style={{backgroundColor: Colors.white}}>
            <Tabs.TabList style={styles.tabContainer}>
                <Tabs.Tab style={styles.tabStyle} value="tab1">
                    <Tabs.TabTitle style={{alignSelf: 'center'}}>Tab 1</Tabs.TabTitle>
                </Tabs.Tab>
                <Tabs.Tab style={styles.tabStyle} value="tab2">
                    <Tabs.TabTitle style={{alignSelf: 'center'}}>Tab 2</Tabs.TabTitle>
                </Tabs.Tab>
            </Tabs.TabList>
            <Tabs.TabPanels>
                <Tabs.TabPanel value="tab1">
                    <Text>Some content for Tab 2</Text>
                </Tabs.TabPanel>
                <Tabs.TabPanel value="tab2">
                    <Text>Some content for Tab 2</Text>
                </Tabs.TabPanel>
            </Tabs.TabPanels>
        </Tabs>
    );
};

const styles = StyleSheet.create({
    tabContainer: {
        width: '90%',
        backgroundColor: Colors.white,
        alignSelf: 'center'
    },
    tabStyle: {
        borderWidth: 1,
        flex: 0.5,
        backgroundColor: Colors.secondary,
        borderColor: Colors.tertiary
    }
});

export default SyncScreen;
```
