### ISSUE TITLE
[ScrollView] Typescript error

### ISSUE THREAD

**Issue by PiTiLeZarD** [gluestack/gluestack-ui#1083]
### Description

Typescript thinks children should be string[]

### Steps to reproduce

``` typescript
import { ScrollView, Text } from "@gluestack-ui/themed";
import React from "react";

export type BandSelectProps = {
    text: string;
};

export type BandSelectComponent = React.FC<BandSelectProps>;

export const BandSelect: BandSelectComponent = ({ text }): JSX.Element => {
    return (
        <ScrollView h="$80" w="$80">
            <Text>{text}</Text>
            <Text>{text}</Text>
            <Text>{text}</Text>
            <Text>{text}</Text>
            <Text>{text}</Text>
            <Text>{text}</Text>
            <Text>{text}</Text>
            <Text>{text}</Text>
        </ScrollView>
    );
};
```

This shows me:
```
Type '{ children: Element[]; h: "$80"; w: "$80"; }' is not assignable to type 'Partial<ComponentProps<StyleProp<ViewStyle>, unknown, ScrollViewProps, "ScrollView">>'.
  Property 'children' is incompatible with index signature.
    Type 'Element[]' is not assignable to type 'string & {}'.
      Type 'Element[]' is not assignable to type 'string'.ts(2322)
```

### gluestack-ui Version

0.1.38

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Other Platform

I'm using bit.dev but I don't think the issue is platform specific

### Additional Information

Tried to dig into your types but couldn't pinpoint where children is overriden. The react native scroll view has the right types tho.

I've tried your example as well, not just mine, the only way I can make the view work is by giving it strings:
```typescript
<ScrollView h="$80" w="$80">
            test
            test
            test
</ScrollView>
```

**Comment by PiTiLeZarD** [comment]
Actually have the same issue with most components :/ I thought it was my tsconfig, so I took the one that npx create uses and same thing happens.

**Comment by Georgerowberry** [comment]
Having the same issue here with Avatar component

**Comment by Georgerowberry** [comment]
@PiTiLeZarD I managed to get this working with this tsconfig:

`{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@gluestack-ui/themed": ["../../packages/themed/src"]
    },
    "emitDeclarationOnly": true,
    "noEmit": false,
    "declaration": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["esnext", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "esnext"
  }
}
`

**Comment by jpike88** [comment]
Same problem. @makkarMeenu a 3 weeks old issue... I want to migrate from native base but this is makes it pretty much impossible.

**Comment by makkarMeenu** [comment]
Hi @jpike88  @PiTiLeZarD , I just created an `expo` project with the template that we provided for `expo`. I pasted this code snippet and it worked like magic. 
```
import { GluestackUIProvider, Text, ScrollView } from "@gluestack-ui/themed";
export default function App() {
  return (
    <GluestackUIProvider>
      <ScrollView h="$80" w="$80">
        <Text>dhhdh</Text>
        <Text>dhhdh</Text>
        <Text>dhhdh</Text>
        <Text>dhhdh</Text>
        <Text>dhhdh</Text>
        <Text>dhhdh</Text>
        <Text>dhhdh</Text>
        <Text>dhhdh</Text>
      </ScrollView>
    </GluestackUIProvider>
  );
}
```


<img width="1079" alt="Screenshot 2023-10-03 at 12 19 20 PM" src="https://github.com/gluestack/gluestack-ui/assets/54400869/5bdeffb2-bba6-4537-a750-a2d631dfa23e">

<img width="1440" alt="Screenshot 2023-10-03 at 12 18 08 PM" src="https://github.com/gluestack/gluestack-ui/assets/54400869/5dd44811-0472-42ab-bd21-1623c5714de7">


I am not able to understand the issue you are facing. Kindly help me with more information, so that I can help you in better way.
I am on the version `"@gluestack-ui/themed" : 0.1.53` and `"@gluestack-style/react" : 0.2.51` . 


Here is my `ts-config` file in case needed.

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true
  }
}
```

Please update to the latest versions and let me know.

**Comment by jpike88** [comment]
it seems to be perhaps clashing with:
 @types/react@18.2.24.
@gluestack-ui/themed": ^0.1.53
gluestack-style/react@0.2.51

<img width="960" alt="Screenshot 2023-10-03 at 14 10 41" src="https://github.com/gluestack/gluestack-ui/assets/9585787/0149b9e5-b234-4df9-b747-03215623b5fe">
<img width="854" alt="Screenshot 2023-10-03 at 14 12 02" src="https://github.com/gluestack/gluestack-ui/assets/9585787/5e025250-1db8-4f2b-ba1d-5ebc6df567db">

**Comment by makkarMeenu** [comment]
I updated the react types version manually in my project to `18.2.24`.  It is working fine. Can you please provide me the your repository access.

**Comment by PiTiLeZarD** [comment]
Hey,

[So here is a project](https://drive.google.com/file/d/1Mtge0XLBI2JVQvqMNgI7qyOPOA-iTYmp/view?usp=sharing) that showcases the issue.

It's a bit.dev project so, gotta install bit and then `bit install` to see the project come to life.

Tell me if that helps.

**Comment by czaku** [comment]
Same is happening to me...

**Comment by ankit-tailor** [comment]
> Hey,
> 
> [So here is a project](https://drive.google.com/file/d/1Mtge0XLBI2JVQvqMNgI7qyOPOA-iTYmp/view?usp=sharing) that showcases the issue.
> 
> It's a bit.dev project so, gotta install bit and then `bit install` to see the project come to life.
> 
> Tell me if that helps.
> 
> PS: yes I am considering not using bit.dev, but for the sake of this issue that seems to be shared with other contexts, I share mine ;)

Hey @PiTiLeZarD, I updated the `@gluestack-ui/themed` and `@gluestack-style/react` to the latest version, and also I have added `@gluestack-ui/config` for `config` since we are exporting `config` from there now. It is working for me. Can you please try the same? Let me know if it works for you.
