### ISSUE TITLE
InputField seems to be inheriting the padding from parent Input in Android

### ISSUE THREAD

**Issue by jihyundotkim** [gluestack/gluestack-ui#1084]
### Description

InputField gets padding if from parent Input has it, in Android only

### Steps to reproduce

```
<FormControl>
    <FormControlLabel>
        <FormControlLabelText>Phone Number</FormControlLabelText>
    </FormControlLabel>
    <Input p='$2'>
        <InputIcon>
            <Icon as={PhoneIcon} />
        </InputIcon>
        <InputField placeholder="3051119999" />
    </Input>
</FormControl>
```
the InputField becomes so small that neither the placeholder nor the text input is visible. This only occurs on Android, Doesn't seem to be doing this in iOS

### gluestack-ui Version

themed@0.1.38

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

setting the InputField padding to 0 does solve the problem (`<InputField placeholder="30542340999" p='$0' />`)

so this isn't a high-priority issue, but I still wanted to let you know :)

**Comment by Viraj-10** [comment]
Hey @jihyundotkim, use _input inside sx to give padding to input. Don't give padding to Input directly.

**Comment by Viraj-10** [comment]
For more understanding of styling input please visit [Input Docs ](https://ui.gluestack.io/docs/components/forms/input). At the end you will find a specsheet for styling guide.

**Comment by jihyundotkim** [comment]
@Viraj-10 ah I see! I'll close the issue now thanks so much!
