### ISSUE TITLE
[Actionsheet] Jest SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by fly1chop** [gluestack/gluestack-ui#1095]
### Description

I am trying to run a very simple test to check gluestack-ui and it fails to run due to unexpected 'export' from `@legendapp/motion/index.js`.

#### This is the error
![image](https://github.com/gluestack/gluestack-ui/assets/25377159/ad297901-9444-483f-92b3-4726c9cff4a5)

#### App.js
```
import { Text } from '@gluestack-ui/themed';

export default function App() {
   return <Text>Hello World</Text>
}
```

#### App.test.js
```
import React from 'react';
import renderer from 'react-test-renderer';

import App from '../App';

describe('<App />', () => {
  it('has 1 child', () => {
    const tree = renderer.create(<App />).toJSON();
    expect(tree.children.length).toBe(1);
  });
});
```

#### jest.config.js
```
module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@gluestack-ui|@gluestack-ui/.*|@legendapp/motion)',
  ],
};
```

### gluestack-ui Version

0.1.41

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @fly1chop, use typescript and babel with jest.

**Comment by fly1chop** [comment]
> Hey @fly1chop, use typescript and babel with jest. You can refer this [PR](https://github.com/gluestack/expo-head-starter-kit/pull/1) for jest testing setup till we write office doc.

Hi @Viraj-10 thank you for the quick reply!
Can I use gluestack-ui without typescript? Was it never intended to be used with just js?

**Comment by fly1chop** [comment]
I just created a fresh expo project using typescript and set my babel as per your example but get the following error
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From __test__/App.test.tsx.
```

Here is my test file
```
jest.useFakeTimers();

import React from 'react';
import renderer from 'react-test-renderer';
import { StyledProvider, config } from '@gluestack-ui/themed';
import App from '../App';

it('Renders with Gluestack', () => {
  const tree = renderer
    .create(
      <StyledProvider config={config.theme}>
        <App />
      </StyledProvider>,
    )
    .toJSON();
  expect(tree).toMatchSnapshot();
});
```

**Comment by Viraj-10** [comment]
Hey @fly1chop, Can you provide repo link?

**Comment by luiz504** [comment]
> ## 1. I just created a fresh expo project using typescript and set my babel as per your example but get the following error:
> ![image](https://user-images.githubusercontent.com/25377159/268545214-244190cf-c39d-4221-b84a-fd6a486e50a0.png)
try `jest.runAllTimers()` I guess that could be some async stuff like timeout | Throttle | debounce that runs after the test finishes.

**Comment by luiz504** [comment]
> ### Steps to reproduce
> #### This is the error
> ![image](https://user-images.githubusercontent.com/25377159/268185519-ad297901-9444-483f-92b3-4726c9cff4a5.png)

I solved this problem by adding `|@gluestack-ui/themed|@legendapp` to the trabsformIgnorePattern string in the jest.config.ts.

**Comment by Viraj-10** [comment]
Closing this issue since above solution are seems to be working please feel free to comment. I will reopen this issue.

**Comment by Amystherdam** [comment]
I have an error similar to this @Viraj-10 

<img width="1067" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/43969809/081f5dc5-e021-4437-99cc-b5fda1c56654">

Adding `|@gluestack-ui/themed|@legendapp` as @luiz504 recommended, didn't work

**Comment by ozanhonamlioglu** [comment]
This issue still persist, even with your example projects.
