### ISSUE TITLE
[Select] ActionSheet for Select Component doesn't work as expected.

### ISSUE THREAD

**Issue by ThukuWakogi** [gluestack/gluestack-ui#1128]
### Description

The actionsheet has a fixed height and doesn't scroll when actionsheet items overflow

### CodeSandbox/Snack link

https://snack.expo.dev/@thukuwakogi/suspicious-violet-strawberries

### Steps to reproduce

Import select component and use it as normal

### gluestack-ui Version

0.1.46

### Platform

- [x] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

https://github.com/gluestack/gluestack-ui/assets/16945309/bb213bad-0b44-4142-bb56-649e80229aa6

https://github.com/gluestack/gluestack-ui/assets/16945309/c064e96f-6b78-4b21-ab84-992c8c2f84af

**Comment by surajahmed** [comment]
Thanks for reporting this @ThukuWakogi . 
We'll look into this.

**Comment by tmarkops** [comment]
Any update on this? Facing the same issue.

**Comment by tmarkops** [comment]
> Any update on this? Facing the same issue.

I just found a workaround: you can wrap the Scroll.Items in a ScrollView and then the scrolling functionality will be fine. But this should probably be the case by default.

**Comment by Viraj-10** [comment]
Hey @tmarkops, We have `<SelectScrollView />` for this. you can wrap your `SelectItems`. Please upgrade to latest version of `@gluestack-ui/themed` and `@gluestack-style/react`.
