### ISSUE TITLE
space prop in ButtonGroup incorrectly typed.

### ISSUE THREAD

**Issue by GollyJer** [gluestack/gluestack-ui#1129]
Just wanted to let you know. The prop works, but throws a type error.

<img width="730" alt="SCR-20230919-nhun" src="https://github.com/gluestack/gluestack-ui/assets/689204/d834fc4f-5092-4e64-99fa-553dca19105b">

**Comment by makkarMeenu** [comment]
Thanks for reporting, we will fix this asap.

**Comment by makkarMeenu** [comment]
Please update the `@gluestack-ui/themed` version to the latest. This is fixed.
