### ISSUE TITLE
Radio: Tap any option on the Android Emulator, and it crashes.

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#1135]
Radio. Tap any option on the Android Emulator, and it crashes.

(https://snack.expo.dev/lgajv9n7c)

On a bare RN App, shows this:

<img width="346" alt="Captura de pantalla 2023-09-17 a la(s) 20 04 56" src="https://github.com/gluestack/gluestack-ui/assets/517228/dee9534e-a6fe-4802-b646-dbe2bdc13fea">

_Originally posted by @jacargentina in https://github.com/gluestack/gluestack-ui/issues/1068#issuecomment-1722590855_

**Comment by makkarMeenu** [comment]
Thanks for reporting, we will look into this.

**Comment by makkarMeenu** [comment]
@jacargentina This has been fixed, please update to the latest version of `@gluestack-ui/themed`.

**Comment by jacargentina** [comment]
@makkarMeenu now it is not crashing!!

**Comment by gavishap** [comment]
i am having the same issue. the radios are not being filled when selected. Any solutions?

**Comment by LucassMota** [comment]
Hello! The same is happening to me using ButtonIcon: 

> For input string: "sm"

`"@gluestack-style/react": "^1.0.17",
    "@gluestack-ui/config": "^1.0.3",
    "@gluestack-ui/themed": "^1.0.17",`

**Comment by LucassMota** [comment]
> Hello! The same is happening to me using ButtonIcon:
> 
> > For input string: "sm"
> 
> `"@gluestack-style/react": "^1.0.17", "@gluestack-ui/config": "^1.0.3", "@gluestack-ui/themed": "^1.0.17",`

Actualy, if I use size="sm" on a Button with a ButtonIcon using a lucide icon, the same will happen
