### ISSUE TITLE
Failed to parse source map from '/Users/yy/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts' file: Error: ENOENT: no such file or directory, open '/Users/yeyuliang/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts'

### ISSUE THREAD

**Issue by yeyuliang2015** [gluestack/gluestack-ui#1141]
### Description

Failed to parse source map from '/Users/yy/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts' file: Error: ENOENT: no such file or directory, open '/Users/yeyuliang/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts'

### CodeSandbox/Snack link

Failed to parse source map from '/Users/yy/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts' file: Error: ENOENT: no such file or directory, open '/Users/yeyuliang/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts'

### Steps to reproduce

Failed to parse source map from '/Users/yy/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts' file: Error: ENOENT: no such file or directory, open '/Users/yeyuliang/react-native/di-adp-app/node_modules/@legendapp/src/timeoutOnce.ts'

### gluestack-ui Version

0.1.48

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by yeyuliang2015** [comment]
控制台报错

**Comment by yeyuliang2015** [comment]
<img width="1362" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/10381702/bdce4705-ed37-4796-a3a0-4d2ac20b27eb">

**Comment by yeyuliang2015** [comment]
<img width="416" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/10381702/5c18f6b3-90ed-4bf9-909f-9dfb85e92835">

**Comment by surajahmed** [comment]
@yeyuliang2015 Thanks for reporting. We'll look into this.

**Comment by Viraj-10** [comment]
Hey @yeyuliang2015, This issue is resolved in latest version of `@gluestack-ui/themed`. Please install `latest` version of `@gluestack-ui/themed` and `@gluestack-style/react`.

**Comment by yeyuliang2015** [comment]
Why did the styles become messed up after upgrading to the latest version?
