### ISSUE TITLE
What happend with the types in the latest update?

### ISSUE THREAD

**Issue by lhguerra** [gluestack/gluestack-ui#1147]
### Description

Attributions that where working perfectly started to give all kinds of nonsensical error types

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

0.1.49

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

These types where working fine until my latest update. I'm now using 0.1.49

![image](https://github.com/gluestack/gluestack-ui/assets/4529663/09b44797-90fa-4839-be98-4436cec6c5ae)

**Comment by surajahmed** [comment]
@lhguerra Thanks for reporting. Can you please try updating the version of `@glustack-ui/themed` and `@gluestack-style/react` to the latest?

**Comment by lhguerra** [comment]
@surajahmed it looks like these errors were a side effect that my IDE was handling very poorly, after some investigation I removed another type error (this one was really wrong) and all other errors  vanished. So I'm closing the issue since it's not a bug with gluestack.
