### ISSUE TITLE
Tooltip not closing on overlay click?

### ISSUE THREAD

**Issue by GollyJer** [gluestack/gluestack-ui#1157]
### Description

I'm not sure this is a problem with my expectation, or a bug.
My expectation is that, when using Tooltip on mobile that tapping outside the tooltip will close it. But this doesn't happen.

### CodeSandbox/Snack link

https://snack.expo.dev/@gollyjer/gluestack-hide-tooltip-on-mobile

### Steps to reproduce

Go to the snack. Tap to open the tooltip. Tap outside the tooltip and it remains open.
It behaves the same on web/android/ios.

### gluestack-ui Version

0.1.50

**Comment by surajahmed** [comment]
@GollyJer Thanks for reporting this. We're working on it.

**Comment by makkarMeenu** [comment]
Hi @GollyJer , Thanks for reporting.
Documentation and types were not up-to-date for tooltip. We will update that. We don't have the functionality on closeOnOverlayClick in tooltip.
 If you think, we should have such functionality. Please feel free to open discussion.
