### ISSUE TITLE
[Actionsheet] the actionsheet shadow is not opacity 

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1159]
### Description

[Actionsheet] the actionsheet shadow is not opacity

### Steps to reproduce

https://github.com/gluestack/gluestack-ui/assets/16587763/44ecfc5e-800c-417d-b362-50d6e1946d0b

### gluestack-ui Version

0.1.51

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by BooYeu** [comment]
The issue I submitted before : https://github.com/gluestack/gluestack-ui/issues/1086
But the problem still exists in ios &  android

**Comment by surajahmed** [comment]
@BooYeu Can you please try updating `@gluestack-style/react` to latest?
If that doesn't resolve the issue, please try removing and adding `@gluestack-ui/themed`. 
Please inform us if the problem persists. Thank you for bringing this to our attention.

**Comment by BooYeu** [comment]
It is fine. Thank you !
