### ISSUE TITLE
@gluestack-style/animation-plugin@0.1.12  cause Error: Check the render method of Styled(Component) 

### ISSUE THREAD

**Issue by jasonz1360** [gluestack/gluestack-ui#1162]
### Description

@gluestack-style/animation-plugin@0.1.12  cause Error: Element type is invalid: expected a string ... Check the render method of Styled(Component) 

### Steps to reproduce

yarn install @gluestack-style/animation-plugin@latest
yarn start --web

Failed to start web app in chrome.
Error: Element type is invalid: expected a string ... Check the render method of Styled(Component) when using Image component

Roll back to 0.1.7, everything return to ok immediately.

### gluestack-ui Version

animation-plugin@0.1.12

### Platform

- [X] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Failed to start web app in chrome.
version snapshot
<img width="355" alt="2023-09-25 19 44 58" src="https://github.com/gluestack/gluestack-ui/assets/96457197/049fe422-9f8e-4c7a-9c75-d3ba3ae1b9c1">

**Comment by makkarMeenu** [comment]
Thanks for reporting. We will fix this on priority.

**Comment by Viraj-10** [comment]
Hey @jasonz1360, Please can you please try with our new version of `@gluestack-ui/themed` and `@gluestack-style/react`.
Also we have deprecated `@gluestack-style/animation-plugin`. for more info please refer this following docs link:
- https://gluestack.io/style/docs/plugins/animation-plugin.
- https://gluestack.io/ui/docs/advanced/animations.
