### ISSUE TITLE
New error today  -  The `value` prop is required for the `<Context.Provider>`. 

### ISSUE THREAD

**Issue by OneHatRepo** [gluestack/gluestack-ui#1163]
### Description

Gluestack errors on simple launch of demo app

### Steps to reproduce

Just install a stock app from the template, and try to run the web app

```
npm create gluestack
cd my-app
npm run start
w
```

Gives the following console error:

```
react-dom.development.js:86 Warning: The `value` prop is required for the `<Context.Provider>`. Did you misspell it or forget to pass it?
    at GluestackUIContextProvider (http://localhost:19006/static/js/bundle.js:39832:5)
    at http://localhost:19006/static/js/bundle.js:39862:7
    at GluestackUIProvider (http://localhost:19006/static/js/bundle.js:51394:32)
    at App
    at withDevTools(App)
```

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by makkarMeenu** [comment]
Thanks for reporting the issue.
 We have fixed the warning. Kindly update the `@gluestack-ui/themed` to the latest version or  start a new gluestack project.
