### ISSUE TITLE
Add a way to use Tooltips on mobile.

### ISSUE THREAD

**Issue by GollyJer** [gluestack/gluestack-ui#1172]
### Description

I used to use the native-base Popover to show information near where a user taps. But the gluestack Popover is significantly different. It is almost no different than a modal from a UX perspective.

So, I tried using Tooltip to show some content near the tapped item and found it doesn't work on mobile.

Here is the report where I thought this was a bug 👉 https://github.com/gluestack/gluestack-ui/issues/1157#issuecomment-1735253303. 

There is no way good way to use Tooltip on a mobile device. Seems there needs to be if this is to be considered a cross platform component.

### Problem Statement

Tooltip doesn't do anything on mobile.

### Proposed Solution or API

- Show/hide tooltip onPress using triggerProps.
- add closeOnOverlayClick functionality.

**Comment by makkarMeenu** [comment]
We will have a look into this and implement whatever is the best as soon as we get some bandwidth.

**Comment by Viraj-10** [comment]
Hey @GollyJer, We have resolve this issue in version `V1.0.3` of `@gluestack-ui/themed` Please refer this [snack](https://snack.expo.dev/@viraj_10/tooltip-native-onpress) for working code.

PS:- Code inside snack will only work on native.

**Comment by AlexMachin1997** [comment]
@Viraj-10 I've just given this a go and it doesn't seem to be appearing.

Is there anything specific that needs doing outside of the rather simple example ?

**Comment by Viraj-10** [comment]
Hey @AlexMachin1997, you can checkout below example. 

https://github.com/user-attachments/assets/6121ed34-d463-496c-a749-d3decb1f03c2


```
import { Button, ButtonText } from "@/components/ui/button";
import {
  Checkbox,
  CheckboxIcon,
  CheckboxIndicator,
  CheckboxLabel,
} from "@/components/ui/checkbox";
import {
  CheckIcon,
  ChevronDownIcon,
  InfoIcon,
  SearchIcon,
} from "@/components/ui/icon";
import { Input, InputField, InputIcon, InputSlot } from "@/components/ui/input";
import {
  Select,
  SelectBackdrop,
  SelectContent,
  SelectDragIndicator,
  SelectDragIndicatorWrapper,
  SelectIcon,
  SelectInput,
  SelectItem,
  SelectPortal,
  SelectTrigger,
} from "@/components/ui/select";
import { Tooltip, TooltipContent, TooltipText } from "@/components/ui/tooltip";
import { useState } from "react";
import { View } from "react-native";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <View className="bg-white flex-1 items-center justify-center">
      <Input className="w-48 overflow-hidden px-2">
        <InputField placeholder="Search..." />
        <Tooltip
          isOpen={isOpen}
          placement="bottom left"
          trigger={(triggerProps) => {
            console.log(triggerProps);
            return (
              <InputSlot
                className="pl-3"
                {...triggerProps}
                onPressIn={() => setIsOpen(true)}
                onPressOut={() => setIsOpen(false)}
              >
                <InputIcon as={InfoIcon} />
              </InputSlot>
            );
          }}
        >
          <TooltipContent className="w-[100px]">
            <TooltipText>This is a tooltip for the input field</TooltipText>
          </TooltipContent>
        </Tooltip>
      </Input>
    </View>
  );
}

```
