### ISSUE TITLE
Radio: selected option is not filled

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#1173]
### Description

The selected options icon is not filled

### CodeSandbox/Snack link

https://snack.expo.dev/lgajv9n7c

### Steps to reproduce

The selected options icon is not filled

### gluestack-ui Version

0.1.53

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

### Additional Information

<img width="336" alt="Captura de pantalla 2023-09-26 a la(s) 16 09 00" src="https://github.com/gluestack/gluestack-ui/assets/517228/c108ac55-bbd2-4b4e-b7c8-2d4795b2b3f1">

**Comment by makkarMeenu** [comment]
@jacargentina You are using `lucide-react-native` circle icon which is not filled by default. You can pass `fill` prop in RadioIcon. [Here](https://snack.expo.dev/FzYwN3Xvb) is the snack that I built to help you with this.
