### ISSUE TITLE
Using Theme component ruins flexbox layout

### ISSUE THREAD

**Issue by johnjensenish** [gluestack/gluestack-ui#1183]
### Description

Using the <Theme> component as the parent of a component like <Box flex={1}> makes it so the Box no longer takes up the full screen.

### Steps to reproduce

1. Have a component like `<Box flex={1}>` stretching
2. Wrap it in `<Theme>`
3. Observe the Box is no longer stretching

### gluestack-ui Version

0.1.53

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

```
    "@gluestack-style/react": "^0.2.51",
    "@gluestack-ui/themed": "^0.1.53",
```

**Comment by johnjensenish** [comment]
Is it because [Theme.tsx](https://github.com/gluestack/gluestack-style/blob/main/packages/react/src/Theme.tsx) wraps its children in a`View`?

**Comment by akash3gtm** [comment]
@johnjensenish
Could you also tell why are you using Theme to wrap the components?

**Comment by johnjensenish** [comment]
> @johnjensenish Could you also tell why are you using Theme to wrap the components?

Yeah, my use case is this:

Based on the type of a content a user is creating, i.e. whether it's public or private, we want the entire screen to either be one theme variation or another.

Right now we are leveraging the light/dark `colorMode` prop on `GluestackUIProvider` and styling with `_dark` and `_light` and also manually setting some values. I would rather not use `colorMode` for this. 

Further, the screen can include other content that should render according to its own privacy settings. For this related content, the `colorMode` approach is not appropriate. e.g. The main post could be private and show as as one theme, but a related public post under that would show as another theme.

**Comment by akash3gtm** [comment]
@johnjensenish 
you don't need to wrap them explicitly with the theme component, it will work with the provider and you should be able to use themes directly in that.
define themes in the config and leverage those themes for your styling needs.

Let us know, if there is any issue with the usage of themes.

**Comment by johnjensenish** [comment]
@akash3gtm I'm using the capabilities [described as "Switching between Multiple Themes"](https://ui.gluestack.io/docs/theme/overview). There, it says:

> Now, to actually use this newly created themes, you will need to use the Theme component.

Because I am switching between two different themes, I cannot use just the one theme provided with the provider. I think I need to use the `Theme` component. Am I misunderstanding something?

**Comment by akash3gtm** [comment]
I misunderstood what you were trying to achieve, apologies, and yes, the theme provider does add an extra view if you use it.
As of right now, there is no solution for this issue.
but hey, if you could find a workaround, post it.

P.S. PR's are always welcome :)

**Comment by johnjensenish** [comment]
> I misunderstood what you were trying to achieve, apologies, and yes, the theme provider does add an extra view if you use it. As of right now, there is no solution for this issue. but hey, if you could find a workaround, post it.
> 
> P.S. PR's are always welcome :)

@akash3gtm I'm happy to contribute, but I'm not sure what a solution would be and unsure of the reasoning of the design.

I don't know why the `View` is there. Can you help explain that to me?

I assume it's because we need this data to be available in the component hierarchy: `dataSet={{ 'theme-id': name }}`.

Is there a way of providing `dataSet` to a component that doesn't affect the view hierarchy? Maybe I could I just replace the `View` with a `span` or something like `React.Fragment`?

**Comment by akash3gtm** [comment]
Your assumption is correct, that dataset contains the information for theme to be able to set in all of its children, no matter how nested they are.
We had to use this instead of using javascript only for themes for performance.
Please try the different solutions, if you find any that works with react-native-web i.e. with web, ios and android, we are more than happy to welcome you as a core contributer.

**Comment by rayan1810** [comment]
If I didn't get you wrong your code structure looks something like this right?

```typescript
<LayoutingComponent>
  <Theme name={selectedType}>
      <YourContentCreationComponent>
          .....
          <SelectorForTypePrivateOrPublic onChange={setState}/>
      </YourContentCreationComponent>
  </Theme>
</LayoutingComponent>
``` 

if so, isn't it possible to move the Layouting Component inside the theme as well?

```typescript
<Theme name={selectedType}>
  <LayoutingComponent>
      <YourContentCreationComponent>
          .....
          <SelectorForTypePrivateOrPublic onChange={setState}/>
      </YourContentCreationComponent>
  </LayoutingComponent>
</Theme>
``` 

This will not break the design of your app in most cases, but just for your information, I'm also working on a solution so that color mode is not a separate identity but is all managed by only the same theme system and this improvement might also include subset theme support. I'll keep you updated on that.

**Comment by johnjensenish** [comment]
@rayan1810 Your work sounds promising.

I moved to a different UI library, so can't easily try your suggestion. However I don't think it'd work because how the `Theme` component is implemented. I think the problem is `Theme` renders a `View`, and that `View` does not have the style `flex: 1`.

**Comment by rayan1810** [comment]
Yes, we can easily fix that by making the Theme component accept styled props. We will push it with the next release.

**Comment by rayan1810** [comment]
This will be fixed with this PR https://github.com/gluestack/gluestack-style/pull/500, after this you can provide styles according to your usecase.
