### ISSUE TITLE
Pressable Component `:pressed` doesn't respect state change

### ISSUE THREAD

**Issue by jono-allen** [gluestack/gluestack-ui#1184]
### Description

Setting ':pressed' styling, the component doesn't respond to state. 

Update
If `:active` prop is set, ":pressed` works. So the issue issue here might be a DX issue rather than a bug. 

### CodeSandbox/Snack link

https://snack.expo.dev/@jono-vis-tech/glue-stack-pressable-issue

### Steps to reproduce

1. Hover on "Pressable without active". Color changes. Press down on the component. No state changes 
2. Hover on "Pressable with active". Color changes. Press down on the component. State changes 
3. Hover on button, Color changes, Press down on component state changes 
Expect Pressable state to change when pressed without needing to set ": active" in order for pressed to work.

### gluestack-ui Version

0.1.53

### Platform

- [X] Expo
- [ ] React Native CLI
- [X] Next
- [X] Web
- [X] Android
- [X] iOS

### Additional Information

This affects all platforms from my testing

**Comment by makkarMeenu** [comment]
Hey @jono-allen , `Pressable` and `Button` takes `:active` props to style when pressed. We need to update the documentation for the same.  Hence, this is not a bug. Please feel free to discuss if you have any doubts.
