### ISSUE TITLE
[Select] defaultValue doesn't use the corresponding label

### ISSUE THREAD

**Issue by freddybreitenstein** [gluestack/gluestack-ui#1194]
### Description

Using defaultValue should use the corresponding label of that value but it doesn't. Only after manually selecting a value shows the label

### gluestack-ui Version

0.1.55

### Platform

- [x] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

Here's a screenshot:
![image](https://github.com/gluestack/gluestack-ui/assets/3595072/c06bb8a0-7bf5-43bf-8613-e2f7ececf780)

**Comment by Viraj-10** [comment]
Hey @freddybreitenstein, We have `selectedLabel` prop which let's you set initial label for select component. 
I see that documentation doesn't have that prop. I will update the docs. 
Thanks for reporting Issue.

**Comment by pierrebiver** [comment]
Hello @Viraj-10 , Using selectedLabel does not work either using the latest version of Gluestack-UI, I only see the ID when setting both, selectedLabel and selectedValue.

**Comment by shadowgroundz** [comment]
> Hello @Viraj-10 , Using selectedLabel does not work either using the latest version of Gluestack-UI, I only see the ID when setting both, selectedLabel and selectedValue.

I agree with you. But with the latest version, how can I set value programmatically? Let's say I have 2 select: SelectA & SelectB. I want the clear value of SelectB when I change SelectA. Value from form library success to clear field value, but your component can't change. Only change with the user input

**Comment by jerryhuangyu** [comment]
initialLabel works

> 'selectedLabel' is deprecated.ts(6385)
types.d.ts(11, 8): The declaration was marked as deprecated here.
(property) selectedLabel?: string | undefined
@deprecated — Use initialLabel instead.

**Comment by juandpr** [comment]
`initialLabel` works, but I'm changing it dynamically in my component (using useState) and it does not refresh the selected label.

**Comment by horvathkarolyerp** [comment]
I concur: initialLabel works at first render, there's no way to dynamically change it after that. The selected item can be seen when the select is dropped down, but the label remains unchanged. Guys! Lets's fix this!

**Comment by bohecola** [comment]
> `initialLabel` works, but I'm changing it dynamically in my component (using useState) and it does not refresh the selected label.可以运行，但我正在组件中动态更改它（使用 useState），并且所选标签不会刷新。

same issue
