### ISSUE TITLE
[Button] ButtonGroup space props is invalid

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1203]
### Description

ButtonGroup space props is invalid

### Steps to reproduce

ButtonGroup space props is invalid
```
<ButtonGroup space="sm">
  <Button>
    <ButtonText>button 1</ButtonText>
  </Button>
  <Button>
    <ButtonText>button 2</ButtonText>
  </Button>
</ButtonGroup>
```

### gluestack-ui Version

0.1.55

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by makkarMeenu** [comment]
Hi @BooYeu , it seems to be working for me. https://snack.expo.dev/YNucJDQaO 
Space uses `gap` property now which is implemented in react-native version >=0.71. Can you please check that?

**Comment by BooYeu** [comment]
It is ok in web, but not right in ios & android

**Comment by makkarMeenu** [comment]
Hey, fixed this in the latest version of themed. Please check and revert.

**Comment by BooYeu** [comment]
Thank you ! It is ok now
