### ISSUE TITLE
[typescript] I upgrade to v1.0.1 and the props are all invalid, v0.1.56 is fine

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1218]
### Description

I upgrade to v1.0.1 and the props are all valid

### Steps to reproduce

upgrade to v1.0.1

### gluestack-ui Version

1.0.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by BooYeu** [comment]
![截屏2023-10-08 21 03 50](https://github.com/gluestack/gluestack-ui/assets/16587763/7893af2f-ebd2-4dde-bc59-d089f5d7a10b)

**Comment by BooYeu** [comment]
![截屏2023-10-08 21 04 49](https://github.com/gluestack/gluestack-ui/assets/16587763/2b264063-0451-4f98-9fd5-509c4f3165c3)

**Comment by BooYeu** [comment]
And all the styles lose
![截屏2023-10-08 21 10 03](https://github.com/gluestack/gluestack-ui/assets/16587763/54679af8-1a3f-4bf9-b424-281fb2e0f234)

**Comment by Viraj-10** [comment]
Hey @BooYeu, from version `1.0.2` `@gluestack-ui/themed` will ship without any themed config.
If you want to use default theme config. Please import config from new package from `@gluestack-ui/config`.
```
import { GluestackUIProvider, Button, ButtonText } from "@gluestack-ui/themed";
import { config } from "@gluestack-ui/config";
function App() {
  return (
    <GluestackUIProvider config={config}>
      <Button>
        <ButtonText>Hello world</ButtonText>
      </Button>
    </GluestackUIProvider>
  )
}
```
Please visit this [link](https://gluestack.io/ui/docs/core-concepts/themed-library) from more info.
for customizing theme please visit this [link](https://gluestack.io/ui/docs/theme-configuration/customizing-theme).

**Comment by Viraj-10** [comment]
Hey @pataar, Can you open  new issue regarding typescript. Also please elaborate your issue provide code snippet for better understanding.

**Comment by pataar** [comment]
Sure, here you go: https://github.com/gluestack/gluestack-ui/issues/1243
