### ISSUE TITLE
Toast Component Overlaps with Status Bar in Top Placement Expo

### ISSUE THREAD

**Issue by luiz504** [gluestack/gluestack-ui#1219]
### Description

When triggering a toast with the placement set to "top," it renders under the StatusBar, causing a visibility problem. The toast component should appear above the StatusBar to ensure that notifications are clearly visible to users.

### Steps to reproduce

1. Set up an Expo project with Gluestack.ui.
2. Add a StatusBar to the `App.tsx`
```jsx
      <StatusBar style="dark" translucent />
```
4. Trigger a toast with placement set to 'top' 
```js 
 toast.show({
        placement: 'top',
        render: () => (
          <Toast>
            <Box>
              <Text>Success</Text>
            </Box>
          </Toast>
        ),
      })```
5. Observe the toast appearing below the StatusBar.

Expected Behavior:
The toast should appear above the StatusBar, ensuring clear visibility and readability of the notification.

Actual Behavior:
The toast renders below the StatusBar, making it difficult for users to see the notification clearly.

Additional Information:
This issue affects the usability of the application. It's crucial to address this problem to maintain a seamless user experience.



### gluestack-ui Version

1.0.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Other Platform

_No response_

### Additional Information

_No response_

**Comment by Viraj-10** [comment]
Hey @luiz504, `StatusBar` doesn't come as view or element in `react-native`. Currently with `react-native` it is not possible(AFAIK). you can give `marginTop` or render it under `safeAreaView`. If you have any solution please feel free to reopen.
