### ISSUE TITLE
Toast nativeID error

### ISSUE THREAD

**Issue by luiz504** [gluestack/gluestack-ui#1220]
### Description

I encountered multiple issues while working with the Toast component in Gluestack UI versions 0.1.53 and 1.0.1

### Steps to reproduce

Following the toast doc: https://gluestack.io/ui/docs/components/feedback/toast 

![image](https://github.com/gluestack/gluestack-ui/assets/53402833/14fcc09c-b051-4466-98c5-fb17e0d0b390)

##Issues

1: Outdated Props:
The sample provided references props `variant` and `action`, which do not exist anymore in the 1.0.1 version of Gluestack UI. Documentation and samples should be updated to reflect the current props available.

2: Error with nativeID:
When attempting to use nativeID as shown in the sample, it triggers an error, hindering the proper functionality of the component.
### Screen Shots

 - Usage
![image](https://github.com/gluestack/gluestack-ui/assets/53402833/771aa8fe-0a5f-48d3-99a8-b2e869a2ad7f)

- Error
![image](https://github.com/gluestack/gluestack-ui/assets/53402833/52e98b08-4df8-41dd-baa2-1bc756dc5aff)

I had this issue on the versions @0.1.53 and @1.0.1

### gluestack-ui Version

1.0.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by luiz504** [comment]
The render method does not return any param value, I was needing the `id` to be able to dismiss the toast `onPress`, but it comes `undefined`.

**Comment by Viraj-10** [comment]
Hey @luiz504,Thanks for reporting the issue. 
- `action` and `variant` is themed props if you want to use them you have to use default config from `@gluestack-ui/config`. you can read more [here](https://gluestack.io/ui/docs/theme-configuration/theme/default-components). 
- We will have a look in second issue regarding `nativeID`.
