### ISSUE TITLE
Link not work in documentation

### ISSUE THREAD

**Issue by jishat** [gluestack/gluestack-ui#1221]
### Description

A link is not work in Inputs component

### Steps to reproduce

1. Go to '[Link](https://gluestack.io/ui/docs/components/forms/input)' 
2. Click on "Unstyled" tab
3. Click on "link"
4. See 404 not found
![chrome-capture-2023-9-9](https://github.com/gluestack/gluestack-ui/assets/48252409/41420d57-0d63-41ca-8ebb-dba277891f08)

### gluestack-ui Version

1.0.0

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

I will can fix it. Basically, the link should be "https://gluestack.io/ui/docs/theme-configuration/customizing-theme"

**Comment by makkarMeenu** [comment]
Thanks for reporting. 
Yes, you can send a PR for the same.

**Comment by jishat** [comment]
Ok. Thank you very much

**Comment by Viraj-10** [comment]
Hey @jishat, This issue has been resolved. website will be up in few hours. Thanks for your contribution.
