### ISSUE TITLE
Add global search in Documentation

### ISSUE THREAD

**Issue by jishat** [gluestack/gluestack-ui#1237]
### Description

Add a search field so that developer can search within the entire documentation for their desired solution

### Problem Statement

If I want to seek any component or config system then we can't search it. So it's very hard to find my needs.

### Proposed Solution or API

You can use [Algolia](https://www.algolia.com)  which is very powerful and also popular. Most of the popular libraries use Algolia for search in documentation

### Additional Information

If Algolia is the best solution for glustack-ui then I can build it.

**Comment by Viraj-10** [comment]
Hey @jishat, We have this in our pipeline.

**Comment by jishat** [comment]
Great! Sounds good.

**Comment by makkarMeenu** [comment]
We have added the documentation search, thanks for bringing into notice.
