### ISSUE TITLE
Typescript doesn't recognize aliases

### ISSUE THREAD

**Issue by pataar** [gluestack/gluestack-ui#1243]
### Description

Even though the config is loaded as documented, Typescript can't recognize the set aliases

### Steps to reproduce

1. Install gluestack as documented
2. Make sure that you use Typescript

### gluestack-ui Version

1.0.3

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![image](https://github.com/gluestack/gluestack-ui/assets/3403851/6b17c6f7-0042-4e8d-9ef7-476d329cbf5d)

![image](https://github.com/gluestack/gluestack-ui/assets/3403851/ff2cb993-ba67-4dc6-afd3-ed20ba00289d)

![image](https://github.com/gluestack/gluestack-ui/assets/3403851/d2ab3654-040d-42f7-8adb-26f18c481fc9)

**Comment by surajahmed** [comment]
@pataar Can you please try updating `@gluestack-style/react` and `@gluestack-ui/themed` to the latest?

**Comment by Simoon-F** [comment]
same.
