### ISSUE TITLE
Cannot "npm run build" with vanilla Next project

### ISSUE THREAD

**Issue by twocs** [gluestack/gluestack-ui#1244]
### Description

Out of the box should permit "npm run build" with vanilla project (no changes whatsoever)

### CodeSandbox/Snack link

https://codesandbox.io/p/sandbox/hardcore-dust-72pv3z

### Steps to reproduce

Following instructions at https://gluestack.io/ui/docs/getting-started/installation.

I ran "npm create gluestack", then selected Next.js. I'm able to run "npm run dev" fine, but it fails at "npm run build". What am I doing wrong? I really expected that the basic project would work, and there's no indication in https://gluestack.io/ui/docs/guides/install-nextjs that I'm doing anything unusual for "New Project".

```sh
$ nvm use 18
Now using node v18.18.0 (npm v9.8.1)
$ npm create gluestack
◇  What would you like to build?
│  Web app
│
◇  What is the  name  of your application?
│  my-app
│
◇  Would you like to use App Router?
│  Yes
│
●   Using  npm install --legacy-peer-deps 
$ cd my-app
$ npm run dev
```
All the above works fine. But `npm run build` does not work on a brand new project, and the lint errors are indecipherable to me.
```sh
$ npm run build

> next-app-router-app@1.0.0 build
> next build

- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types  
- info Collecting page data  
[    ] - info Generating static pages (0/4)Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
<truncated>
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
<truncated>
- info Generating static pages (4/4)

> Export encountered errors on following paths:
    /page: /
```

`npm run start` won't work from there since the export failed to complete.

### gluestack-ui Version

1.0.0

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @twocs, This issue is resolved if you are using same template, please run `npm install next@latest`.
Otherwise you can create a new repo using same way. we have updated that template. please feel free to report similar issue here I will open this issue.
