### ISSUE TITLE
HStack not workin in version 1.0.0

### ISSUE THREAD

**Issue by r083rt** [gluestack/gluestack-ui#1245]
### Description

HStack not working when I create a new project using react native CLI. This problem not happen in version 0.2.51.

### gluestack-ui Version

1.0.0

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @r083rt, In order to work default styling of the components you have to pass config in `GluestackUIProvider`.
```
import { GluestackUIProvider, Button, ButtonText } from "@gluestack-ui/themed";
import { config } from "@gluestack-ui/config";
function App() {
  return (
    <GluestackUIProvider config={config}>
      <Button>
        <ButtonText>Hello world</ButtonText>
      </Button>
    </GluestackUIProvider>
  )
}
```

**Comment by r083rt** [comment]
> Hey @r083rt, In order to work default styling of the components you have to pass config in `GluestackUIProvider`.
> 
> ```
> import { GluestackUIProvider, Button, ButtonText } from "@gluestack-ui/themed";
> import { config } from "@gluestack-ui/config";
> function App() {
>   return (
>     <GluestackUIProvider config={config}>
>       <Button>
>         <ButtonText>Hello world</ButtonText>
>       </Button>
>     </GluestackUIProvider>
>   )
> }
> ```

import {GluestackUIProvider} from '@gluestack-ui/themed';
import {LogBox, SafeAreaView} from 'react-native';
import {config} from './gluestack-ui.config.ts';
import Navigator from './routes';
import NetInfo from '@react-native-community/netinfo';
import React, {useEffect} from 'react';
export default function App({children}) {
  LogBox.ignoreAllLogs();
  useEffect(() => {
    const handleConnectivityChange = state => {
      console.log('Connection type: ', state.type);
      console.log('Is connected? ', state.isConnected);
    };
    const unsubscribe = NetInfo.addEventListener(handleConnectivityChange);
    return () => {
      unsubscribe();
    };
  }, []);
  return (
    <SafeAreaView
      style={{
        flex: 1,
      }}>
      <GluestackUIProvider config={config}>
        <Navigator />
      </GluestackUIProvider>
    </SafeAreaView>
  );
}
Here's my code. I already have a project using gluestack ui. the problem did'nt exists in version 0.2.51

**Comment by Viraj-10** [comment]
Hey @r083rt, please follow this steps.

1. run `npx gluestack-ui-scripts eject-theme`.
2. go to `config` folder.
3. find `gluestack-ui.config.ts`.
4. replace your `tokens` and `aliases`(Don't changes anything else).
5. import this `config` and pass this config to `GluestackUIProvider`.

if you want to customised your components and theme please checkout this [doc](https://gluestack.io/ui/docs/theme-configuration/customizing-theme)

**Comment by ryuji-orca** [comment]
I ran into the same problem, but it looked like the config path had changed from ```@gluestack-ui/themed``` to ```@gluestack-ui/config```.

I changed the path and set it up like this [template](https://github.com/gluestack/expo-head-starter-kit/blob/1c2b98e0ee88a3e33673bd7fa7051758b7c00814/gluestack-ui.config.ts
) and it solved the problem.

``` tsx
// import { createConfig, config } from "@gluestack-ui/themed"
import { config as defaultConfig } from '@gluestack-ui/config';

```

**Comment by ryuji-orca** [comment]
📝PS

I did a ```yarn insrtall``` and it said ```@gluestack-ui/config``` path is invalid.
I looked at the [commits](https://github.com/gluestack/gluestack-ui/commit/17beaa10706c6b456a534838da205b30ef2e189e)  and saw that the [documentation(step 1.5)](https://gluestack.io/ui/docs/guides/install-expo) had been updated, so I think following that will solve the problem.

```
yarn add @gluestack-ui/config@latest
```
OR
```
npm i @gluestack-ui/config@latest
```

**Comment by Viraj-10** [comment]
Hey @ryuji-orca, Does this resolved your issue?

**Comment by ryuji-orca** [comment]
@Viraj-10 
I solved the problem by following the above procedure!
However, I can't close this issue because I didn't make this issue.
