### ISSUE TITLE
Add documentation on module augmentation when using custom theme/config

### ISSUE THREAD

**Issue by thedatasnok** [gluestack/gluestack-ui#1250]
### Description

It would be nice to have documentation for how to use module augmentation to allow autocompletion of custom tokens. 

### Problem Statement

When using a custom config, any new tokens introduced are not included when autocompleting style utility props on components.

### Proposed Solution or API

This is how I solved it in my project: 

```typescript
import { createConfig, config as defaultConfig } from '@gluestack-ui/themed';

export const config = createConfig({
  ...defaultConfig.theme,
  tokens: {
    colors: {
      myColor: '#fafafa',
    },
  },
});
 
export type Config = typeof config;

declare module '@gluestack-ui/themed' {
  interface IConfig extends Config {}
}
```

### Additional Information

I'm happy to submit a PR if you don't have other plans for this.

**Comment by thedatasnok** [comment]
It seems `UIConfig` is the correct type to define using module augmentation now. 
I would expect it to be part of the documentation here https://gluestack.io/ui/docs/theme-configuration/customizing-theme

**Comment by Viraj-10** [comment]
Hey @thedatasnok, Now in order to mke custom config we recommend using `eject-theme` script. This includes all the typing inside `gluestack-ui.config.ts`. So users doesn't have to do it. 
I would recommend you to which to new config via eject-theme and copy paste your tokens there.

**Comment by ts-candide** [comment]
Using the `eject-theme` script results in the entirety of the config and component theme files being present in the project. This creates a maintenance burden as the project will now need to check if any of the default config has changed when `gluestack-ui/themed` is updated.

It would be really nice to use a system such as the OP proposed, whereby you take the default config from `@gluestack-ui/config` and modify it to add variants, etc, whilst still having TypeScript work correctly.

**Comment by raphaeljcm** [comment]
I totally agree with the guy from above!
