### ISSUE TITLE
Tooltip makes button flicker, and sometimes not working at all

### ISSUE THREAD

**Issue by maantrifork** [gluestack/gluestack-ui#1270]
### Description

Tooltip makes button flicker, and sometimes not working at all

### CodeSandbox/Snack link

https://snack.expo.dev/p6x5bQZAE

### Steps to reproduce

Create a button in as a tooltip trigger.

See effect in snack.

### gluestack-ui Version

1.0.3

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by makkarMeenu** [comment]
Hey, thanks for reporting. We will fix it in the next release.
For a workaround, pass `h={undefined}` for now.
