### ISSUE TITLE
[ActionSheet] Input in ActionSheet can't automatically scrolled into view. The error still exists

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1272]
### Description

I submitted an issue before. But the error still exists

### Steps to reproduce

The issue is https://github.com/gluestack/gluestack-ui/issues/906

### gluestack-ui Version

1.0.4

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by Viraj-10** [comment]
Hey, @BooYeu, Please look into docs example [here](https://gluestack.io/ui/docs/components/disclosure/actionsheet). on how to you can work on `Keyboard handling` using `KeyboardAvoidingView`.

**Comment by lhguerra** [comment]
I still cant make it work on iPhone

**Comment by lhguerra** [comment]
Ps.: on Android it was already working even before adding the KeyboardAvoidingView

**Comment by ragnarob** [comment]
+1, this is not working on 1.0.13 for ios

**Comment by lhguerra** [comment]
works like a charm! thank you!
