### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by andrconstruction** [gluestack/gluestack-ui#1275]
### Description

During switch between light and dark themes

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.4

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![image](https://github.com/gluestack/gluestack-ui/assets/7435330/4d87008d-5757-4056-b997-94fd6f4ed1b2)

Copied a part of code from kithchensink-demo, and during switch themes, using  toggleColorMode , i getting this error

**Comment by ankit-tailor** [comment]
Hey @andrconstruction, Can you try latest version of `@gluestack-style/react`?

**Comment by andrconstruction** [comment]
> Hey @andrconstruction, Can you try latest version of `@gluestack-style/react`?

I'll try

**Comment by andrconstruction** [comment]
> Hey @andrconstruction, Can you try latest version of `@gluestack-style/react`?

Yes it helped
