### ISSUE TITLE
Using the Theme component on Android may lead to a blank page.

### ISSUE THREAD

**Issue by Vvaraz** [gluestack/gluestack-ui#1282]
### Description

I had multiple stack Navigators and required dark mode adaptation for my application. To achieve this, I utilized gluestack with react navigation v6. According to the documentation at https://gluestack.io/style/docs/configuration/themes, when using tokens within the theme, it is necessary to utilize the Theme component in conjunction with the StyledProvider component. However, when I imported the Theme component, the navigation page ended up blank.

### Steps to reproduce

1. npx gluestack-ui-scripts eject-theme，export config and configure theme 
2. Configure any Stack navigator pages， and use the gluestack provider with Theme components

### gluestack-ui Version

1.0.3

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

![image](https://github.com/gluestack/gluestack-ui/assets/73987251/21095723-0e43-40d5-bc3f-b9291f7db6a9)

**Comment by rayan1810** [comment]
Hi @Vvaraz , this is on us we will fix this with the next release. Theme Component renders a View, because of which your layout might be breaking and we are adding the support for passing styled props to that View.

**Comment by rayan1810** [comment]
Will be fixed with this PR: https://github.com/gluestack/gluestack-style/pull/500

**Comment by Vvaraz** [comment]
> Hi @Vvaraz , this is on us we will fix this with the next release. Theme Component renders a View, because of which your layout might be breaking and we are adding the support for passing styled props to that View.

Ok,Based on my current actions, I have commented out the View component of ThemeContext.Provider in Theme.tsx and uses patch-package,looks like this:
`diff --git a/node_modules/@gluestack-style/react/src/Theme.tsx b/node_modules/@gluestack-style/react/src/Theme.tsx
index 4a3bae2..5e0fefc 100644
--- a/node_modules/@gluestack-style/react/src/Theme.tsx
+++ b/node_modules/@gluestack-style/react/src/Theme.tsx
@@ -22,7 +22,8 @@ export const Theme: React.FC<{
   return (
     <ThemeContext.Provider value={contextValue}>
       {/* @ts-ignore */}
-      <View dataSet={{ 'theme-id': name }}>{children}</View>
+      {/* <View dataSet={{ 'theme-id': name }}>{children}</View> */}
+      {children}
     </ThemeContext.Provider>
   );
 };`

**Comment by rayan1810** [comment]
Hey @Vvaraz, commenting out View will break the Theme in the Web application.
