### ISSUE TITLE
Will you plan implement warning styls for button and etc

### ISSUE THREAD

**Issue by andrconstruction** [gluestack/gluestack-ui#1283]
### Description

Will you plan implement warning styls for buttons and etc

### Problem Statement
no warning styles

### Proposed Solution or API

implement warning styls for button and etc

**Comment by Viraj-10** [comment]
Hey @andrconstruction, can you share code example and elaborate more ?

**Comment by andrconstruction** [comment]
I meant next : at this moment has only four attribute an action's type using for buttons or other compoments this is a  <pirmary|secondary|positive|negative> for comparsion in the native-base colorschemes was a little bit more for example it  - 'warning' style, but in gluestack-ui it excluded, should I implements my own styles and customize themes for it, or it will be include next verions?

**Comment by makkarMeenu** [comment]
@andrconstruction There is no plan of adding more variants to it. You will need to customize the theme and add your styles.
 However, we can help you with the desired style of yours.
