### ISSUE TITLE
[BUG] Inconsistency in NavBar Products Tab 

### ISSUE THREAD

**Issue by 3xp10it3r** [gluestack/gluestack-ui#1286]
### Description

Double clicking on Products works perfectly, but when clicking on arrow icon, it doesn't closes. (Minor Bug)

### Steps to reproduce

1. Go to https://gluestack.io/
2. Double Click on Arrow Icon right to Products tab in Navbar
4. See inconsistency 

### gluestack-ui Version

1.0

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Additional Information

Video Link : https://drive.google.com/file/d/14ZNLV-duZbBKOzs3uwa3_oMhvFNHAAvj/view?usp=sharing

**Comment by 3xp10it3r** [comment]
I would like to work on this, if this gets assined to me.

**Comment by amars29** [comment]
Thanks for reporting. This issue has been resolved now.
