### ISSUE TITLE
[Enhancement] : Unstyled components section code look blurry on Gluestack web landing page

### ISSUE THREAD

**Issue by 3xp10it3r** [gluestack/gluestack-ui#1287]
### Description

Code part looks blurry seeks more attention.

![Screenshot 2023-10-16 at 10 36 02 AM](https://github.com/gluestack/gluestack-ui/assets/65729055/54025f0b-e34e-40a2-ae9e-6644535b495b)

### Problem Statement

Code part looks blurry seeks more attention.

### Proposed Solution or API

Increase visibility of the code part.

### Additional Information

Would like to work on this issue.

**Comment by surajahmed** [comment]
@3xp10it3r Thanks for reporting this. We've updated the landing page.
