### ISSUE TITLE
Modal components break the app

### ISSUE THREAD

**Issue by lhguerra** [gluestack/gluestack-ui#1291]
### Description

I'm using the modal just like the [example in the docs](https://gluestack.io/ui/docs/components/overlay/modal) and it breaks my app.

### Steps to reproduce

1. Add any modal to any screen, I've got the following error with backdrop and modal content components: 
![image](https://github.com/gluestack/gluestack-ui/assets/4529663/a7db41a8-45ec-4da8-a400-00d8fa92768f)

### gluestack-ui Version

0.1.56

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @lhguerra, Please upgrade to latest version of `@gluestack-ui/themed`. here is a working snack example [link](https://snack.expo.dev/@viraj_10/modal-working-example).

**Comment by lhguerra** [comment]
Nice to know we are in version 1 already, I have completely missed that :sweat_smile: 

Thank you!
