### ISSUE TITLE
[ActionSheet] the animation has something wrong first time.

### ISSUE THREAD

**Issue by llr101** [gluestack/gluestack-ui#1301]
### Description

the animation has something wrong first time. The actionsheet slides from top when open it first time

### Steps to reproduce

https://github.com/gluestack/gluestack-ui/assets/16587763/2db923c6-bb1f-43fa-856c-edaef5ef06c3

### gluestack-ui Version

1.0.6

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by Viraj-10** [comment]
Hey @BooYeu, Thanks for reporting we will have look.

**Comment by vilenleung** [comment]
i usually trigger this bug on iPhone.

**Comment by vilenleung** [comment]
Any update?
It still happy in my app.
"@gluestack-style/react": "1.0.26",
"@gluestack-ui/config": "1.0.8",
"@gluestack-ui/themed": "1.0.25",

**Comment by vilenleung** [comment]
https://github.com/gluestack/gluestack-ui/assets/97012521/f384ca7c-88c6-45d5-a8d6-19d7c5cd72cc

**Comment by Viraj-10** [comment]
Hey @vilenleung, This issues are fixed. Please upgrade to lastest version of `@gluestack-ui/config`,`@gluestack-ui/themed`,`@gluestack-style/react`.

**Comment by ludwighen** [comment]
Any updates on this? I still have it in the latest version.

**Comment by yngfoxx** [comment]
> Any updates on this? I still have it in the latest version.

+1

**Comment by Rossella-Mascia-Neosyn** [comment]
i have the same issue

**Comment by yngfoxx** [comment]
I was able to create a temporary solution to this (imo it is good enough)
here's the gist https://gist.github.com/yngfoxx/7aaeee666fa5a66c72da85f83e35d3db

**Comment by yngfoxx** [comment]
> > I was able to create a temporary solution to this (imo it is good enough) here's the gist https://gist.github.com/yngfoxx/7aaeee666fa5a66c72da85f83e35d3db
> 
> Do I need to make a patch or do I need to create the component in my project?

You need to create the component.

**Comment by Rossella-Mascia-Neosyn** [comment]
> > > I was able to create a temporary solution to this (imo it is good enough) here's the gist https://gist.github.com/yngfoxx/7aaeee666fa5a66c72da85f83e35d3db
> > 
> > 
> > Do I need to make a patch or do I need to create the component in my project?
> 
> You need to create the component.

all right thanks a lot

**Comment by zainkhas** [comment]
Same issue on.
```
    "@gluestack-style/react": "^1.0.56",
    "@gluestack-ui/config": "^1.1.18",
    "@gluestack-ui/themed": "^1.1.26",
```

**Comment by rajat693** [comment]
Hi,
We have tested this issue on Expo v50 and v51 across all platforms. Please share a code snippet or your package.json file to help us recreate and fix the issue.
Thank you.

**Comment by rajat693** [comment]
We are closing this issue for now. If the issue reoccurs or if you have any further questions or concerns, please feel free to reopen it. We're here to help!
Thank you.
