### ISSUE TITLE
Toasts not working possibly due to nativeID

### ISSUE THREAD

**Issue by milesingrams** [gluestack/gluestack-ui#1303]
### Description

When trying to use Toasts an error is thrown

### Steps to reproduce

1. Follow docs to use toasts

2. When Toast has nativeID on it passed from toast.show render function it throws an error

<img width="395" alt="Screen Shot 2023-10-17 at 11 53 52 PM" src="https://github.com/gluestack/gluestack-ui/assets/4930881/3f9eba95-5dff-4874-8a36-2116c6560d35">

### gluestack-ui Version

1.0.6

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

It also looks like Toasts arent working on the documentation website page;

**Comment by milesingrams** [comment]
Looks like casting to string solves it on native
```
<Toast nativeID={String(id)} />
```

**Comment by Viraj-10** [comment]
Hey @milesingrams, Thanks for reporting we have this issue in docs. It will reflect soon.
