### ISSUE TITLE
Issue installing @gluestack-ui/config with pnpm

### ISSUE THREAD

**Issue by ondra-marik** [gluestack/gluestack-ui#1313]
### Description

Failing to install @gluestack-ui/config possibly due to incorrect peer dependency

### Steps to reproduce

1. open existing react native cli project
2. try installing @gluestack-ui/config dependency with pnpm

### gluestack-ui Version

1.0.7

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Using pnpm, @gluestack-ui/config is not automatically installed, when trying to install it manually with `pnpm add @gluestack-ui/config` I'm getting error `@gluestack-style/themed is not in the npm registry, or you have no permission to fetch it.`. Checked the `package.json` for `@gluestack.ui/config`, it seems peer dependency is misconfigured causing installation to fail.

**Comment by Viraj-10** [comment]
Hey @ondra-marik, Thanks for reporting issue. We have fixed this issue in our latest version of `@gluestack-ui/config@1.0.3`. Let me know if doesn't work.
