### ISSUE TITLE
Property 'variant' does not exist

### ISSUE THREAD

**Issue by lhguerra** [gluestack/gluestack-ui#1314]
### Description

After my latest update, the variant prop started to give several type errors.

### Steps to reproduce

1. Add Heading or Radio components with a variant
2. Typescript will fail saying property variant does not exist on those components

My code:
```
<Heading variant="actionSheet">Order</Heading>
```

Full error message:
```
error TS2322: Type '{ children: Element; variant: string; value: SortDirection; }' is not assignable to type 'IntrinsicAttributes & InterfaceRadio & Omit<Omit<Omit<PressableProps & RefAttributes<View>, never> & Partial<...> & Partial<...> & { ...; }, "animationComponentGluestack">, "ref"> & RefAttributes<...>'.
  Property 'variant' does not exist on type 'IntrinsicAttributes & InterfaceRadio & Omit<Omit<Omit<PressableProps & RefAttributes<View>, never> & Partial<...> & Partial<...> & { ...; }, "animationComponentGluestack">, "ref"> & RefAttributes<...>'.
```

### gluestack-ui Version

1.0.7

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @lhguerra, Can you install latest version of `@gluestack-style/react` and check once?

**Comment by lhguerra** [comment]
I'm still getting it, here are the versions I'm running:
```
➜  mobileApp git:(stage) ✗ npm list | grep glue
├── @gluestack-style/react@1.0.7
├── @gluestack-ui/config@1.0.3
├── @gluestack-ui/themed@1.0.7
```

**Comment by lhguerra** [comment]
Ps.: maybe its worth to mention I've ejected the theme.

**Comment by Viraj-10** [comment]
Hey @lhguerra, inside your `gluestack-ui.config.ts`. Please check at the end this code matches or replace it this code.
it should.
```

type Config = typeof gluestackUIConfig; // Assuming `config` is defined elsewhere

type Components = typeof componentsConfig;

export const componentsConfig = createComponents(componentsTheme);

export type { UIConfig, UIComponents } from '@gluestack-ui/themed';

export interface IConfig {}
export interface IComponents {}

declare module '@gluestack-ui/themed' {
  interface UIConfig extends Omit<Config, keyof IConfig>, IConfig {}
  interface UIComponents
    extends Omit<Components, keyof IComponents>,
      IComponents {}
}

export const config = {
  ...gluestackUIConfig,
  components: componentsConfig,
};

```

**Comment by lhguerra** [comment]
It's the same, except i have some token overrides also in the config object

**Comment by ankit-tailor** [comment]
Hey @lhguerra,  I have tried updating the variant of the Heading component by ejecting the theme. It is working for me. It would be great if you could provide minimal reproduction of the issue.

**Comment by lhguerra** [comment]
Hey, I have identified my variants weren´t inside the 'variant' key. A bit confusing since the structure is variants -> variant -> myVariant but I got it working.
