### ISSUE TITLE
ButtonSpinner should be an instance of Spinner not ActivityIndicator

### ISSUE THREAD

**Issue by milesingrams** [gluestack/gluestack-ui#1324]
### Description

Theme applied to Spinner does not apply to ButtonSpinner

### gluestack-ui Version

1.0.8

### Additional Information

https://github.com/gluestack/gluestack-ui/blob/main/packages/themed/src/components/Button/styled-components/Spinner.tsx

While ButtonText uses the gluestack Text component ButtonSpinner does not use the gluestack Spinner component and therefore doesnt properly get themed if you change the Spinner component.

**Comment by akash3gtm** [comment]
Hi @milesingrams , could you provide an expo snack or a code sandbox example of the code you're writing.

**Comment by Viraj-10** [comment]
Good point @milesingrams. we will fix this. You can create a PR as well you find any spare time.

**Comment by makkarMeenu** [comment]
This has been fixed in the latest version of `@gluestack-ui/themed` . Thanks for pointing out.

**Comment by lhguerra** [comment]
This way, how can I set a default color for the spinner?
