### ISSUE TITLE
The select component is not working inside an actionsheet

### ISSUE THREAD

**Issue by Kreshnik** [gluestack/gluestack-ui#1325]
### Description

I am using https://github.com/ammarahm-ed/react-native-actions-sheet and want to place a select component in its content, however, the select component is not showing as the created actionsheet from the select is in the background

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

Latest

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by Viraj-10** [comment]
Hey @Kreshnik, I would Suggest use [Actionsheet](https://gluestack.io/ui/docs/components/disclosure/actionsheet) from `@gluestack-ui/themed`. With [react-native-actions-sheet](https://github.com/ammarahm-ed/react-native-actions-sheet). We don't have control over rendered View of action-sheet overlay. 
Still Provide me with snack example I will have a look.
