### ISSUE TITLE
Unstyled - GluestackUIProvider warning for missing config.

### ISSUE THREAD

**Issue by hristo87** [gluestack/gluestack-ui#1326]
### Description

Why does the documentation indicate that when using an Unstyled -  'gluestack-ui' (without installing '@gluestack-ui/config@latest'), you need to use 'GluestackUIProvider'? In reality, even without 'GluestackUIProvider,' you can still import and use all the components from '@gluestack-ui/themed'. So, what is the purpose of wrapping the app in 'GluestackUIProvider' for the Unstyled variation? However, I would like to clarify and possibly remove this from the documentation because it is potentially misleading.

### gluestack-ui Version

1.0.8

### Platform

- [ ] Expo
- [x] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![image](https://github.com/gluestack/gluestack-ui/assets/102364045/09cbc324-7ee9-4172-ae5a-b6c58068ce52)

**Comment by NikolayDonev** [comment]
The same happens on my end. The only way I don't get a warning is if I install the theme and add config.
It looked like the config param is optional though...

**Comment by Viraj-10** [comment]
Hey @hristo87 @NikolayDonev, `GluestackUIProvider` Comes with `ToastProvider`, `OverlayProvider`  and other internal functionality which is required. If you don't want to use the `@gluestack-ui/themed`. You can use more low-level packages such as `@gluestack-ui/button`. We currently don't have documentation for this but you can reference `@gluestack-ui/themed`.

**Comment by hristo87** [comment]
Hey @Viraj-10, it seems you didn't quite catch my point. I can still use '@gluestack-ui/themed' even without wrapping it with 'GluestackUIProvider.' The issue I'm facing is with the documentation. There's an example in the documentation (check the image above) where the component is wrapped in 'GluestackUIProvider' without a 'config' prop. However, if you follow this example, it triggers a warning indicating a missing 'config.' I believe this might be a mistake in the documentation. If it's not a mistake, I'd like to understand how it's supposed to work to avoid this warning.

**Comment by hristo87** [comment]
I see, thank you for clarifying this!

**Comment by conghai** [comment]
And can’t use multiple GluestackUIProvier, too.
I try use 2 different config, but it only apply for rootConfig, not apply childConfig

```
<GluestackUIProvider config={rootConfig}>
   <SomeComponent>
    ….
       <GluestackUIProvider config={config2}
         <ChildComponent /> // <—- This not apply config2 (still rootConfig)
      </GluestackUIProvider>
   …
</GluestackUIProvider>
```

**Comment by rayan1810-dev** [comment]
Hey @conghai , we do not support multiple providers. The solution to your usecase is themes, please have a look at https://gluestack.io/style/docs/configuration/themes . This is the feature of gluestack-style which is the underlying styling engine.

**Comment by rayan1810** [comment]
Hey @conghai , we do not support multiple GluestackUIProviers, for your use-case I feel you should check out https://gluestack.io/style/docs/configuration/themes. `Themes` is a feature of gluestack-style the underlying style engine that powers gluestack-ui. 

PS: Nested themes are not supported yet, we are working on it.

**Comment by conghai** [comment]
Is there any solution to watch Mobile on Desktop/Tablet?
Because I have an app that allows users to preview the mobile UI template (without iframe or webview)

On the old NativeBase, I used Nested Provider and set the config as follows to force all use `base`
```
_themeCfg.breakpoints = {
      base: 0,
      sm: 999995,
      md: 999996,
      lg: 999997,
      xl: 999998,
      '2xl': 999999,
    };
```

Thanks for your help!

**Comment by rayan1810** [comment]
That's interesting, we will assess your use case and let you know if this can be achieved with the currently available solutions else we will incorporate support for your use case in our road map.

**Comment by conghai** [comment]
I have checked again with the configs below for Nested GluestackUIProvider

```
const _nestedCfg: any = _.cloneDeep(GSConfig);
_nestedCfg.tokens.breakpoints = {
  'base': 0,
  'xs': 9999919,
  'sm': 9999929,
  'md': 9999939,
  'lg': 9999949,
  'xl': 9999959,
};

_nestedCfg.tokens.mediaQueries = {
  base: '@media screen and (min-width: 0)',
  xs: '@media screen and (min-width: 9999919px)',
  sm: '@media screen and (min-width: 9999929px)',
  md: '@media screen and (min-width: 9999939px)',
  lg: '@media screen and (min-width: 9999949px)',
  xl: '@media screen and (min-width: 9999959px)',
};

const nestedCfg = createConfig(_nestedCfg);

/**
 * Main App
 */

export default () => {
  return (
    <GluestackUIProvider config={GSConfig}>

      // ...
      // Some components here
      // ...

      <GluestackUIProvider config={nestedCfg}>
        <NestedRender /> // <--- Test for this Component
      </GluestackUIProvider>

       // ...
       // Some components here
       // ...

    </GluestackUIProvider>
  );
}


/**
 * NestedRender
 */

const NestedRender = () => {
  return (
    <Box sx={{
      '@base': {
        bgColor: '$red500',
      },
      '@md': {
        bgColor: '$green500',
      },
    }}>
      <Text>Hello NestedRender</Text>
    </Box>
  )
};
```

=> Native App on IPAD  `NestedRender` has bgColor => `RED` => `Correct`
but it's wrong on **Desktop web** => alway show bgColor => `GREEN`

```
useBreakpointValue => Correct for all
```

Have any solution for Desktop Web?

Thanks so much GlueStack Team!

**Comment by hristo87** [comment]
@conghai hey m8, could you please stop using this bug  report for personnel chat and open your own bug/question if you would like to clarify something, because your questions doesn`t have anything related to the bug itself. Thanks!

**Comment by makkarMeenu** [comment]
Hey @conghai , please make another issue for your concern. This is misleading in this particular issue context. 

Hey @hristo87 , we have fixed the unstyled version i.e. not passing the config. Please upgrade to the latest version of `@gluestack-style/react ` to `1.0.15`.

**Comment by hristo87** [comment]
@makkarMeenu unfortunately your fix didn`t work at least for me. Check the images bellow, may be I am mistaken somewhere?:
![image](https://github.com/gluestack/gluestack-ui/assets/102364045/ec21ba0c-ab5b-4bbe-9e29-787a7674f6a5) 
![image](https://github.com/gluestack/gluestack-ui/assets/102364045/60f3a94d-ba52-4158-b20c-bb6e76b8492e)
![image](https://github.com/gluestack/gluestack-ui/assets/102364045/e869f105-8be2-49f2-ba7d-3dc9a44820ef)

**Comment by makkarMeenu** [comment]
Hey @hristo87,  this warning is supposed to be there.  In most of the cases users want to use the unstyled version of `gluestack-ui` and then pass their own config. If you will pass your own config, this warning will get removed. May I know your usecase of using `gluestack-ui` where you don't want to pass the config at all?

**Comment by hristo87** [comment]
@makkarMeenu regarding the use case, i don`t get it either from the example mentioned in your documentation, if you're encountering a warning when wrapping your application in GluestackUIProvider (without config provided), and you find that there's no apparent use case for GluestackUIProvider, it might be a bit misleading to include it in the documentation. Why should we use GluestackUIProvider (without config provided), if there is no particular use case to do it and in the same time it give you a warning?

It's important to note that, in a previous conversation, your colleague @Viraj-10  mentioned that the warning is not expected behavior. However, I could not get what was the fix of this 'bug', when at the end is an expected behavior.

Please consider this just as a feedback, but removing the mention of GluestackUIProvider (without config provided) from the documentation or explicitly stating that the warning is expected behavior will improve the overall experience. Further clarification on the use case of GluestackUIProvider (without config provided) in our documentation would be greatly appreciated.

**Comment by makkarMeenu** [comment]
@hristo87, I appreciate the additional information and support. I now understand your point, and I acknowledge my previous misunderstanding. We are actively addressing the unnecessary config warning in the unstyled version and working on updating the documentation accordingly.
We will keep you informed once the fix is implemented.

**Comment by makkarMeenu** [comment]
This is fixed in the latest version of `@gluestack-ui/themed` i.e. `1.0.18` , please check once.

**Comment by NikolayDonev** [comment]
@makkarMeenu can you explain what is the use case of not providing config? Is it documented yet?

**Comment by makkarMeenu** [comment]
> @makkarMeenu can you explain what is the use case of not providing config? Is it documented yet?

We have not yet documented this. It doesn't have a significant use case. If you omit the configuration, you can still provide inline styles as utility props to the component, such as backgroundColor="blue". This enables you to access all the features of [gluestack-style](https://gluestack.io/style) without a default configuration, meaning that all style features will function without default tokens.

I hope this explanation is clear. Feel free to reach out if you have any additional questions; we're here to assist you.

**Comment by NikolayDonev** [comment]
> > @makkarMeenu can you explain what is the use case of not providing config? Is it documented yet?
> 
> We have not yet documented this. It doesn't have a significant use case. If you omit the configuration, you can still provide inline styles as utility props to the component, such as backgroundColor="blue". This enables you to access all the features of [gluestack-style](https://gluestack.io/style) without a default configuration, meaning that all style features will function without default tokens.
> 
> I hope this explanation is clear. Feel free to reach out if you have any additional questions; we're here to assist you.

That's fair enough, thank you!

**Comment by hristo87** [comment]
@makkarMeenu confirm its fixed!
