### ISSUE TITLE
Unable to resolve module ./Provider : None of these files exist

### ISSUE THREAD

**Issue by yaxiaoliu** [gluestack/gluestack-ui#1328]
### Description

build with react-native failed, some error like

### Steps to reproduce

1. `yarn add @gluestack-ui/themed @gluestack-style/react react-native-svg@13.4.0`
2. `pod install`
3. ` import {GluestackUIProvider} from '@gluestack-ui/themed'` at my `App.tsx`
4. Then run `yarn ios` will build failed for below errors\

<img width="566" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/37991688/ee5e8f7e-68cf-4895-92fb-dff167b2acdd">
<img width="850" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/37991688/98b0e346-2ea6-489e-837f-b3cfa1d76715">

and tsconfing.json has some errors:
```json
[{
	"resource": "/Users/xxx/work/code/github/xxx/node_modules/@gluestack-ui/themed/tsconfig.json",
	"owner": "typescript",
	"severity": 8,
	"message": "No inputs were found in config file '/Users/xxx/work/code/github/xxx/node_modules/@gluestack-ui/themed/tsconfig.json'. Specified 'include' paths were '[\"./src\"]' and 'exclude' paths were '[\"node_modules\",\"example\"]'.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```
<img width="1232" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/37991688/b8c5e5a5-b40e-4215-ae8c-5d23a96b4ca0">

### gluestack-ui Version

1.0.8

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

"@gluestack-style/react": "^1.0.8",
    "@gluestack-ui/themed": "^1.0.8",

**Comment by surajahmed** [comment]
@yaxiaoliu Thanks for reporting this. We'll look into this.

**Comment by makkarMeenu** [comment]
@yaxiaoliu , This is working fine in the latest versions. Please try using `npm create gluestack@latest` . Re-open the issue if not resolved.
