### ISSUE TITLE
Card recipe docs renders image wrong

### ISSUE THREAD

**Issue by mattaningram** [gluestack/gluestack-ui#1329]
### Description

Image should span full card width instead of maxing out at 80px

### Steps to reproduce

Go to https://gluestack.io/ui/docs/recipes/card and see the issue: 
<img width="864" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/955092/5c1ffde8-71ca-4822-a154-9ce8c9eb2aca">

Inspect element to see `width: 80px` is applied to image wrapper:
<img width="560" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/955092/9fb3f5b1-fc5c-4720-9dfe-ba00f376beb7">

### gluestack-ui Version

1.0.3

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Additional Information

As you can see in the second image I linked, it is extremely hard to debug Gluestack styles in production because there is nothing in the generated class names or attributes that lets you figure out where the style is coming from. The `80px` width is not being created by the example code in docs, it is coming from somewhere else in the repo.

Additionally I tried to fix this myself and make a PR, but the current situation with branches in Gluestack is so messy that I wasn't confident I was changing the right thing. The image that appears in the Card recipe comes from a URL that is only in the `documentation` branch and not in the `main` branch. The URL in `main` just doesn't work.

My team is looking to switch to Gluestack, but the lack of clarity around some of this stuff is making us a little worried. It would help out a lot if it was more clear what branch your documentation is being generated by (And why it isn't the `main` branch) and if the docs were more robust in general (please add search functionality).

Also please please please delete old branches when they are no longer relevant.

**Comment by Viraj-10** [comment]
Hey @mattaningram, Thanks for reporting this issue. We have fix this issue on our docs.
