### ISSUE TITLE
Hooks release v0.1.8 breaks the build

### ISSUE THREAD

**Issue by hristo87** [gluestack/gluestack-ui#1333]
### Description

After upgrading hooks (under the hood) from version 0.1.7 to 0.1.8, the build process encountered a missing module error ( @react-native-community/clipboard ). This issue needs to be addressed to ensure that the package can be upgraded without causing build failures.

### gluestack-ui Version

1.0.8

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information
![image](https://github.com/gluestack/gluestack-ui/assets/102364045/4196de2a-d31a-4fd0-bb7f-2bed65ced1a9)

**Comment by Viraj-10** [comment]
Hey @hristo87, Please try again issue is fixed now.

**Comment by hristo87** [comment]
Confirm, its fixed! Thanks
