### ISSUE TITLE
Toasts should respect SafeArea region on android

### ISSUE THREAD

**Issue by milesingrams** [gluestack/gluestack-ui#1334]
### Description

Toasts show up under android UI

### Steps to reproduce

Use any toast on android.

<img width="429" alt="Screen Shot 2023-10-25 at 5 59 20 PM" src="https://github.com/gluestack/gluestack-ui/assets/4930881/b5db36b2-0aa8-4c0c-9e1b-b5f50d940d1a">

### gluestack-ui Version

1.0.8

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @milesingrams, Please wrap your `GluestackUIProvider` with `safeAreaView`.
Recommend using `useSafeAreaInsets` from `react-native-safe-area-context`. 
```
<SafeAreaView style={{ marginTop: 100 }}>
      <GluestackUIProvider config={config}>
        <Example />
      </GluestackUIProvider>
    </SafeAreaView>
```

Closing this issue feel free to reopen it.

**Comment by milesingrams** [comment]
This will make the entire app inset which is not desirable most of the time. I think there needs to be a way to handle this specifically for Toasts

**Comment by LipLoody** [comment]
Still present on last version !

@Viraj-10 can you reopen it?

**Comment by milesingrams** [comment]
Same still an issue

**Comment by milesingrams** [comment]
@Viraj-10 Please reopen this! It's still and issue

**Comment by zainkhas** [comment]
My App is wrapped in a RootView and has padding set by `useSafeAreaInsets` but still the Toast does not have any spacing on top in Android, it works fine in iOS.

**Comment by luiz504** [comment]
> Hey @milesingrams, Please wrap your `GluestackUIProvider` with `safeAreaView`. Recommend using `useSafeAreaInsets` from `react-native-safe-area-context`.
> 
> ```
> <SafeAreaView style={{ marginTop: 100 }}>
>       <GluestackUIProvider config={config}>
>         <Example />
>       </GluestackUIProvider>
>     </SafeAreaView>
> ```
> 
> Closing this issue feel free to reopen it.

Following this approach caused double margin because the `SafeAreaView` already ignore the `Statusbar` height for the most components but not for toasts, I got it working following your tip to use the `useSafeAreaInsets` direct with a `View` element
![image](https://github.com/user-attachments/assets/9bba4a1b-d889-42bd-b831-9a5df7153fa4)

**Comment by stefan-schweiger** [comment]
@Viraj-10 just wrapping everything in a safe area provider really is not an option as it will mess with for example navigation elements. It would be great if the overlay provider would just accept some margins which are only provided to the overlays but not to the children.
