### ISSUE TITLE
 The custom theme color defined in sx is not effective.

### ISSUE THREAD

**Issue by Vvaraz** [gluestack/gluestack-ui#1338]
### Description

I want the custom colors defined in the theme to take effect within the Interaction Props in sx.

### Steps to reproduce

-  Some styles were customized using createConfig({}). The theme contains both light and dark variants.

![image](https://github.com/gluestack/gluestack-ui/assets/73987251/50a69d0b-5552-4d24-a2d6-6d73352b3709)

- They are being used in the sx Interaction Props, for example:

`sx={{
        ":checked": {
                borderColor: "$border-checked",
        },
}}`
 with the purpose of changing the borderColor when the checkbox is checked.

- The result is that it did not works. However, when changing to use colors from tokens such as `$rose200`, 
 ![image](https://github.com/gluestack/gluestack-ui/assets/73987251/5590cdfb-67fa-428f-aea9-9ecbed70142c)
the color works. I’m not sure if this is a bug or if there is an issue with the method I am using.And it seems that there are no annotations in the documentation either.

### gluestack-ui Version

@gluestack-ui/themed  v1.0.3

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

I have been a fan of this UI style since starting with Native Base, but it seems that the docs for Gluestack has many issues currently. I hope the docs can be gradually improved over time.

**Comment by rayan1810** [comment]
Hey @Vvaraz, This is a bug. I'm looking into this and will fix it with the highest priority since it's a major issue. I will share more updates soon. As far as docs are concerned we are constantly updating the data and love the feedback from the real users. Please feel free to drop any other issues with the docs in detail too.

**Comment by surajahmed** [comment]
Closing this issue since it has been resolved in the latest version. If the problem continues, please feel free to reopen it.
