### ISSUE TITLE
The toast examples don't work in the docs

### ISSUE THREAD

**Issue by richawo** [gluestack/gluestack-ui#1343]
### Description

Clicking on the toast buttons in the doc examples don't do anything (ref: https://gluestack.io/ui/docs/components/feedback/toast)

### Steps to reproduce

1. Go to: https://gluestack.io/ui/docs/components/feedback/toast
2. Click on any of the buttons in the examples
3. Nothing happens

### gluestack-ui Version

N/A

### Platform

N/A

### Additional Information

This happened on brave browser

**Comment by surajahmed** [comment]
Thanks for reporting this @richawo. We're working on it.

**Comment by Viraj-10** [comment]
Hey @richawo, Issue is fixed.
