### ISSUE TITLE
Select component not opening on iOS without "pointerEvents='none'" input prop

### ISSUE THREAD

**Issue by niemisami** [gluestack/gluestack-ui#1353]
### Description

Select component not opening on iOS without "pointerEvents='none'" input prop

### CodeSandbox/Snack link

https://snack.expo.dev/@madbooster/gluestack-ui-platform-specific?platform=ios

### Steps to reproduce

1. Go to Snack https://snack.expo.dev/@madbooster/gluestack-ui-platform-specific?platform=ios
2. Open Snack with iOS device or browser emulator
3. Clicking first Select doesn't work on iOS
4. Clicking second Select works on iOS

### gluestack-ui Version

1.0.10

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

`SelectInput` omits the `SelectTrigger` onPress event somehow. Easy fix is to add `pointerEvents='none'` prop.

`<SelectInput textAlign='center' pointerEvents='none' />`

Works fine on Android. Tested on Snack's iOS device as well as on iPhone 12 iOS 16.6.

**Comment by grillorafael** [comment]
I think I’m having the same issue. Although if I press the little arrow it works

**Comment by niemisami** [comment]
> I think I’m having the same issue. Although if I press the little arrow it works

**Comment by niemisami** [comment]
> I think I’m having the same issue. Although if I press the little arrow it works

Yeah that should work well because the icon is rendered with `SelectIcon` which doesn't do that crazy input magic 😄

**Comment by likeSo** [comment]
I have the same problem and press the down arrow icon, it works😂

**Comment by hamsterhomka** [comment]
The same problem, it works only when pressing on the down arrow or when passing pointerEvents="none" to the input

**Comment by madelineleclair** [comment]
> The same problem, it only works when the down arrow is pressed

Had the same issue. I changed to a pressable and it works fine.
