### ISSUE TITLE
Incomplete Options Display in Select Component

### ISSUE THREAD

**Issue by LucasHayashi** [gluestack/gluestack-ui#1355]
### Description

When using the Select component from GlueStack UI with a large number of options, the dropdown menu does not display all the options properly. Upon expanding the select menu, the last few options are not visible, and there is no scroll functionality to access these hidden options.

### CodeSandbox/Snack link

https://snack.expo.dev/@lucashayashi1/gluestack-ui-incomplete-options-display?platform=android

### Steps to reproduce

1. Use the provided App component with a large number of options.
2. Expand the select dropdown menu.

**Expected Behavior:**
All options should be displayed within the dropdown menu, and users should be able to scroll through the options to access hidden ones.

**Actual Behavior:**
The last options are not visible within the dropdown, and there is no scroll functionality to access these options.

### gluestack-ui Version

1.0.10

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [x] iOS

**Comment by surajahmed** [comment]
@LucasHayashi You can try wrapping all `SelectItem` with a `ScrollView`. This will fix your issue. Let us know if this doesn't work. Thanks
