### ISSUE TITLE
Pressable and sx prop type issue

### ISSUE THREAD

**Issue by coycoylaniba** [gluestack/gluestack-ui#1356]
### Description

pressable doesn't have function type on children like the one exported in `react-native`, also sx props on components like `Button` does not have `_text`, etc. 

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.11

### Platform

- [ ] Expo
- [x] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![image](https://github.com/gluestack/gluestack-ui/assets/47078705/2495581e-990b-4c82-9a2a-115a92ce1a6e)

![image](https://github.com/gluestack/gluestack-ui/assets/47078705/bb787f58-3777-4333-a69d-839b650c1ea9)

**Comment by surajahmed** [comment]
@coycoylaniba Thanks for reporting this. We'll fix this soon.

**Comment by ankit-tailor** [comment]
Hey @coycoylaniba, Please upgrade `@gluestack-ui/themed`, `@gluestack-style/react` to latest version. Let me know if that works for you. Feel free to re-open the issue in case you face any issues.

**Comment by coycoylaniba** [comment]
@ankit-tailor thanks! will update you soon.
