### ISSUE TITLE
`InputField` can still be active even on `Input` `isDisabled` is true

### ISSUE THREAD

**Issue by coycoylaniba** [gluestack/gluestack-ui#1357]
### Description

a bug where even if the `Input` component has `isDisabled` prop true, child `InputField` is not affected and still can be inputed.

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.11

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![image](https://github.com/gluestack/gluestack-ui/assets/47078705/11fd69d2-5657-4be6-b47c-d16dd0ffed14)

**Comment by LucasHayashi** [comment]
Hi, @coycoylaniba ! I'm facing the same issue as you. Native Base highly recommended using GlueStack UI, but unfortunately, it's riddled with bugs 👎.

**Comment by coycoylaniba** [comment]
yeah, i might use Native Base until this issues are fixed.

**Comment by Viraj-10** [comment]
Hey @coycoylaniba , @LucasHayashi, This issue has been fixed in latest version of `@gluestack-ui/themed`

**Comment by coycoylaniba** [comment]
@Viraj-10 thanks!
