### ISSUE TITLE
Input component does not support name property

### ISSUE THREAD

**Issue by savalaram-redkar** [gluestack/gluestack-ui#1362]
### Description

I'm using Gluestack-ui with Next.js 14 and trying to implement for Server actions where I needed a name prop on Input, but I'm receiving an error stating that 'Property 'name' does not exist'.

### gluestack-ui Version

1.0.11

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @savalaram-redkar, Can you provide small implementation of this? a github repo or codeSandBox ?

**Comment by savalaram-redkar** [comment]
Hey @Viraj-10,

I created a [Codesandbox](https://codesandbox.io/p/sandbox/nextjs-gluestack-8x26pg?file=%2Fapp%2Fpage.tsx%3A18%2C21) to demonstrate this issue.

**Comment by makkarMeenu** [comment]
@savalaram-redkar , I am not able to run this codesandbox. However, can you reproduce this issue with `TextInput` from `react-native`.

**Comment by makkarMeenu** [comment]
@savalaram-redkar Also, can you please create a minimal repository, it would help reproduce it better.

**Comment by makkarMeenu** [comment]
Hi @savalaram-redkar , as per [this](https://github.com/necolas/react-native-web/issues/1793) issue, react-native-web doesn't support web only props. Please consider the solutions given for React-native.

**Comment by kaushal270401** [comment]
I'm trying to implement Server actions where I need a 'name' prop on the Input component. However, I'm receiving an error '

I've checked the documentation for Gluestack-ui , but I couldn't find any information on whether the 'name' prop is supported or if there's an alternative approach.

Here is the link to the repository where I'm facing this issue: 
![Screenshot from 2023-12-20 15-41-52](https://github.com/gluestack/gluestack-ui/assets/115895025/8f30b3b5-62fc-420b-931c-c2016386a52c)
[https://github.com/kaushal270401/Server-Action](url)
