### ISSUE TITLE
Uncaught Error When Running 'eject-theme' Script

### ISSUE THREAD

**Issue by hristo87** [gluestack/gluestack-ui#1372]
### Description

I'm encountering an issue with the eject-theme script (`npx gluestack-ui-scripts eject-theme`). When I run this script, it consistently results in an exit code of 1, which usually indicates an error. The intriguing part is that it doesn't visibly throw an error message when run manually. This issue is consistent both when I execute the script from my custom CLI tool and when running it manually.  While the script doesn't provide an error message, my custom CLI tool is designed to catch uncaught errors, resulting in an unhandled exception. This unhandled exception is problematic because it lacks specific details about the error itself.  Although everything which is expected from your script is done, I'm facing difficulty identifying the specific error source, and I suspect there might be an underlying issue that needs to be addressed.

### Steps to reproduce

1. Install new react native cli project:  `npx react-native@latest init AwesomeProject`
2. Navigate to the newly created directory: cd ./AwesomeProject
3. Install all gluestack-ui dependencies:  `yarn add @gluestack-ui/themed @gluestack-style/react react-native-svg@13.4.0 @gluestack-ui/config@latest`
4. Eject the theme: `npx gluestack-ui-scripts eject-theme`
5. `$LastExitCode` - returns 1 (check the images bellow)

### gluestack-ui Version

1.0.13

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Clean react native CLI project with gluestack-ui installed and theme config ejected:
![image](https://github.com/gluestack/gluestack-ui/assets/102364045/f6597920-9e9f-425f-b43b-8f348894de20)

My custom CLI during set up: 
![image](https://github.com/gluestack/gluestack-ui/assets/102364045/d741ecdc-a065-4e96-b950-5f2de25ab853)

**Comment by surajahmed** [comment]
@hristo87 Thanks for reporting this. We're working on it.

**Comment by makkarMeenu** [comment]
Hey @hristo87 , I followed all the steps you mentioned to reproduce this issue. This is working fine and I am unable to reproduce this.  Can you help me further?
<img width="719" alt="Screenshot 2023-11-29 at 3 52 32 PM" src="https://github.com/gluestack/gluestack-ui/assets/54400869/1e18d7cd-b8f3-4394-8ba0-39f4ee0238aa">

**Comment by hristo87** [comment]
@makkarMeenu try to check last exit code right after ejection. It returns 1 which means a generic error code :
on windows: $LastExitCode (check the last step No.5 from steps to reproduce)
on mac (i`m not sure): $?

**Comment by makkarMeenu** [comment]
I will try to reproduce on Windows and let you know.

**Comment by makkarMeenu** [comment]
@hristo87 Until I arrange windows, I can send you zip of latest config folder which gets added after running the script. Let me know if you need that.

**Comment by hristo87** [comment]
@makkarMeenu Thank you, but I actually don't need it. I can generate this folder myself. The script is working fine, and it's doing exactly what it should. However, the issue is that there is an uncaught error somewhere, coming from your script. I'm certain that it's originating from the `npx gluestack-ui-scripts eject-theme` command and if it wasn`t my custom cli I probably would not catch it as well.

**Comment by Viraj-10** [comment]
hey @hristo87, can you share your script?

**Comment by hristo87** [comment]
Well the error seems resolved by the newest script version, so I am closing this issue.
