### ISSUE TITLE
The "Actionsheet" component throws an error when closing.

### ISSUE THREAD

**Issue by yeyuliang2015** [gluestack/gluestack-ui#1373]
### Description

The "Actionsheet" component throws an error when closing.

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

0.1.56

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

### Additional Information

<img width="279" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/10381702/bc5a0c1b-cd3b-4358-95e9-6cd786950e11">

**Comment by yeyuliang2015** [comment]
Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'.
TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'.
    at $9bf71ea28793e738$export$2d6ec8fc375ceafa (webpack://di-adp-app/./node_modules/@react-aria/focus/dist/import.mjs?:597:27)
    at $9bf71ea28793e738$var$focusFirstInScope (webpack://di-adp-app/./node_modules/@react-aria/focus/dist/import.mjs?:423:18)
    at eval (webpack://di-adp-app/./node_modules/@react-aria/focus/dist/import.mjs?:353:67)

**Comment by yeyuliang2015** [comment]
![image](https://github.com/gluestack/gluestack-ui/assets/10381702/4bba2bd6-f8d4-48dc-80a4-e6651b6a29f9)
"The component is very laggy, and there are performance issues. It has already been upgraded to the latest version."

**Comment by likeSo** [comment]
Same problem here 
<img width="887" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/12247340/30ba0260-9aa9-4a1f-ac96-86c09e334536">

**Comment by AmandeepPooni** [comment]
This component works out of the box on android but not on web. Got around by using this ActionSheet component instead:
https://gorhom.github.io/react-native-bottom-sheet/

**Comment by Viraj-10** [comment]
Hey @yeyuliang2015, This issue has been fixed in latest version of `@gluestack-ui/themed`.
