### ISSUE TITLE
When Toast disappears, there is a transparent background that cannot be eliminated

### ISSUE THREAD

**Issue by Signinu** [gluestack/gluestack-ui#1374]
### Description

I want to eliminate the transparent background

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.13

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [x] iOS

**Comment by Signinu** [comment]
![Uploading 20231109-142917.jpeg…]()

**Comment by makkarMeenu** [comment]
Can you please elaborate the issue and create an error reproducible snack for the same?

**Comment by Signinu** [comment]
Modify file config/theme/Toast.ts:
info: {
        bg: 'rgba(0,0,0,0.8)',
        ...
      },
This bug is only on android，ios not have this bug，now，i on Android use system toast，ios use gluestack-ui toast

**Comment by Viraj-10** [comment]
@Signinu Thanks for reporting this issue.
we have fixed this issue in `v1.0.18` version of `@gluestack-ui/themed` and `v1.0.4` of `@gluestack-ui/config`.
for ejected theme please check changelog [here](https://github.com/gluestack/gluestack-ui/releases/tag/%40gluestack-ui%2Fthemed%401.0.18)
