### ISSUE TITLE
Web: Input type password with FormControl onPress the icon doesn't change

### ISSUE THREAD

**Issue by TrejoCode** [gluestack/gluestack-ui#1377]
### Description

On the docs pages: Input type password with FormControl on press the icon the icon doesn't change as expected

### Steps to reproduce

1. Go to 'https://gluestack.io/ui/docs/components/forms/input' 
2. Input type password with FormControl
3. Click on 'EyeIcon' 
4. Only change the type of input, but the icon doesn't change

![image](https://github.com/gluestack/gluestack-ui/assets/16879799/cd7861c2-076e-48e3-b3fc-3c39305214fa)

### gluestack-ui Version

1.0.11

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by surajahmed** [comment]
@TrejoCode Thanks for reporting this. We'll look into this.

**Comment by makkarMeenu** [comment]
For now, we have removed the support for this feature while using `as` prop. We will make the necessary changes in the documentation.
As an alternative, please use
```
{showPassword
  ? 
     <Icon
        as={EyeIcon}
        color={'$pink400'}
      />
      :
      <Icon
        as={ EyeOffIcon}
        color={'$blue400'}
      />}

**Comment by makkarMeenu** [comment]
Hey @TrejoCode , this has been fixed in the latest version of `@gluestack-style/react` i.e. `1.0.16`. Please upgrade and open the issue again otherwise. 
Here is the [snack](https://snack.expo.dev/vNA-F5mi6) demonstrating the same.

**Comment by iuhisa** [comment]
Hello @makkarMeenu, I have the same issue.

When I changed [snack](https://snack.expo.dev/vNA-F5mi6) to above,
"@gluestack-ui/config": "1.0.10",
"@gluestack-ui/themed": "1.0.30",
"@gluestack-style/react": "1.0.29"
only the color changed.
