### ISSUE TITLE
isDisabled and isReadonly does not work as I expected

### ISSUE THREAD

**Issue by arsalannury** [gluestack/gluestack-ui#1378]
### Description

the input isReadonly and isDisabled does not work and after setting them I still can change their values

### Steps to reproduce

 <Input
        style={[styles.inputStyle, styleInput]}
        variant="outline"
        size="md"
        isReadOnly={true}
        isDisabled={true}
        isRequired={required}
        width={width ? width : "$full"}
        direction="rtl"
      >
        <InputField
          value={inputValue}
          onChangeText={setValue}
          style={[styles.inputFieldStyle, styleFieldInput]}
          direction="rtl"
          writingDirection="rtl"
          fontFamily="Vazir"
          fontSize={fontSize}
          sx={{ _input: { fontFamily: "Vaizr" } }}
          type={inputType}
        />
        <InputSlot pr={"$3"} pl={"$1"}>
          {icon}
        </InputSlot>
      </Input>

### gluestack-ui Version

1.0.8

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

I tested that on Android, so I don't know about IOS. now I have to control input values with a set value prop which the user can't change this

**Comment by surajahmed** [comment]
@arsalannury Thanks for reporting this. We'll have a look.

**Comment by arsalannury** [comment]
thank you. after updating to the latest version, the problem was solved
