### ISSUE TITLE
Cannot create a controlled Select component

### ISSUE THREAD

**Issue by ugur-akin** [gluestack/gluestack-ui#1379]
### Description

Cannot create a Select component value of which is maintained in React state (i.e. controlled). 

### CodeSandbox/Snack link

https://snack.expo.dev/@ugur.akin/gluestack-ui-controlled-select-component?platform=ios

## Summary

Cannot reflect selection changes to react state using a `Select` component. This can be useful for various reasons - in my case, I need it to validate other input values based on user's selection.

### What I've tried
- **Method 1**: Using the `value` and `onChangeText` props on the `SelectInput` component.
- **Method 2**: Using the `onValueChanged` function to trigger an update and using a `ref` to grab `SelectInput` value.

1. Go to [this expo snack](https://snack.expo.dev/@ugur.akin/gluestack-ui-controlled-select-component?platform=ios). 
2. Change either selection.
3. Expected behaviour: React state is updated to reflect selected value.
4. Observed behaviour: React state remains unchanged (**Method 1**) or is set to `undefined` (**Method 2**).

### gluestack-ui Version

1.0.10

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by surajahmed** [comment]
@ugur-akin I have created a working example of this. Please look into this. 
https://snack.expo.dev/@sacontrack/gluestack-ui-controlled-select-component?platform=ios

Please do let us know if you face any other issue.

**Comment by ugur-akin** [comment]
Ah thank you for this, in hindsight I should have tried anyway but the docs slightly mislead me: 
![image](https://github.com/gluestack/gluestack-ui/assets/70963670/814f0ef5-85ae-4d06-9079-7e4ffa41a3b8)

I'm guessing it's not a priority at this point but do you think you could create an issue to update the function signature(s) correctly in the docs?

**Comment by surajahmed** [comment]
Sure @ugur-akin. We'll update our docs. Thanks for the suggestion.
