### ISSUE TITLE
[IOS] once keyboard tap will trigger two onChangeText event when i set value and onChangeText in [TextareaInput] or [InputField with multiple]  and that wrapped in modal

### ISSUE THREAD

**Issue by vilenleung** [gluestack/gluestack-ui#1380]
### Description

Only on IOS, android is ok.

### Steps to reproduce

"@gluestack-style/react": "^1.0.15",
"@gluestack-ui/config": "^1.0.3",
"@gluestack-ui/themed": "^1.0.13",
//ios 17.0
//App.jsx
// "react": "18.2.0"
//"react-native": "0.72.5",
```
import React, { useState } from 'react'

import { GluestackUIProvider } from "@gluestack-ui/themed"
import { config as GluestackConfig } from '@gluestack-ui/config'
import {
  Modal,
  ModalBackdrop,
  ModalContent,
  ModalBody,
  Input,
  InputField,
  Textarea,
  TextareaInput,
  VStack,
} from "@gluestack-ui/themed"

const App = () => {
  const [message1, setMessage1] = useState('')
  const [message2, setMessage2] = useState('')

  return (
    <Modal
      size='lg'
      isOpen={true}
    >
      <ModalBackdrop/>
      <ModalContent>
        <ModalBody>
          <VStack>
            <Input size='md'>
              <InputField multiline value={message1} onChangeText={value => setMessage1(value)}/>
            </Input>
            <Textarea size='md'>
              <TextareaInput value={message2} onChangeText={value => setMessage2(value)}/>
            </Textarea>
          </VStack>
        </ModalBody>
      </ModalContent>
    </Modal>
  )
}

export default () => {
  return (
    <GluestackUIProvider config={GluestackConfig}>
      <App/>
    </GluestackUIProvider>
  )
}

```

### gluestack-ui Version

1.0.13

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by makkarMeenu** [comment]
Hey @vilenleung, I removed the `Input` and `Textarea` from `gluestack-ui` and rendered `TextInput` from `react-native` . I could still face that issue. 
The issue is, modal is getting rendered when the input state changes. 

Best practice for this will be to shift the state declaration in a different component. [Here](https://snack.expo.dev/Fy58t49Cn) is the example of how you can do it.
Let me know if you need any help.

**Comment by lukerlv** [comment]
@makkarMeenu hello，as you mentioned above, how can I retrieve the value back when i confirm the modal?
