### ISSUE TITLE
React Context doesn't work with modal

### ISSUE THREAD

**Issue by hk-skit** [gluestack/gluestack-ui#1393]
### Description

React context is not working with Modal

### CodeSandbox/Snack link

https://snack.expo.dev/@hitesh.kumar/react-context-does-not-work-with-modal?platform=ios

### Steps to reproduce

1. Go to expo linkt
2. Click on show modal.
4. Look at console the context printed is undefined.

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

### Additional Information

It works fine when `useRNModal` is set to `true`. But I can't set it true cause setting it true will mess up the zIndex of toasts. They'll always appear under the modal if useRNModal is set to true.

**Comment by hk-skit** [comment]
@makkarMeenu @akash3gtm Can you help with this? Thanks.

**Comment by akash3gtm** [comment]
hi @hk-skit 
All our overlay components use React Portals, and render the overlay components directly at the level of `GluestackUIProvider`.
If you use the `Context.Provider` inside `GluestackUIProvider`, it won't work. This is a known issue in react.

instead of this,
   ```
<GluestackUIProvider config={config}>
    <MyContext.Provider value={{ greetings: 'Hey, There!!' }}>
        <MyModal />
    </MyContext.Provider>
</GluestackUIProvider>
```

write like this
```
<MyContext.Provider value={{ greetings: 'Hey, There!!' }}>
    <GluestackUIProvider config={config}>
        <MyModal />
    </GluestackUIProvider>
</MyContext.Provider>
```

If the context provider is outside GluestackUIProvider, then at any level inside the context should be available to all components.


> Please note that this issue only applies to overlay components, rest of the components will work as intended.

**Comment by akash3gtm** [comment]
If there is any other issue, please reopen the issue.
For now I have marked it closed.

**Comment by hk-skit** [comment]
@akash3gtm is there any plan to disable the portal behaviour?  Generally `GluestackUIProvider` is added at the root of the application. And it's not always possible to restructure the component tree. Specially when the providers are not global. eg.

```
<GlustStackUIProvider>
    <SomeComponent>
      <SomeOtherComponent>
         <SomeProvider>
           <Modal>
              <SomeConsumer/>
           </Modal>
       </SomeProvider>
    <SomeOtherComponent>
   <SomeComponent>
</GlueStackUIProvider>
```

**Comment by akash3gtm** [comment]
@hk-skit 
As overlay needs to open at the root, we made it like this.
you can put the components anywhere but they will always render at the level of `GlueStackUIProvider`.
It is not possible to resolve this issue.

You would have to maintain your code architecture assuming the render is done at root.

If you could find a way around this problem, let us know. Other users will also benefit from that.

**Comment by Viraj-10** [comment]
Hey @hk-skit, you can find another work around by creating `ModalContext` [here](https://snack.expo.dev/@viraj_10/workaround-for-context-issue?platform=ios) your example with ModalContext Implemented. 
Currently in `react-native` Portals are not supported so we are using context based portals. 
Once we find a better way to use portals we will implement that and remove context based portals.

**Comment by hk-skit** [comment]
@Viraj-10 Sure. Thanks for the clever workaround. Till now, people were only forwarding refs. With this, they'll foward contexts.  😅

**Comment by Viraj-10** [comment]
@hk-skit, Although it's context forward cause I thought you wanted to know how to access context. 
but best practice would have been passing down `greetings` as a prop to `<MyGreetings />` component from modal.

MyModal.tsx
```
 const { greetings } = useMyContext();
  return (
    <Center h={300}>
      <Button onPress={() => setShowModal(true)} ref={ref}>
        <ButtonText>Show Modal</ButtonText>
      </Button>
      <Modal
        isOpen={showModal}
        onClose={() => {
          setShowModal(false);
        }}
        finalFocusRef={ref}>
        <ModalBackdrop />
        <ModalContent>
            <ModalBody>
              <MyGreetings greetings={greetings} />
            </ModalBody>
        </ModalContent>
      </Modal>
    </Center>
  );
```
MyGreetings.tsx
```
const MyGreetings = ({ greetings }) => {
  return <Text>{greetings ?? 'Recevied emtpy context'}</Text>;
};
```
This way `MyGreetings` follows single responsibility principle and can be reused in other places.
