### ISSUE TITLE
Bad behavior of <Actionsheet.Backdrop />

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#140]
Hello guys, I'm here just to propose a "small" change into <Actionsheet.Backdrop /> component.
When we use ```animationPreset="slide"```, it only works if I define ```useRNModal``` too.
Until there, everything ok, but the question is when the actionsheet opens. The backdrop layer animates in slide too... It's too ugly. I think It would be better if even the ```Actionsheet.Content``` animates in ```slide``` mode, the backdrop could stay in ```fadein``` mode... I made a video to exemplify it:

https://user-images.githubusercontent.com/5796053/227669739-ba9ae162-9f91-413a-b918-cf65343b9713.MP4

```tsx
<Actionsheet isOpen={isOpen} onClose={() => setIsOpen(false)} animationPreset="slide" useRNModal>
  <Actionsheet.Backdrop />
  <Actionsheet.Content>
    <Actionsheet.DragIndicatorWrapper>
      <Actionsheet.DragIndicator />
    </Actionsheet.DragIndicatorWrapper>
    <Actionsheet.Item onPress={() => setIsOpen(false)}>
      <Actionsheet.ItemText>Community</Actionsheet.ItemText>
    </Actionsheet.Item>
  </Actionsheet.Content>
</Actionsheet>
```

**Comment by NandoMB** [comment]
And the property ```closeOnOverlayClick``` is not working...

**Comment by NandoMB** [comment]
Thank you @mayank-96!

**Comment by mayank-96** [comment]
Hey @NandoMB, this issue has been fixed. Please upgrade your `Actionsheet` version to `0.2.1`.
Closing this issue, feel free to re-open if you any doubts.

**Comment by NandoMB** [comment]
Thank you @mayank-96! I'll try it.
