### ISSUE TITLE
The positioning of the toast is incorrect.

### ISSUE THREAD

**Issue by dtrongphuc** [gluestack/gluestack-ui#1407]
### Description

The toast items do not align properly when their lengths are different.

### CodeSandbox/Snack link

https://snack.expo.dev/@dtrongphuc/gluestack-toast

### Steps to reproduce

1. Follow the docs to create the toast UI.
2. Set placement="top right".
3. Show multiple toasts with different content and observe that the toast items do not align to the right of the page.

### gluestack-ui Version

1.0.3

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by phatlamhd** [comment]
The same here.

**Comment by makkarMeenu** [comment]
Fixed the above issue in `@gluestack-ui/toast: 1.0.1`. Here is the PR, https://github.com/gluestack/gluestack-ui/pull/1417. Once, we release `@gluestack-ui/themed` with this, this will get fixed.

**Comment by makkarMeenu** [comment]
We have released a new version of `@gluestack-ui/themed` with the fix. Please update.
