### ISSUE TITLE
 Warning: Failed prop type: Invalid prop `role` of value `text` supplied to `TextInput`,

### ISSUE THREAD

**Issue by vilenleung** [gluestack/gluestack-ui#1408]
### Description

 Warning: Failed prop type: Invalid prop `role` of value `text` supplied to `TextInput`, expected one of ["alert","alertdialog","application","article","banner","button","cell","checkbox","columnheader","combobox","complementary","contentinfo","definition","dialog","directory","document","feed","figure","form","grid","group","heading","img","link","list","listitem","log","main","marquee","math","menu","menubar","menuitem","meter","navigation","none","note","option","presentation","progressbar","radio","radiogroup","region","row","rowgroup","rowheader","scrollbar","searchbox","separator","slider","spinbutton","status","summary","switch","tab","table","tablist","tabpanel","term","timer","toolbar","tooltip","tree","treegrid","treeitem"].

### Steps to reproduce

"@gluestack-style/react": "^1.0.16",
"@gluestack-ui/config": "^1.0.3",
"@gluestack-ui/themed": "^1.0.16",
"react": "18.2.0",
"react-native": "0.72.5",
App.jsx

```
import React from 'react'
import { GluestackUIProvider } from "@gluestack-ui/themed"
import { config as GluestackConfig } from '@gluestack-ui/config'

import {
  Modal,
  ModalBackdrop,
  ModalContent,
  ModalHeader,
  Heading,
  ModalBody,
  ModalFooter,
  FormControl,
  FormControlLabel,
  FormControlLabelText,
  Textarea,
  TextareaInput,
} from "@gluestack-ui/themed"

const App = () => {
  return (
    <Modal
      size='lg'
      isOpen={true}
      avoidKeyboard={true}
    >
      <ModalBackdrop/>
      <ModalContent>
        <ModalHeader>
          <Heading size="lg">Title</Heading>
        </ModalHeader>
        <ModalBody>
          <FormControl size='md'>
            <FormControlLabel>
              <FormControlLabelText>Testing</FormControlLabelText>
            </FormControlLabel>
            <Textarea>
              <TextareaInput />
            </Textarea>
          </FormControl>
        </ModalBody>
        <ModalFooter>
        </ModalFooter>
      </ModalContent>
    </Modal>
  )
}

export default () => {
  return (
    <GluestackUIProvider config={GluestackConfig}>
      <App/>
    </GluestackUIProvider>
  )
}
```

### gluestack-ui Version

1.0.16

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by makkarMeenu** [comment]
Thanks for reporting, we will have a look.
