### ISSUE TITLE
(Modal/Alert Dialog/Menu/Select/Popover) are render behind the screen that set the stack screen presentation to "modal" using expo router

### ISSUE THREAD

**Issue by leouie28** [gluestack/gluestack-ui#1410]
### Description

 I have a screen called create.js that sets the presentation on the screen option to "modal". Now, within this screen, I'm attempting to incorporate a (SELECT/MODAL/ALERT DIALOG/POPOVER) components on this screen. The mention  components above are rendered behind the create.js screen. I've attempted to resolve this by setting the z-index of those components to the highest value, but it still renders behind the create.js screen. Even utilizing a custom modal to create a custom select doesn't solve the issue, as it also appears behind the create.js screen, which is configured with the stack screen option representation set to "modal". 
 
![J09BykLmqF6i1jWVkdovja73c75JEaUDgV0nO8bc](https://github.com/gluestack/gluestack-ui/assets/100117314/0cb674d4-6acc-40d9-a07b-a75687b317e1)

 
 Please refer to this if the image did not display which a screenshot illustrating the problem: https://kargax-qat-bucket.s3.ap-southeast-1.amazonaws.com/drivers/J09BykLmqF6i1jWVkdovja73c75JEaUDgV0nO8bc.png

## Structure
```lua
|-- root/
|    |-- app/
|        |-- _layout.tsx
|        |-- create.tsx // <---- this is the screen where i set the stack screen option presentation to "modal" (see the code below)
```

## `_layout.tsx` code
```js
function RootLayoutNav() {
    const colorScheme = useColorScheme();

    return (
        <GluestackUIProvider config={config}>
            <OverlayProvider>
                <Stack>
                    <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
                    <Stack.Screen
                        name="create"
                        options={{ headerShown: false, presentation: 'modal' }}
                    />
                </Stack>
            </OverlayProvider>
        </GluestackUIProvider>
    );
}
```

### gluestack-ui Version

1.0

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Other Platform

*Emulator

**Comment by Gluant101** [comment]
Hey @leouie28, our Devs are looking into the issue.

**Comment by Viraj-10** [comment]
Hey @leouie28, currently all the overlay components use context based portal. In this case expo uses NativeModal which will always comes on top. We are finding solutions to resolve this.
for now you can use `useRNModal` prop which will render component inside `RNModal` so it comes on top. 
PS:- Multiple Modal is not support in this case. Also `Toast` doesn't support `RNModal`. 

```jsx
export default function ModalScreen() {
  const [showActionsheet, setShowActionsheet] = React.useState(false);
  const handleClose = () => setShowActionsheet(false);
  return (
    <View style={styles.container}>
      <Center>
        <Button onPress={() => setShowActionsheet(true)}>
          <ButtonText>Open</ButtonText>
        </Button>
        <Actionsheet isOpen={showActionsheet} onClose={handleClose} useRNModal>
          <ActionsheetBackdrop />
          <ActionsheetContent>
            <ActionsheetDragIndicatorWrapper>
              <ActionsheetDragIndicator />
            </ActionsheetDragIndicatorWrapper>
            <ActionsheetItem onPress={handleClose} isDisabled>
              <ActionsheetItemText>Delete</ActionsheetItemText>
            </ActionsheetItem>
            <ActionsheetItem onPress={handleClose}>
              <ActionsheetItemText>Share</ActionsheetItemText>
            </ActionsheetItem>
            <ActionsheetItem onPress={handleClose}>
              <ActionsheetItemText>Play</ActionsheetItemText>
            </ActionsheetItem>
            <ActionsheetItem onPress={handleClose}>
              <ActionsheetItemText>Favourite</ActionsheetItemText>
            </ActionsheetItem>
            <ActionsheetItem onPress={handleClose}>
              <ActionsheetItemText>Cancel</ActionsheetItemText>
            </ActionsheetItem>
          </ActionsheetContent>
        </Actionsheet>
      </Center>
      <StatusBar style={Platform.OS === "ios" ? "light" : "auto"} />
    </View>
  );
}
```

**Comment by leouie28** [comment]
@Viraj-10  currently working on my solution for this issue, i might create a pr if get luck experimenting solutions.

**Comment by Gluant101** [comment]
@leouie28 Looking forward to your contribution!
