### ISSUE TITLE
input text always keeps the first letter capitalized

### ISSUE THREAD

**Issue by mrsants** [gluestack/gluestack-ui#1411]
### Description

input text always keeps the first letter capitalized, I don't know if this is only in the iOS simulator

### gluestack-ui Version

1.0.17

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by makkarMeenu** [comment]
Hey @mrsants
 This is not an issue but the expected behaviour for `TextInput` from React Native. You can choose to type smallcase if needed.
