### ISSUE TITLE
Toast ui issue on notch screen

### ISSUE THREAD

**Issue by vilenleung** [gluestack/gluestack-ui#1419]
### Description

ui issue

### Steps to reproduce

<img width="754" alt="Screenshot 2023-11-29 at 1 54 36 PM" src="https://github.com/gluestack/gluestack-ui/assets/97012521/f81c74d7-c06b-48bc-9018-aeeef99d5502">
<img width="496" alt="Screenshot 2023-11-29 at 1 54 53 PM" src="https://github.com/gluestack/gluestack-ui/assets/97012521/a539ebea-d533-4227-99ee-175a3012c8cd">
<img width="606" alt="Screenshot 2023-11-29 at 1 55 07 PM" src="https://github.com/gluestack/gluestack-ui/assets/97012521/ff94b2f5-9dcd-4b71-9e22-0c3cfae2f279">
<img width="636" alt="Screenshot 2023-11-29 at 1 55 28 PM" src="https://github.com/gluestack/gluestack-ui/assets/97012521/b81bbc96-469b-4b4c-8df0-5ec672f45aa5">

"@gluestack-style/react": "^1.0.17",
"@gluestack-ui/config": "^1.0.4",
"@gluestack-ui/themed": "^1.0.18",
"react": "18.2.0",
"react-native": "0.72.5",

```
import React, { useEffect } from 'react'
import { GluestackUIProvider, Toast, ToastTitle, useToast } from "@gluestack-ui/themed"
import { config as GluestackConfig } from '@gluestack-ui/config'

const App = () => {
  const toast = useToast()

  useEffect(() => {
    toast.show({
      placement: 'top',
      duration: 4000,
      avoidKeyboard: true,
      render: ({ id }) => {
        return (
          <Toast nativeId={id} action='info' variant='accent'>
            <ToastTitle>Testing</ToastTitle>
          </Toast>
        )
      },
    })
  }, [])
  
  return (
    <> </>
  )
}

export default () => {
  return (
    <GluestackUIProvider config={GluestackConfig}>
      <App/>
    </GluestackUIProvider>
  )
}
```

### gluestack-ui Version

1.0.18

### Platform

- [ ] Expo
- [x] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @vilenleung, Thanks for reporting. We will work on this.
