### ISSUE TITLE
Backdrop component opacity

### ISSUE THREAD

**Issue by nathan-charles** [gluestack/gluestack-ui#1428]
### Description

All components using backdrop like (Modal, ActionSheet) are showing solid without any opacity after upgrading to latest version

### gluestack-ui Version

1.0.19

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @nathan-charles, This issue has been resolved in [@gluestack-ui/config@1.0.5](https://github.com/gluestack/gluestack-ui/releases/tag/%40gluestack-ui/config%401.0.5) and [@gluestack-ui/themed@1.0.20](https://github.com/gluestack/gluestack-ui/releases/tag/%40gluestack-ui/themed%401.0.20).
please upgrade to latest version.

**Comment by vilenleung** [comment]
and @gluestack-style/react@1.0.22
