### ISSUE TITLE
MenuItem onPress not working on web

### ISSUE THREAD

**Issue by mathis-kdio** [gluestack/gluestack-ui#1431]
### Description

The "onPress" property doesn't seem to work on the web with expo

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.19

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @mathis-kdio, Thanks for reporting this issue. We will have a look.

**Comment by mathis-kdio** [comment]
This code works well on mobile, but not on the web. I'm interested if you have a workaround.

```
<Menu
  placement='bottom left'
  trigger={({ ...triggerProps }) => {
    return (
      <Button {...triggerProps} bgColor='#0594ae'>
        <FontAwesome5 name="bars" size={28} color="white"/>
      </Button>
    )
  }}
  closeOnSelect={true}
>
  <MenuItem key="Joueurs" textValue={t("liste_joueurs")} onPress={() =>  this.props.navigation.navigate('ListeJoueur')}>
    <MenuItemLabel size='sm'>{t("liste_joueurs")}</MenuItemLabel>
  </MenuItem>
</Menu>
```

**Comment by Viraj-10** [comment]
Hey @mathis-kdio, you can find workaround [here](https://snack.expo.dev/@viraj_10/menu-item-onselection-change).

**Comment by mathis-kdio** [comment]
Thank you for this workaround. I've tested it and it works well

**Comment by hamsterhomka** [comment]
> Hey @mathis-kdio, you can find workaround [here](https://snack.expo.dev/@viraj_10/menu-item-onselection-change).

Unfortunately, it doesn't work as expected with Expo 49. The menu doesn't close when pressing on MenuItem
