### ISSUE TITLE
There is no way to animate a Button since Button Root is not animatable.

### ISSUE THREAD

**Issue by milesingrams** [gluestack/gluestack-ui#1438]
### Description

`https://github.com/gluestack/gluestack-ui/blob/main/packages/themed/src/components/Button/styled-components/Root.tsx`

<img width="530" alt="Screen Shot 2023-12-04 at 1 30 21 PM" src="https://github.com/gluestack/gluestack-ui/assets/4930881/fc325a75-6820-4528-9fe5-7d922231a9f5">

Notice this doesnt use AnimatedPressable thus button root is not animatable. It would be super useful is there was a way to make any element animatable by passing an animatable prop to styled config object.
It seems cumbersome to have to define if it will ever be animated from the start.

i.e:
```
import { styled } from '@gluestack/style';

const AnimatableButton = styled(Button, {}, {
  animatable: true,
});
```

### Problem Statement

All components and pieces of components should be animatable

### Proposed Solution or API

```
import { styled } from '@gluestack/style';

const AnimatableButton = styled(Button, {}, {
  animatable: true,
});
```

**Comment by ankit-tailor** [comment]
Hey @milesingrams, We have `as` prop through which you can change the component. 
```
<Button as={AnimatedPressable} />
```

Using this API you will be able to animate the component. We are working on adding support to resolve animation props for the same. I'll update you once we release stable version for the same.

**Comment by milesingrams** [comment]
Thanks for the reply! This definitely would resolve my issue. I'll use the "as" prop in the future for these cases

**Comment by surajahmed** [comment]
Closing this issue as this is resolved in the latest version. Feel free to reopen if the issue persists.
