### ISSUE TITLE
Center doesn't justify-contents 'center'

### ISSUE THREAD

**Issue by mini-777** [gluestack/gluestack-ui#1458]
### Description

Center doesn't justify-contents 'center'

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.24

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![Simulator Screenshot - iPhone 15 Pro - 2023-12-07 at 17 17 07](https://github.com/gluestack/gluestack-ui/assets/58356850/1aada66b-0dd2-4a8c-b6e8-0da99801c60b)

**Comment by Viraj-10** [comment]
Hey @mini-777, Please find snack [here](https://snack.expo.dev/@viraj_10/centered-button-using-center-component) for working `Center` component. 
Please let me know if it doesn't work for you.
