### ISSUE TITLE
Animations not working

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1459]
### Description

This is not working

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

This is not working

<img width="647" alt="Screenshot 2023-12-07 at 3 44 50 PM" src="https://github.com/gluestack/gluestack-ui/assets/152247394/55ebe19d-c342-41ce-865e-37640387000e">

**Comment by rcasari1987** [comment]
Hello, yesterday I was testing a bit, and that example works for me. The thing is, you don't get to see it; the animation starts working when the component is mounted. You can try adding a transition to it:

const Box = styled(AnimatedView, {
  ':initial': {opacity: 0},
  ':animate': {opacity: 1},
  ':transition': {
    type: 'timing',
    duration: 1500,
  },
});

**Comment by ankit-tailor** [comment]
Hey @rcasari1987, It's working me. Here is the [snack](https://snack.expo.dev/G2sBhSMkecFmWkVTpUvx_). Let me know if it works for you. Closing the issue for now.
