### ISSUE TITLE
Modal not respecting phone's safe area

### ISSUE THREAD

**Issue by madelineleclair** [gluestack/gluestack-ui#1462]
### Description

Modal not respecting safe area of phone

### Steps to reproduce

1. Create a modal
2. Have it take up the the entire height of the phone
3. The modal takes up all the space and runs into the power bar

![Image](https://github.com/gluestack/gluestack-ui/assets/24612594/39c11510-52db-460b-9e6e-cf2e32724fd5)

### gluestack-ui Version

1.0.24

### Platform

- [x] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

The default modal should use a max height so it doesn't run into this issue.

**Comment by Viraj-10** [comment]
Hey @madelineleclair, Can you share small reproduction of code with snack or github repo?

**Comment by madelineleclair** [comment]
@Viraj-10 I created a [public repo](https://github.com/madelineleclair/gluestack-modal-bug) to show the bug. I am using ios to reproduce it. Use `npm run ios` to start the expo app.

**Comment by rajat693** [comment]
hi @madelineleclair, you can take reference from this:- https://snack.expo.dev/@rajat693/modal-gluestack-ui

**Comment by Viraj-10** [comment]
@madelineleclair, As shown in example user has to control `SafeArea` in project. As we don't want to force users to use any  third party library. User have freedom to choose third party library to achieve this behaviour or create custom safearea logic.
We will try to add docs regarding the same. 
Thanks for reporting this issue.
