### ISSUE TITLE
useToken not resolving token values set in themes

### ISSUE THREAD

**Issue by TomSwift** [gluestack/gluestack-ui#1465]
`useToken` is resolving a given token value to the "default" value in the configuration and doesn't appear to be resolving any overridden value set in an active theme.   

If this is expected behavior, is there a mechanism for me to resolve tokens values taking into account an active theme?   Even if it's a workaround for now that'd be great to understand.

**Comment by ankit-tailor** [comment]
Hey @TomSwift, Please upgrade the `@gluestack-style/react` to latest version. We have added the feature.
