### ISSUE TITLE
Styles missing for print

### ISSUE THREAD

**Issue by vine77** [gluestack/gluestack-ui#1466]
## Issue Description

Due to the use of `@media screen`, gluestack-style styles in a web context are missing when printing the page.

## Motivation or Use Case

We're using gluestack-ui to generate PDFs reports for our app (via headless Chrome).

## Version

Current version, not a regression

## Reproduction steps

Print a page built with gluestack in any modern browser and note that styles are missing.

## Suggest a fix

I [fixed](https://github.com/gluestack/gluestack-style/commit/0b1254ef6fd497cbc2524bf18413dc88e3ff23fd) the issue in a [fork](https://github.com/reperiohealth/gluestack-style) by replacing `@media screen` with `@media all`.

**Comment by Viraj-10** [comment]
Hey @vine77, This has been fixed.
