### ISSUE TITLE
Able to create themed component like MUI

### ISSUE THREAD

**Issue by ducpt-bili** [gluestack/gluestack-ui#1474]
### Description

I want to create component in theme, and treat it like built-in component like MUI. You can checkout this link.
https://mui.com/material-ui/guides/creating-themed-components/

### Problem Statement

I want to create component like a base component, not just override the base Input. ex: FloatLabelInput.

### Proposed Solution or API

You can check out the link above of MUI.

**Comment by Gluant101** [comment]
Thanks for reporting this. We'll update you soon.

**Comment by makkarMeenu** [comment]
Hello @ducpt-bili, you can definitely develop your own component similar to MUI.

I've created a Card component resembling MUI. Take a look at https://snack.expo.dev/uI8Ue74bA and feel free to ask if you have any questions or need further clarification.

**Comment by ducpt-bili** [comment]
Thank you @makkarMeenu, your solution look good to me. 
I will try it. Thanks
