### ISSUE TITLE
Discord: Action sheet and Select components just don't work as expected

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1478]
### Description

J.Daniel — 09/12/2023 18:37
Hello everyone! I hope you are all well. I migrated from NativeBase to Gluestack ui, and everything used to work well but since 5-4 days, the Action sheet and Select components just don't work as expected. The precise issue is that before when I clicked and tapped on the overlays it would close the ActionSheet and the Select would do the same thing as well. But now it just does not work. Has anything changed? any help greatly appreciated please🙏

thatrandybrown — Yesterday at 20:58
it might be that there's a bug in the animations with the most recent release. i had to roll back.

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by vilenleung** [comment]
this bug same as https://github.com/gluestack/gluestack-ui/issues/1478

**Comment by vilenleung** [comment]
Help!!!!!
My app's next deploy task was blocking by this bug.

**Comment by Viraj-10** [comment]
Hey @vilenleung, Can you share a small code?
It's working for I just checked with latest versions.
please make sure you have all the latest versions install and if your config is ejected please compare your config with our latest.

**Comment by BooYeu** [comment]
> Hey @vilenleung, Can you share a small code? It's working for I just checked with latest versions. please make sure you have all the latest versions install and if your config is ejected please compare your config with our latest.

I have same error in android. 
```
const [visible, setVisible] = useState(false)
const handleClose = useCallback(() => setVisible(false), [])

<Actionsheet isOpen={visible} onClose={handleClose} closeOnOverlayClick>
// something...
</Actionsheet>
```

**Comment by vilenleung** [comment]
> > Hey @vilenleung, Can you share a small code? It's working for I just checked with latest versions. please make sure you have all the latest versions install and if your config is ejected please compare your config with our latest.
> 
> I have same error in android.
> 
> ```
> const [visible, setVisible] = useState(false)
> const handleClose = useCallback(() => setVisible(false), [])
> 
> <Actionsheet isOpen={visible} onClose={handleClose} closeOnOverlayClick>
> // something...
> </Actionsheet>
> ```

"@gluestack-style/react": "1.0.26",
"@gluestack-ui/config": "1.0.8",
"@gluestack-ui/themed": "1.0.25",
"react": "18.2.0",
"react-native": "0.72.7",

<img width="447" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/97012521/06557d2d-fb0c-4941-8103-a3a27c53b69f">


```
import React from 'react'
import { 
  GluestackUIProvider,
  Select,
  SelectTrigger,
  SelectInput,
  SelectIcon,
  Icon,
  SelectPortal,
  SelectBackdrop,
  SelectContent,
  SelectDragIndicatorWrapper,
  SelectDragIndicator,
  SelectItem,
} from '@gluestack-ui/themed'
import { config as GluestackConfig } from '@gluestack-ui/config'
import Ionicons from 'react-native-vector-icons/Ionicons'

const App = () => {

  return (
    <Select mt={100}>
      <SelectTrigger variant="outline" size="md">
        <SelectInput placeholder="Select option" />
        <SelectIcon mr="$3">
          <Icon as={Ionicons} name='chevron-down-outline' />
        </SelectIcon>
      </SelectTrigger>
      <SelectPortal>
        <SelectBackdrop />
        <SelectContent>
          <SelectDragIndicatorWrapper>
            <SelectDragIndicator />
          </SelectDragIndicatorWrapper>
          <SelectItem label="UX Research" value="ux" />
          <SelectItem label="Web Development" value="web" />
          <SelectItem
            label="Cross Platform Development Process"
            value="Cross Platform Development Process"
          />
          <SelectItem label="UI Designing" value="ui" isDisabled={true} />
          <SelectItem label="Backend Development" value="backend" />
        </SelectContent>
      </SelectPortal>
    </Select>
  )
}

export default () => {
  return (
    <GluestackUIProvider config={GluestackConfig}>
      <App/>
    </GluestackUIProvider>
  )
}
```

**Comment by vilenleung** [comment]
i haven't eject the config and had try to delete node_modules and pod(ios).
and change
 "@gluestack-style/react": "^1.0.26",
 "@gluestack-ui/config": "^1.0.8",
"@gluestack-ui/themed": "^1.0.25",

TO

"@gluestack-style/react": "1.0.26",
"@gluestack-ui/config": "1.0.8",
"@gluestack-ui/themed": "1.0.25",

**Comment by Viraj-10** [comment]
@vilenleung, Does actionsheet also behaving the same?

**Comment by vilenleung** [comment]
> @vilenleung, is actionsheet also behaving the same?

YES.

**Comment by vilenleung** [comment]
this bug combine https://github.com/gluestack/gluestack-ui/issues/1301 this will produce a horrific consequences.
when i open the actionSheet
the ActionsheetContent will display out of screen and backdrop over on full mobile screen
so that i can't do anything to back,only quit app and reboot.

**Comment by vilenleung** [comment]
https://github.com/gluestack/gluestack-ui/assets/97012521/44745036-a497-4304-a5e2-29416ce4be33

on previous version, i can press backdrop to close and open again until the actionSheet to be normal, but now ......

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
