### ISSUE TITLE
Warning after npm start

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1480]
### Description

Warning after npm start

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Alicia — 03/12/2023 14:53
Hi guys! I am really new to programming and I am trying to build an app with gluestack. I am using the starter kit but run into this warning after I run npm start. Can anyone help check how can I resolve this issues please
[Image](https://discord.com/channels/1050761204852858900/1123159327751028756)

Alicia — 03/12/2023 15:07
I just ran npm --legacy-peer-deps and it showed
[Image](https://discord.com/channels/1050761204852858900/1123159327751028756)

Post Link: https://discord.com/channels/1050761204852858900/1123159327751028756/1180801586444894258

**Comment by surajahmed** [comment]
The issue was resolved by downgrading the metro version in the starter kit, as `expo-router` has a peer dependency on "metro": "^0.76.7". We have updated our starter kits.
Thanks for reporting.
