### ISSUE TITLE
How can I close the Select from code ?

### ISSUE THREAD

**Issue by ArjunKarki** [gluestack/gluestack-ui#1491]
### Description

How can I close the Select from code ?

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

How can I close the Select from code ?

**Comment by surajahmed** [comment]
@ArjunKarki You can pass `isOpen` props to `SelectPortal` component to programmatically open/close select on native devices.

**Comment by ArjunKarki** [comment]
@surajahmed Thanks  but after I add that props, when I select the options ,it didn't close, and I can not set isOpen to false in onValueChange props.

**Comment by Viraj-10** [comment]
Hey @ArjunKarki, you can find controlled select snack [here](https://snack.expo.dev/@viraj_10/controlled-select).
