### ISSUE TITLE
ActionSheet 无法点击遮罩进行关闭

### ISSUE THREAD

**Issue by 7chenys** [gluestack/gluestack-ui#1512]
### Description

这个组件的closeOnOverlayClick设置为true，但还是无法关闭Sheet

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

import React, {useState, useEffect} from 'react';
import {
  Actionsheet,
  ActionsheetBackdrop,
  ActionsheetContent,
  GluestackUIProvider,
  HStack,
  Text,
  Pressable,
  Icon,
  ChevronLeftIcon,
  VStack,
  Box,
} from '@gluestack-ui/themed';
import {config} from '@/themeConfig/gluestack-ui.config';
import {Keyboard} from 'react-native';

interface IProps {
  isOpen: boolean; //是否显示
  dark?: boolean; // 是否暗色主题
  overlayColor?: string; // 遮罩颜色
  closeOnOverlayClick?: boolean; // 点击遮罩是否关闭
  showTitle?: boolean; // 显示标题
  title?: string; // 标题
  leftIcon?: any; // 标题左侧图标
  rightIcon?: any; // 标题右侧图标
  showLeftIcon?: boolean; // 显示标题左侧图标
  showRightIcon?: boolean; // 显示标题右侧图标
  autoClose?: boolean; // 自动关闭 会触发onClose事件
  titleRender?: () => React.ReactNode; // 自定义标题内容
  children?: any; // 插槽
  onClose: () => void; // 关闭事件
  onLeftIconPress?: () => void; // 左侧图标点击事件
  onRightIconPress?: () => void; // 右侧图标点击事件
  onTitlePress?: () => void; // 点击标题
}

export default function YActionSheet({
  isOpen,
  dark = true,
  overlayColor = 'rgba(0,0,0,0)',
  closeOnOverlayClick = true,
  title,
  showTitle = true,
  leftIcon = ChevronLeftIcon,
  rightIcon,
  showLeftIcon = true,
  showRightIcon,
  autoClose = true,
  onClose,
  onLeftIconPress,
  onRightIconPress,
  children,
  titleRender,
  onTitlePress,
}: IProps) {
  const [showActionsheet, setShowActionsheet] = useState(false);
  // 底部内边距 用于替代KeyboardAvoidingView
  const [pb, setPb] = useState(0);

  const handleClose = () => {
    setShowActionsheet(false);
    onClose && typeof onClose === 'function' && onClose();
  };

  const handleLeftIconPress = () => {
    onLeftIconPress && typeof onLeftIconPress === 'function' && onLeftIconPress();
    if (autoClose) {
      handleClose();
    }
  };

  const handleRightIconPress = () => {
    onRightIconPress && typeof onRightIconPress === 'function' && onRightIconPress();
  };

  useEffect(() => {
    setPb(0);
    setShowActionsheet(isOpen);

    if (isOpen) {
      Keyboard.addListener('keyboardDidShow', _keyboardDidShow);
      Keyboard.addListener('keyboardDidHide', _keyboardDidHide);
    } else {
      Keyboard.removeAllListeners('keyboardDidShow');
      Keyboard.removeAllListeners('keyboardDidHide');
    }
  }, [isOpen]);

  // 键盘显示
  const _keyboardDidShow = (e: any) => {
    if (isOpen) {
      // 键盘高度
      setPb(e.endCoordinates.height);
    }
  };

  // 键盘隐藏
  const _keyboardDidHide = () => {
    setPb(0);
  };

  return (
    <Actionsheet isOpen={showActionsheet} onClose={handleClose} zIndex={1} useRNModal={true} closeOnOverlayClick={closeOnOverlayClick}>
      <GluestackUIProvider config={config}>
        <ActionsheetBackdrop bg={overlayColor} />

        <ActionsheetContent borderTopLeftRadius={0} borderTopEndRadius={0} bg={dark ? '#0F0F0F' : '$white'} pb={pb}>
          <VStack w="$full" pl={15} pr={15}>
            {/* Header */}

            {showTitle && (
              <Pressable
                onPress={() => {
                  onTitlePress && typeof onTitlePress === 'function' && onTitlePress();
                }}>
                <HStack
                  justifyContent="center"
                  alignItems="center"
                  space="md"
                  borderBottomColor="rgba(239, 242, 251, 0.2)"
                  borderBottomWidth={1}
                  pt={20}
                  pb={20}
                  mb={14}>
                  {/* 左侧 */}
                  <Box w={'$6'} h={'$6'}>
                    {showLeftIcon && (
                      <Pressable onPress={handleLeftIconPress}>
                        <Icon as={leftIcon} color="$white" w={'$6'} h={'$6'} />
                      </Pressable>
                    )}
                  </Box>
                  {/* 中间内容 */}
                  {titleRender ? (
                    titleRender()
                  ) : (
                    <Text flex={1} textAlign="center" color="$white" fontSize={18} fontWeight="$bold">
                      {title}
                    </Text>
                  )}
                  {/* 右侧 */}
                  <Box w={'$6'} h={'$6'}>
                    {showRightIcon && rightIcon && (
                      <Pressable onPress={handleRightIconPress}>
                        <Icon as={rightIcon} color="$white" w={'$6'} h={'$6'} />
                      </Pressable>
                    )}
                  </Box>
                </HStack>
              </Pressable>
            )}
            {children && children}
          </VStack>
        </ActionsheetContent>
      </GluestackUIProvider>
    </Actionsheet>
  );
}

![image](https://github.com/gluestack/gluestack-ui/assets/90511733/9df35c73-a1b3-4b6b-b969-171afebb0c58)

**Comment by Gluant101** [comment]
Thanks for reporting! We'll look into this.

**Comment by Viraj-10** [comment]
Hey @7chenys, Please upgrade to latest version of `@gluestack-ui/themed, @gluestack-ui/config & @gluestack-style/react`.

**Comment by 7chenys** [comment]
> 嘿@7chenys，请升级到最新版本的`@gluestack-ui/themed, @gluestack-ui/config & @gluestack-style/react`。

已经是最新版啦

**Comment by Viraj-10** [comment]
Hey @7chenys, It's working for me. Can you share a repo where this bug reproduced?
