### ISSUE TITLE
Issue with Select component

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1515]
### Description

I'm trying to use the Select component for mobile, using expo in the iOS....
When I start the select with some existing value Item, it is showing the VALUE instead of the LABEL.... is it a bug or am I messing with the component?

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @Gluant101, Please upgrade to latest version of `@gluestack-ui/themed & @gluestack-style/react`.

**Comment by teckbeng-payboy** [comment]
@Viraj-10  i tested with latest version, issue still exist.

**Comment by Viraj-10** [comment]
Hey @teckbeng-payboy, Please check with latest version. `@gluestack-ui/themed` version `1.0.30` and `@gluestack-ui/config` `1.0.10`.

**Comment by pierrebiver** [comment]
I checked as well and still have the same issue too.

**Comment by Viraj-10** [comment]
Hey @pierrebiver @Gluant101, when you pass the value to `selectedValue` pass `selectedLabel` as well.

**Comment by pierrebiver** [comment]
I did passed both and it still won't work using expo on iOS. On top of that (I can open another ticket maybe) I cannot seems to select a item anymore, when I click on a item, it won't do anything, the list stays open and it was working before I upgraded it to the latest version.
<img width="338" alt="Capture d’écran 2023-12-18 à 10 08 45" src="https://github.com/gluestack/gluestack-ui/assets/13810999/59abb89a-6ab5-43d1-980a-2bbe88dd21bd">

**Comment by Relax594** [comment]
@Viraj-10 I just tried to upgrade our apps from native-base to gluestack-ui. 

Why do we have to set `selectedLabel` everytime we update `selectedValue`?
I do not know the matching label at various positions where I am trying to update the `selectedValue` from.

In native-base it wasn't required to set the `selectedLabel`. It updated automatically when updating `selectedValue`.

Is this behaviour intended to stay after "beta" or it is a temporary solution?

**Comment by cameronmurphy** [comment]
Can this be reopened? I think the `selectedLabel` prop is a really strange API for a `Select` component. We are rendering a list of `SelectItem` components with `label`s and `value`s so why must we tell the component which label to render?

My expectation would be when the value of `selectedValue` changes, the `Select` component will use the `SelectItem` collection to figure out which label to display.

Also the documentation for `selectedValue` is currently incorrect, it's not a boolean.

**Comment by CodySwannGT** [comment]
@Viraj-10 Agreed this is really weird especially since `selectedLabel` is deprecated, but, leaving it out gives you the value as the display

**Comment by petruspierre** [comment]
I'm facing the same problem, and neither initialLabel or selectedLabel seems to work as expected.

**Comment by Viraj-10** [comment]
@petruspierre, Can you please open new issue with minimal reproduction?

**Comment by Bustinout** [comment]
I was able to make my own temporary fix like so if anyone is interested:
`
const getLabelFromValue = (value: string) => {
    return options.find((option) => option.value === value)?.label;
};

<SelectTrigger>
    <Text>
        {getLabelFromValue(value)}
    </Text>
    <SelectIcon className="mr-3" as={ChevronDownIcon} />
</SelectTrigger>
`
