### ISSUE TITLE
InputField lineHeight typo in @gluestack-ui/config

### ISSUE THREAD

**Issue by joelso** [gluestack/gluestack-ui#1531]
### Description

Noticed that InputField text was not aligned when using size `lg`.

### Steps to reproduce

1. Create a gluestack ui project 
2. Create a Input of size `lg`
3. Notice that InputField text is not aligned

I am pretty sure this is just a typo on @gluestack-ui/config. 

Surely lineHeight should be `$lg` and not `$xl`? See here:
https://github.com/gluestack/gluestack-ui/blob/main/packages/config/src/theme/InputField.ts#L44

### gluestack-ui Version

1.0.30

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by Viraj-10** [comment]
Hey @joelso, Thanks for reporting the issue our designers will have look.

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
