### ISSUE TITLE
Issue encountered while using menu component 

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1532]
### Description

ggglll — 16/12/2023 00:52 Hey there! I'm using the Menu component in React Native, and I've encountered an issue. Here's the code I'm using: 

Copy

```
<Menu
  placement="bottom start"
  alignItems='flex-end'
  trigger={({...triggerProps}) => { 
    return (
      <Button
        backgroundColor="rgb(242, 242, 242)"
        size="xs"
        {...triggerProps}>
        <ThemedIcon color="black" as={MenuIcon} />
      </Button>
    );
  }}>
  <MenuItem
    onPress={handlelogout}
    key="Logout"
    textValue="Logout">
    <MenuItemLabel  mr="$2" size="sm">
      Logout
    </MenuItemLabel>
    <Icon name="logout" size={18} color="#000" />
  </MenuItem>

  <MenuItem  onPress={() => { navigation.navigate("PrintingScreen"); setIsMenuOpen(false)}}  key="printer" textValue="printer">
    <MenuItemLabel mr="$2" size="sm">
      Print 
    </MenuItemLabel>
    <Icon name="printer" size={18} color="#000" />
  </MenuItem>
  <MenuItem   key="Settings" textValue="Settings">
    <MenuItemLabel mr="$2" size="sm">
      Settings
    </MenuItemLabel>
    <ThemedIcon as={SettingsIcon} size="sm" mr="$2" />
  </MenuItem>
</Menu>

```
 The problem I'm facing is that when I press on the "Print" MenuItemLabel, I'm navigated to the PrintingScreen, but the Menu remains open. However, when I press on "Settings," the Menu closes as expected. How can I fix this issue? Any help would be greatly appreciated!

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @Gluant101 ggglll, Please refer [this](https://snack.expo.dev/@viraj_10/menu-item-onselection-change). for screen navigation menu.

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
