### ISSUE TITLE
lucide-react-native icons are not rendering

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1534]
### Description

miguel.n1400 — Today at 09:37 Hello! Im using the lucide-react-native library recommend in the glue stack docs for icons. Locally the icons render just fine, but after creating a iOS internal distribution build. When the app launches, none of the components  that are using lucide-react-native icons are rendering anymore.  Any suggestions?

miguel.n1400 — Today at 09:16
I updated my gluestack deps today and now the icons don’t render on local ether. Get the error message ‘md’ is not a valid dimension

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by millerm30** [comment]
I'm thinking that this is tied to the following issue.

LucideIcon size doesn't support the "md", "lg" etc #1516

**Comment by Viraj-10** [comment]
Hey @Gluant101 @millerm30, Please upgrade `@gluestack-style/react` to version `1.0.30`.

**Comment by millerm30** [comment]
Thank you @Viraj-10 will give this a try today.
