### ISSUE TITLE
Error while trying to run storybooks

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1539]
### Description

Patryk Ziemkowski — Today at 15:44 Hello.   I'm forking a gluestack-ui main branch and I'm trying to run storybooks.   I followed the contribution guide (yarn, cd example/storybook yarn storybook) I didn't change any files.  While trying to run storybooks, I get multiple ModuleNotFoundError. For example 

`ModuleNotFoundError: Module not found: Error: Can't resolve '@gluestack-style/animation-resolver'`, which is first but there are many more.  Am I missing some step? Would someone be able help me set this up?

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by makkarMeenu** [comment]
This has been fixed.
