### ISSUE TITLE
Toast not display on second time trigger when using with MutationCache on the root project, Alert of React native work fine

### ISSUE THREAD

**Issue by ducpt-bili** [gluestack/gluestack-ui#1543]
### Description

I am trying to show Toast to handle error on global project with react query, MutationCache onError, but it only work on the first time, the second time it not display at all. Please see the image below.

### Steps to reproduce

<img width="680" alt="Screenshot 2023-12-19 at 14 52 38" src="https://github.com/gluestack/gluestack-ui/assets/101504153/77d4e2dd-5b80-4c9b-bb27-d9b9e24137c7">
<img width="618" alt="Screenshot 2023-12-19 at 14 53 07" src="https://github.com/gluestack/gluestack-ui/assets/101504153/85fa8cbd-1a15-472c-b223-1af5b6212228">

### gluestack-ui Version

1.0.10

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

 "@gluestack-style/react": "1.0.29",
    "@gluestack-ui/config": "^1.0.10",
    "@gluestack-ui/themed": "1.0.30",

**Comment by Gluant101** [comment]
Thanks for reporting. We'll look into this.

**Comment by andrewvasilchuk** [comment]
I'm getting the same problem.

**Comment by k-v-dimitrov** [comment]
@Viraj-10 @Gluant101 
I've implemented a fix for this ^

**Comment by guialcantara** [comment]
I'm getting the same problem.

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
