### ISSUE TITLE
[Tooltip]Tooltip is invalid on ios & android

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1555]
### Description

Tooltip is invalid on mobile, can't be shown

### Steps to reproduce

```
<Tooltip
              trigger={triggerProps => (
                <Text size="xs" color="#888" {...triggerProps}>
                  just now
                </Text>
              )}>
              <TooltipContent>
                <TooltipText>2023-12-21</TooltipText>
              </TooltipContent>
            </Tooltip>
```

### gluestack-ui Version

1.0.30

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by Gluant101** [comment]
Thanks for reporting. We'll look into this.

**Comment by Viraj-10** [comment]
hey @BooYeu, Native devices doesn't have hover state. So you can control tooltip by passing isOpen. Here is [expo snack](https://snack.expo.dev/@viraj_10/tooltip-native-onpress) for the same.

**Comment by BooYeu** [comment]
> hey @BooYeu, Native devices doesn't have hover state. So you can control tooltip by passing isOpen. Here is [expo snack](https://snack.expo.dev/@viraj_10/tooltip-native-onpress) for the same.

I try https://snack.expo.dev/@viraj_10/tooltip-native-onpress, but I still can't open tooltip on ios&android
