### ISSUE TITLE
[Badge] BadgeText can't effect when Badge props change

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1556]
### Description

BadgeText can't effect when Badge props change

### Steps to reproduce

```
const Demo = () => {
  const [isActive, setIsActive] = useState(false)
  return (
    <Pressable onPress={() => setIsActive(prev => !prev)}>
    <Badge action={isActive ? 'info' : 'muted'}>
      <BadgeText>something</BadgeText>
    </Badge>
    </Pressable>
  )
}
```

### gluestack-ui Version

1.0.30

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by Gluant101** [comment]
We'll look into this. Thanks for reporting.

**Comment by Viraj-10** [comment]
Hey @BooYeu, It's working fine in production please find working snack [here](https://snack.expo.dev/@viraj_10/working-badge-example).
Let me if it still doesn't work for you.
