### ISSUE TITLE
The icon doesn't change on gluestack website and my device.

### ISSUE THREAD

**Issue by iuhisa** [gluestack/gluestack-ui#1557]
### Description

On the docs pages: Input type "password with FormControl" doesn't work properly.

### Steps to reproduce

This and [#1377](https://github.com/gluestack/gluestack-ui/issues/1377#issue-1988697455) is almost the same.

1. Open https://gluestack.io/ui/docs/components/forms/input#input-type-password-with-formcontrol .
2. Move to **Input type password with FormControl** and click "**eye**" button.
3. Only change the type of input, but the icon doesn't change.

also it occurs on my device.

### gluestack-ui Version

1.0.30

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by Gluant101** [comment]
Thanks for reporting. We'll look into this.

**Comment by fatidian1** [comment]
FYI: If it has any meaning - it also doesn't work on React Native CLI.

**Comment by Viraj-10** [comment]
Hey @fatidian1 @iuhisa , #1576 this PR will fix this issue.

**Comment by rajat693** [comment]
I hope your problem is resolved now; therefore, I am closing this issue.
