### ISSUE TITLE
Eye off and Eye on icon is not working when I press it

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1562]
### Description

kushal_p. — 24/12/2023 06:57 Hi There,  I am using gluestack for the first time and I am facing some issues. I am working on login page, I am following the example of Input type password with FormControl section given in https://gluestack.io/ui/docs/components/forms/input .  Eye off and Eye on icon is not working when I press it. It stays still. on the official glustack document page it does not work as well. Below is the code for password input field. Please help

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

```
<Input>
  <InputField type={showPassword ? "text" : "password"} />
  <InputSlot pr="$3" onPress={handleState}>
    <InputIcon
      as={!showPassword ? EyeIcon : EyeOffIcon}
      color="$darkBlue500"
    />
  </InputSlot>
</Input>
```

**Comment by GoldMyr1994** [comment]
I had the same problem, for now as workaround to force the render of the correct icon I added a key to the icon

**Comment by Viraj-10** [comment]
Hey @GoldMyr1994 @Gluant101, #1576 this PR will fix this issue.
