### ISSUE TITLE
deprecated error  in react native 0.73,  Input component  only ios

### ISSUE THREAD

**Issue by CodeExpedition** [gluestack/gluestack-ui#1568]
### Description

currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput

### gluestack-ui Version

@gluestack-ui/themed": "^1.0.33"

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

need some action later

**Comment by Viraj-10** [comment]
Hey @CodeExpedition, I am unable to reproduce it can you please share your code?
