### ISSUE TITLE
[Button] ButtonGroup direction "Type 'string' is not assignable to type 'undefined'"

### ISSUE THREAD

**Issue by yokozawa0701** [gluestack/gluestack-ui#1572]
### Description

Type 'string' is not assignable to type 'undefined'.ts(2322)

### Steps to reproduce

When I tried to use ButtonGroup and set direction props to 'column' like below, this type of error happened.

```tsx
<ButtonGroup direction="column">
```

![スクリーンショット 2024-01-02 20 58 40](https://github.com/gluestack/gluestack-ui/assets/8081222/4f3164e2-dea3-492f-8aca-b70e2c9363d5)

### gluestack-ui Version

1.0.33

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Gluant101** [comment]
Thanks for reporting! We'll look into this.

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
