### ISSUE TITLE
It would be great if you add intellisense support for useToken api

### ISSUE THREAD

**Issue by afu-hive** [gluestack/gluestack-ui#1574]
### Description

It would be great if you add **intellisense** support for `useToken` api,
or do you guy have any suggestions for me to make that happen

**thank you**

### Problem Statement

When I create many custom `theme.tokens` that very hard to maintain and developing is slow, So for now I create constants for contain keys from tokens but when I create new of tokens that make me have to create new constants too.

That why I looking for **intellisense**

### Proposed Solution or API

fast development, easy to maintain, readable for all tokens, suggestion tokens

**Comment by ankit-tailor** [comment]
Hey @afu-hive, We have added type intellisense for `useToken` in the latest versions of `@gluestack-style/react`. Please upgrade to latest version. Let me know if we can improve anything after using it or you face any issues ;)
