### ISSUE TITLE
throw 

### ISSUE THREAD

**Issue by moonrailgun** [gluestack/gluestack-ui#1585]
### Description

gluestack-ui is a cross platform, so its should support next server side render and not throw warning

### Steps to reproduce

1. clone https://github.com/gluestack/solito-head-starter-kit
2. run `yarn`
3. run `yarn web`

![image](https://github.com/gluestack/gluestack-ui/assets/6964737/cbacc797-e09f-4b0e-94e2-5f612a1e7803)

### gluestack-ui Version

1.0.31

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @moonrailgun, this warning will be fixed in this #1487 PR.

**Comment by moonrailgun** [comment]
cool

**Comment by moonrailgun** [comment]
yeah, after simple test, this warning has been fixed
