### ISSUE TITLE
Input's text not in center

### ISSUE THREAD

**Issue by suhaotian** [gluestack/gluestack-ui#1587]
### Description

**Input** 's value should center correctly, but currently it's not

### Steps to reproduce

Example code:
```tsx
  <FormControl isInvalid={false} w="100%">
            <FormControlLabel>
              <FormControlLabelText>Subject</FormControlLabelText>
            </FormControlLabel>
            <Input size={'lg'}>
              <InputField />
            </Input>
          </FormControl>
```

Screenshot:

<img width="346" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/6512574/6c143231-ffeb-4324-b668-87d6a8fe7c57">

Note: below input is plain TextInput, is center correctly when typing something.

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by eminx** [comment]
Thank you! @suhaotian this is the case for me too for quite a while - hoping for a change. It's quite annoying, looks very unpleasant indeed...

**Comment by eminx** [comment]
<img width="364" alt="Screenshot 2024-01-10 at 16 04 09" src="https://github.com/gluestack/gluestack-ui/assets/22205310/db762a62-c526-4153-9078-79384ac6013b">

**Comment by suhaotian** [comment]
@eminx 

Temporary solution is add `lineHeight='$md'` to `<InputField />`, like `<InputField lineHeight="$md" />`

**Comment by eminx** [comment]
@suhaotian that doesn't really work for me. I have succeeded though with:

`<InputField mb="$1" />`

**Comment by suhaotian** [comment]
@eminx ehhh.. that's interesting, did you add custom style in the parent component?

Mine's like this:

```ts
  <Input size={'lg'}>
       <InputField lineHeight="$md" placeholder="" />
 </Input>
```

**Comment by Viraj-10** [comment]
Hey @suhaotian, This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
