### ISSUE TITLE
Babel Plugin not working on Expo

### ISSUE THREAD

**Issue by GManzato** [gluestack/gluestack-ui#1589]
### Description

The babel plugin doesn't seem to work , even on a new created app with create gluestack

### CodeSandbox/Snack link

https://github.com/GManzato/Gluestack-Babel-Repro

### Steps to reproduce

1. `npm create gluestack`
2. Follow https://gluestack.io/ui/docs/production-optimizations/babel-plugin , step 1 to 4
3. See error :
```iOS Bundling failed 15ms
error: App.tsx: ****/myTestApp/App.tsx: You cannot use tokens without wrapping the component with StyledProvider. Please wrap the component with a StyledProvider and pass theme config.

```

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by ankit-tailor** [comment]
Hey @GManzato, Can you share your `babel.config.js`?

**Comment by ankit-tailor** [comment]
Hi @GManzato, I'll have a look into your project.

**Comment by GManzato** [comment]
@ankit-tailor any update on this ? 
By the way thanks for all the work on this project, it's fantastic.

**Comment by ankit-tailor** [comment]
Hey @GManzato, I have created a [PR](https://github.com/GManzato/Gluestack-Babel-Repro/pull/1) which adds babel plugin support.

Actually the thing is that you need to export the default gluestack config from `gluestack-ui.config.ts` so that babel plugin can pick it from your project and bundle it for further use. We'll update the docs with the same. Thanks for reporting it.

Closing the issue for now. Feel free to re-open it in case you face any other issue.

**Comment by GManzato** [comment]
Hey @ankit-tailor , Thanks for the help but I have another issue, 
When I eject the theme , it seems that the babel plugin doesn't load correctly the theme, I've updated the repo 
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-16 at 10 08 58](https://github.com/gluestack/gluestack-ui/assets/1064904/b34c43e2-1326-45a4-a471-e8e6a05d55e7)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-16 at 10 08 46](https://github.com/gluestack/gluestack-ui/assets/1064904/02b48eef-0052-4d89-a323-ad1cb839164a)

**Comment by tadeumelembe** [comment]
> Hey @ankit-tailor , Thanks for the help but I have another issue, When I eject the theme , it seems that the babel plugin doesn't load correctly the theme
> 
> First image is by loading the default config , the second is when the theme is ejected.
> 
> I've updated my repo with the code. ( Seems also that I cannot reopen the issue )
> 
> ![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-16 at 10 08 58](https://private-user-images.githubusercontent.com/1064904/296914223-b34c43e2-1326-45a4-a471-e8e6a05d55e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODEzMTIsIm5iZiI6MTczMDQ4MTAxMiwicGF0aCI6Ii8xMDY0OTA0LzI5NjkxNDIyMy1iMzRjNDNlMi0xMzI2LTQ1YTQtYTQ3MS1lOGU2YTA1ZDU1ZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMTcxMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNhZTYzNThiZGEwOGExNmY2MjA3M2I4Yzg1NzA0MmRjMjRiOTkyZDRiZjAzMTYyOTJlZDQyMTE0MDE5YTY2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vqvrLKBJCdhgWzI_94yMdwmQrSF7OMgoiWw99Muq6wQ) ![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-16 at 10 08 46](https://private-user-images.githubusercontent.com/1064904/296914266-02b48eef-0052-4d89-a323-ad1cb839164a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODEzMTIsIm5iZiI6MTczMDQ4MTAxMiwicGF0aCI6Ii8xMDY0OTA0LzI5NjkxNDI2Ni0wMmI0OGVlZi0wMDUyLTRkODktYTMyMy1hZDFjYjgzOTE2NGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMTcxMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDkzYjQ2NjdlNzJiN2MwZDI0Nzc4OTI0ZWEyMzQyMjdhZmE5NTI2NjlkMThiNWYwNjk0MmJhZThiMWZiNDA4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dvOBZKJg4pjgXJRP5Q-4Z6KpGmLws006eckEs6LQqF0)

Any luck?
