### ISSUE TITLE
Input shrinks when used inside HStack

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1601]
### Description

Input shrinks when used inside HStack

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Reported by @sanketsahu & @surajahmed 

![image (22)](https://github.com/gluestack/gluestack-ui/assets/152247394/7e8def31-f09b-4cc5-b1fa-9d367ccf02f6)
![image (23)](https://github.com/gluestack/gluestack-ui/assets/152247394/0255548a-a40b-4578-90d6-9e929867fdfc)

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
