### ISSUE TITLE
Bugs caught during extensive testing

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1605]
### Description

This is a list of bugs

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

> The image's border-radius property and the space property in VStack and HStack are causing a type error 

> For the checkbox `isFocusVisible` prop is giving this error.
![image (25)](https://github.com/gluestack/gluestack-ui/assets/152247394/8865ddaf-e6a7-4da8-a148-f0282014ea53)

> `isEnabled` prop of switch is showing this error.
![image (26)](https://github.com/gluestack/gluestack-ui/assets/152247394/35261c1f-243b-4473-b2b3-e2b669ad042c)

> `strokewidth` for icon is also giving type error
![image (27)](https://github.com/gluestack/gluestack-ui/assets/152247394/50f745e5-53f2-4d48-aace-de0313c932d5)

> `isFocusVisible` prop for radio type error.
![image (28)](https://github.com/gluestack/gluestack-ui/assets/152247394/3a70b642-03e4-40f0-b13e-68bb4dfa4ca8)

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
