### ISSUE TITLE
Facing issue after upgrading project to expo 49

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1615]
### Description

Error: While trying to resolve module clsx from file 

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Issue: https://discord.com/channels/1050761204852858900/1192419797225443338

**Comment by neverson-silva** [comment]
having same issue some update on this? any components more complex that needs some kind of anymation this error occurs.

**Comment by n1thun** [comment]
Posting the original issue from discord over here for ease of access.
I too have the same issue, the web build fails to render after adding gluestack-ui. I am able to run the ios simulator though.

![image](https://github.com/gluestack/gluestack-ui/assets/2892349/71b2aba9-f1b5-446a-84f8-8edb652991d1)

**Comment by rajat693** [comment]
Hi there!
To help us better understand and resolve your issue, could you please provide a minimal codebase that reproduces the problem? This will greatly assist us in diagnosing and fixing the issue more efficiently.
Thank you so much for your cooperation!

**Comment by sra1kumar-NULL** [comment]
Hey there, we are closing this issue for now, please feel free to reopen the issue if you are still facing it/ having any queries about it.
