### ISSUE TITLE
Gluestack Text component clips top of text for fontsize > 24

### ISSUE THREAD

**Issue by rampantslug** [gluestack/gluestack-ui#1618]
### Description

Create a page with a <Text> component and set fontsize={24}. Notice that top of text is getting clipped. Increase size further and more text will be clipped 

### Steps to reproduce

See description for steps

### gluestack-ui Version

gluestack themed 1.0.34

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by madelineleclair** [comment]
Also experiencing this when doing font size of "$2xl" for text. This makes it almost impossible to do responsive design for larger screens like ipads.



![Image](https://github.com/gluestack/gluestack-ui/assets/24612594/4a6a668f-5ce2-40e2-95b9-34facc8c4451)

**Comment by Viraj-10** [comment]
Hey @rampantslug @rampantslug, This issue has been fixed in latest version. 
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`
