### ISSUE TITLE
Menu item behaving differently

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1626]
### Description

Link: https://discord.com/channels/1050761204852858900/1054373041435574322/1194861169119342755

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

I'm having a weird problem that I'd love some help with; I have a standard Menu with a Trigger and MenuItems. the menu items open a modal when selected.

In storybook, this behaves as expected: selecting a menu item closes the menu and opens the modal. however, when running in the browser (using expo), the menu stays open and the modal is opened.

Any idea what might be the cause in the difference in these two experiences?

**Comment by thatrandybrown** [comment]
Just to add to this, the behavior seems to be aligned with whether or not the menu has a selectionMode provided or moves to a controlled state. In those cases, the menu no longer closes.

**Comment by thatrandybrown** [comment]
#1631 describes this issue (and another) more fully.

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
