### ISSUE TITLE
Issue with Menu component

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1627]
### Description

Link: https://discord.com/channels/1050761204852858900/1054373041435574322/1194830768531316888

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

i am using https://gluestack.io/ui/docs/components/overlay/menu and i hace this problem:
react-dom.development.js:16305 Uncaught TypeError: Illegal constructor
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)

in this component: 
return (
    <Menu
      bg="$backgroundSecondary"
      trigger={({ ...triggerProps }) => {
        return (
          <Pressable {...triggerProps}>
            <MemoizedAvatarCard picture={avatar} sizeAvatar="sm" name={name} />
          </Pressable>
        );
      }}
    >
      <MenuItem key="user">
        <MenuItemLabel color="$text" size="sm">
          {name}
        </MenuItemLabel>
      </MenuItem>
      <MenuItem key="company" onPress={() => console.log('sadasdas')}>
        {/* <Icon as={Lock} size="sm" /> */}
        <MenuIcon as={Lock} size="sm" />
        <MenuItemLabel color="$text" size="sm">
          {translate('status')}
        </MenuItemLabel>
      </MenuItem>
    </Menu>
  );

my version in package is:
"react-native-web": "~0.18.10",
"react-native-webview": "13.2.2",
"react-native": "0.72.6",

and chatGpt say this:
Ensure Compatibility: Verify that all components and libraries you're using are compatible with react-native-web. This includes Menu, MenuItem, MenuItemLabel, and MenuIcon.

why? i need update my package?

**Comment by DennisHesler** [comment]
My Platform Is Expo,
My issue was that I wasn't passing the 'key' or 'textvalue' prop to the MenuItem. When I included these props, the error was resolved. However, I'm still facing an issue where the MenuItem's onPress function doesn't work. When clicked, it just closes without triggering the onPress event.
My code where a onPress not found it is:
`    <Menu
      bg="$background"
      placement="bottom left"
      trigger={({ ...triggerProps }) => {
        return (
          <Pressable {...triggerProps}>
            <MemoizedAvatarCard picture={avatar} width="$9" name={name} />
          </Pressable>
        );
      }}
    >
      <MenuItem key="user" textValue="user" onPress={() => console.log('sadasdas')}>
        <ItemUser />
      </MenuItem>
      {!verifyIsNotNativeDevice() && (
        <MenuItem key="company" textValue="company" onPress={() => console.log('sadasdas')}>
          <View style={{ paddingHorizontal: 12, paddingVertical: 0 }}>
            <ContainerCompany
              direction="column"
              pos_name={salesPoint?.Title}
              team_name={team?.name}
              product_name={product?.NombreComercial}
            />
          </View>
        </MenuItem>
      )}
      <MenuItem
        key="GoToPms"
        textValue="GoToPms"
        onPress={() => Linking.openURL('https://pms.pxsol.com')}
      >
        <Icon as={IconArrowLeft} size="md" />
        <MenuItemLabel ml="$4" size="md">
          {translate('gotToPms')}
        </MenuItemLabel>
      </MenuItem>
      <MenuItem key="logout" textValue="logout" onPress={onPressLogout}>
        <Icon as={Logout} size="md" />
        <MenuItemLabel ml="$4" size="md">
          {translate('logout')}
        </MenuItemLabel>
      </MenuItem>
    </Menu>`
  this is a screen recording: 
[Screen](https://bkxrnu8zez.vmaker.com/record/GCDTaBViksDouVXW)

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
