### ISSUE TITLE
Menu seems not to behave as expected

### ISSUE THREAD

**Issue by thatrandybrown** [gluestack/gluestack-ui#1631]
### Description

Menu does not close when controlled, and MenuItems do not seem to fire onPress events despite being pressables

### Steps to reproduce

# Sample Source Code for onPress of a Pressable:

```ts
    <Menu
    trigger={({ ...triggerProps }) => {
      return (
        <Button
          {...triggerProps}
        >
          <ButtonText>Actions</ButtonText>
        </Button>
      );
    }}
  >
    {[{label: "first option", value: "first"}, {label: "second option", value: "second"}].map(({ label, value }) => (
      <MenuItem key={value} textValue={value} onPress={() => console.log(value)}>
        <MenuItemLabel>{label}</MenuItemLabel>
      </MenuItem>
    ))}
  </Menu>
```

Expected behavior: `value` is logged to the console.
Observed behavior: `value` is never logged.

Additional details:

On inspection in the console, only pointerenter and pointerleave events are tracked; the press is never added, even though the Item is correctly documented as a button on web.

# Sample Source Code for Not Closing on Selection
```ts
const MenuWrapper = () => {
  const [selected, setSelected] = useState<Set<Key>>(new Set<Key>());

  console.log("selected", selected);
  return (
    <Menu
    selectionMode="single"
    selectedKeys={selected}
    onSelectionChange={(selections) => {
      console.log("selections", selections);
      setSelected(selections as Set<Key>);
    }}
    trigger={({ ...triggerProps }) => {
      return (
        <Button
          {...triggerProps}
        >
          <ButtonText>Actions</ButtonText>
        </Button>
      );
    }}
  >
    {[{label: "first option", value: "first"}, {label: "second option", value: "second"}].map(({ label, value }) => (
      <MenuItem key={value} textValue={value}>
        <MenuItemLabel>{label}</MenuItemLabel>
      </MenuItem>
    ))}
  </Menu>
```

Expected behavior: `Menu` closes on selection
Observed behavior: `Menu` stays open on selection

Additional Notes: Both console logs demonstrate the correct updates to the selections and selected keys, and the firing of `onSelectionChange` seems to indicate that a selection has indeed happened.

The docs note that `closeOnSelect` is set to true by default.

### gluestack-ui Version

1.0.35

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by thatrandybrown** [comment]
Of note, menu also fails to close when `selectionMode` is set to `single` and the Menu stays uncontrolled.

**Comment by Viraj-10** [comment]
Hey @thatrandybrown, Thanks for reporting this issue. we will have a look.

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
