### ISSUE TITLE
Select action sheet content open animation 

### ISSUE THREAD

**Issue by AstaninIvan** [gluestack/gluestack-ui#1642]
### Description

The opening animation on Android works very strangely. Sometimes it opens with a jump, and sometimes it opens correctly

### Steps to reproduce

   example of the code I use
   ```
 <Select >
        <Select.Trigger w="100%">
          <Select.Input />
          <Icon as={ChevronDownIcon} />
        </Select.Trigger>
        <Select.Portal useRNModal >
          <Select.Backdrop />
          <Select.Content>
            <Select.DragIndicatorWrapper>
              <Select.DragIndicator />
            </Select.DragIndicatorWrapper>
            <Select.ScrollView>
                <Select.Item key={'1'} label={'1'} value={'1'}/>
                <Select.Item key={'1'} label={'2'} value={'2'}/>
                <Select.Item key={'1'} label={'3'} value={'3'}/>
                <Select.Item key={'1'} label={'4'} value={'4'}/>
            </Select.ScrollView>
          </Select.Content>
        </Select.Portal>
      </Select>
```

### gluestack-ui Version

  "@gluestack-style/react": "1.0.33",     "@gluestack-ui/config": "1.0.11",     "@gluestack-ui/themed": "1.0.35",

### Platform

- [x] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [x] Android
- [x] iOS

### Additional Information
[Запись экрана от 15.01.2024 16:45:50.webm](https://github.com/gluestack/gluestack-ui/assets/31966999/edf9cb3c-6d7a-41a5-905e-11d98ac6dfa3)

**Comment by RishabhSahu24** [comment]
@AstaninIvan 
Could you please provide the code for us? This would aid in gaining a better understanding of your issue, enabling us to reproduce it more effectively. Additionally, kindly specify the device name and operating system version you used for testing.

**Comment by srknymc** [comment]
i have same issue, any solution ?
