### ISSUE TITLE
Text got cut off when size deemed too big

### ISSUE THREAD

**Issue by arielclement** [gluestack/gluestack-ui#1653]
### Description

Text component dimension not properly adjusted when `fontSize` property was raised

### Steps to reproduce

`<Text fontSize="$4xl">This text got cut off</Text>`

<img width="327" alt="Screenshot 2024-01-16 at 19 45 56" src="https://github.com/gluestack/gluestack-ui/assets/97739122/b58175e1-53eb-46a7-913a-63364b80891c">

### gluestack-ui Version

1.0.33

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.
