### ISSUE TITLE
Twitter: (SelectItem)  pressing the element didn't not work.

### ISSUE THREAD

**Issue by Viraj-10** [gluestack/gluestack-ui#1665]
### Description

https://x.com/dennis__Arg/status/1747710297287106574?s=20

### gluestack-ui Version

latest

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by rajat693** [comment]
I have tested the Select component, and it is working fine for me.
Sharing the git repo for reference. [https://github.com/rajat693/gluestack-components](url)

**Comment by Dennish02** [comment]
It's helpful, but I need to run a function that changes the value in the Select. That's why I chose the option to use onValueChange in the Select
` <Select onValueChange={handleChangeTeam}>
        <SelectTrigger variant="outline" size="md">
          <SelectInput defaultValue={selectedTeam} placeholder={selectedTeam} />
          <MaterialCommunity icon={ChevronDownIcon} />
        </SelectTrigger>
        <SelectPortal>
          <SelectBackdrop />
          <SelectContent>
            <SelectDragIndicatorWrapper>
              <SelectDragIndicator />
            </SelectDragIndicatorWrapper>
            {teamsName?.map((team) => (
              <SelectItem
                label={team.team_name}
                value={team.team_name}
                key={team.id_team}
              />
            ))}
          </SelectContent>
        </SelectPortal>
      </Select>`

its work for me..

**Comment by rajat693** [comment]
I hope your problem is resolved now. Therefore, I am closing this issue.
