### ISSUE TITLE
GluestackUIProvider without config leads to SyntaxError

### ISSUE THREAD

**Issue by hristo87** [gluestack/gluestack-ui#1667]
### Description

If you use GluestackUIProvider without config provided leads to "SyntaxError: JSON Parse error: Unexpected character: u", the problem is only if there is no config provided.

### Steps to reproduce

1. Create a RN project with gluestack-ui. 
2. Wrap your app in GluestackUIProvider without config provided
3. SyntaxError: : JSON Parse error: Unexpected character: u

### gluestack-ui Version

gluestack-ui/themed: 1.0.37

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![SCR-20240118-iulo](https://github.com/gluestack/gluestack-ui/assets/102364045/fdeca891-39f6-4829-9194-a278c4752128)
![SCR-20240118-iuqo](https://github.com/gluestack/gluestack-ui/assets/102364045/9ee58ce9-3ca7-4f6b-b8e3-196a246f02ae)

**Comment by TomSwift** [comment]
This is an issue for us as well.   We may provide an undefined config in our app; we're using that as a signal to fall back to old-styling (no gluestack components).

**Comment by ankit-tailor** [comment]
Hey @TomSwift, The issue is fixed. Will release a new version today. That will fix the issue.
