### ISSUE TITLE
onKeyPress in <InputField /> triggers additional "Backspace" event after each key press (except for backspace itself)

### ISSUE THREAD

**Issue by chkee** [gluestack/gluestack-ui#1672]
### Description

onKeyPress in <InputField /> should be triggered according to what you actually press, and backspace key shouldn't be triggered unless pressed

### Steps to reproduce:
Have following implementation:
```
<Input>
    <InputField
        onKeyPress={({nativeEvent}) => {
            console.log(`InputField-onKeyPress: ${nativeEvent.key}`, { nativeEvent });
        }}/>
</Input>
```

#### Case 1: Non backspace keys
1. Type in "12ab" alphabets/number.
2. Observe the log, there would be 8 logs (instead of 4), each keys were followed by a Backspace that you **didn't** pressed.
<img width="403" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/22137869/d1c1e8a5-ea83-4ce3-b7b8-906db432d1f9">

#### Case 2: Backspace key
1. Now try press "Backspace" once.
2. Observe the log, there's only one log from the backspace. Which is the expected behavior.
<img width="345" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/22137869/50695e27-8197-429b-9081-0aca85cfba57">

### gluestack-ui Version

1.0.36

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

Note: This has happened to me on iOS, I haven't tested on Android yet.

**Comment by rajat693** [comment]
hi @chkee, I tried to reproduce the issue that you reported but it's working fine for me. I am sharing below the reference of my git repo https://github.com/rajat693/rn-inputBox

**Comment by rajat693** [comment]
I am closing this issue for now. If you need further assistance or if the problem persists, please don’t hesitate to reopen it.
Thank you!
