### ISSUE TITLE
Popover throws errors and warnings on web

### ISSUE THREAD

**Issue by sem4phor** [gluestack/gluestack-ui#1712]
### Description

Popover throws an error that back handler is not supported on web. Everyti´hings´works fine though...

### CodeSandbox/Snack link

https://gluestack.io/ui/docs/components/overlay/popover

### Steps to reproduce

1. Go to ['Popover docs' ](https://gluestack.io/ui/docs/components/overlay/popover)
2. Open. the console
3. Click on the example to open the popover

### gluestack-ui Version

1.0.35

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by surajahmed** [comment]
@sem4phor Thanks for reporting this. We're working on it.

**Comment by RishabhSahu24** [comment]
Hey @sem4phor , this issue will be fixed in this [#1745](https://github.com/gluestack/gluestack-ui/pull/1745) PR.
