### ISSUE TITLE
Problem with floating elements: (modal, tooltip, Alert): BackHandler is not supported on web and should not be used

### ISSUE THREAD

**Issue by DennisHesler** [gluestack/gluestack-ui#1727]
### Description

BackHandler is not supported on web and should not be used.      at Overlay (http://localhost:19006/static/js/bundle.js:136029:5)     at http://localhost:19006/static/js/vendors-node_modules_expo-asset_build_AssetHooks_js-node_modules_gluestack-ui_themed_build_co-e0d746.chunk.js:253:3     at div     at http://localhost:19006/static/js/bundle.js:82130:25     at StyledComponent (http://localhost:19006/static/js/bundle.js:120248:22)     at MoreOptions (http://localhost:19006/src_components_sidebar_sidebarFilters_SidebarFilters_tsx-src_components_tabs_CustomTabBar_tsx-2b5491.7e4f64e200151b188fb3.hot-update.js:69:29)     at div     at http://localhost:19006/static/js/bundle.js:82130:25     at StyledComponent (http://localhost:19006/static/js/bundle.js:120248:22)     at div     at http://localhost:19006/static/js/bundle.js:82130:25     at StyledComponent (http://localhost:19006/static/js/bundle.js:120248:22)     at div     at http://localhost:19006/static/js/bundle.js:82130:25     at Pressable (http://localhost:19006/static/js/bundle.js:77790:24)     at StyledComponent (http://localhost:19006/static/js/bundle.js:120248:22)     at http://localhost:19006/static/js/bundle.js:136115:7     at ConversationCard (http://localhost:19006/src_components_sidebar_sidebarFilters_SidebarFilters_tsx-src_components_tabs_CustomTabBar_tsx-2b5491.7e4f64e200151b188fb3.hot-update.js:411:29)     at ErrorBoundary (http://localhost:19006/static/js/src_routers_RouteNavigations_tsx.chunk.js:209:86)     at div     at http://localhost:19006/static/js/bundle.js:82130:25     at VirtualizedListCellContextProvider ..

### Steps to reproduce

2. Click on 'OPEN `MODAL`, HOVER A `TOOLTIP`, OPEN A `DIALOG`, OPEN `ALERT`' 
3. Scroll down to '...' 
4. See error `IN CONSOLE`

### gluestack-ui Version

1.1.0

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by DennisHesler** [comment]
## it is adiditional Info in other issue:

If i am using modal of react-native not have this problem..
Screen Recorder https://drive.google.com/file/d/1BvZbHUQIRFYWpBtmpWeWqBsSB8-Wuzej/view?usp=sharing

**Comment by RishabhSahu24** [comment]
Hey @DennisHesler, this issue will be fixed in this [#1745](https://github.com/gluestack/gluestack-ui/pull/1745) PR.
