### ISSUE TITLE
When using nested components in theme, dark values are active when in light mode

### ISSUE THREAD

**Issue by milesingrams** [gluestack/gluestack-ui#1746]
### Description

When using nested components in theme, dark values are active when in light mode

### CodeSandbox/Snack link

https://snack.expo.dev/@milesingrams/gluestack-issue-with-dark-styles

### Steps to reproduce

 Only in ("@gluestack-style/react": "1.0.32") and after. Still happens in latest release ("@gluestack-style/react": "1.0.45")

https://snack.expo.dev/@milesingrams/gluestack-issue-with-dark-styles

Toggle the colorMode and notice the Icon always has the _dark theme set (red color)

### gluestack-ui Version

"@gluestack-style/react": "1.0.32" and later

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by rajat693** [comment]
hi @milesingrams please follow the method given in the docs for `customizing theme` rather than following the above approach. Sharing the link below
https://gluestack.io/ui/docs/theme-configuration/customizing-theme

**Comment by milesingrams** [comment]
We already use a custom theme in our app and it still happens. Also happens when using `.dark` or `_dark`. Looks like theres a bug in the resolution of nested colorMode themes during the `sx` processing step. 

Likely files to look at are:

https://github.com/gluestack/gluestack-ui/blob/main/packages/styled/react/src/convertSxToSxVerbosed.ts

https://github.com/gluestack/gluestack-ui/blob/main/packages/styled/react/src/resolver/checkAndPush.ts

**Comment by milesingrams** [comment]
In this method:
https://github.com/gluestack/gluestack-ui/blob/c15698c5740015127c28e0908f322e81dfed8728/packages/styled/react/src/resolver/checkAndPush.ts#L18C70-L19C1

Youll see that which colorMode is stored in path as 'theme' now after the change of theme handling, this method looks for 'colorMode' in the path to handle the logic for setNestedObjectValue.

**Comment by rajat693** [comment]
You have passed the color property in the props, you dont need to pass it inside the `props` key, you can directly pass it and it will work.
Check this expo [snack](https://snack.expo.dev/@rajat693/gluestack-issue-with-dark-styles---fixed), I changed the code to work accordingly. I only removed the props key and the rest is the same.

If you have any other issue or if it is breaking somewhere else or need more clarification then please open this issue again.
I am closing it for now.
