### ISSUE TITLE
Android Build fails while using gluestack-ui with EXPO 50

### ISSUE THREAD

**Issue by st-anonymous** [gluestack/gluestack-ui#1747]
### Description

EAS Build for android preview fails due to @gluestack-ui/linear-gradient uses a previous version of expo-linear-gradient

### Steps to reproduce

I am using gluestack-ui with Expo 50.
EAS Build for android preview fails due to @gluestack-ui/linear-gradient uses a previous version of expo-linear-gradient.
It gives an error as 
```
Execution failed for task ':expo-linear-gradient:compileReleaseKotlin'. 
> 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
```
The same error happens if I try to build an apk using expo prebuild.

### gluestack-ui Version

1.1.0

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by mjcarnaje** [comment]
+1

**Comment by pupattan** [comment]
+1

**Comment by st-anonymous** [comment]
I have raised a PR for the bug above. 
https://github.com/gluestack/gluestack-ui/pull/1748
