### ISSUE TITLE
Getting component props in typescript

### ISSUE THREAD

**Issue by haruki-m** [gluestack/gluestack-ui#1750]
### Description

I'm trying to forward a prop to a gluestack component, but it gives me, for example, "Property 'as' does not exist on type 'IIconProps & (StyledComponentProps<false | ViewStyle...'." A workaround would be much appreciated!

### Steps to reproduce

`tsconfig.json`:
```
{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compilerOptions": {
    "noUnusedLocals": true
  },
}
```

`SampleComponent.tsx`:
```
import type { FC, ComponentProps } from 'react'
import { Icon } from '@gluestack-ui/themed'

type IconProps = ComponentProps<typeof Icon>

type Props = {
  as: IconProps['as']
}

const SampleComponent: FC<Props> = props => {
  return <Icon as={props.as} /> // simplified
}
```

Error: `Property 'as' does not exist on type 'IIconProps & (StyledComponentProps<false | ViewStyle | ImageStyle | TextStyle | RegisteredStyle<ViewStyle> | ... 6 more ... | undefined, unknown, StyledComponentProps<...>, string> | { ...; })'.`

### gluestack-ui Version

1.1.3

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by surajahmed** [comment]
@haruki-m Thanks for reporting this. We'll look into this.

**Comment by surajahmed** [comment]
Closing this issue since it has been resolved in the latest version. If the problem continues, please feel free to reopen it.
