### ISSUE TITLE
Popover on Android is not placed as expected

### ISSUE THREAD

**Issue by sem4phor** [gluestack/gluestack-ui#1751]
### Description

On Web & iOS the Content of the Popover is positioned near the trigger. On Android it is positioned in the middle of the screen. If it is intended to be like this it would be great to have it dcumented :)

### Steps to reproduce

1. Build any app with gluestack
2. Copy the popover example
3. Open on android and see that the popover is in the middle
4. open on ios and see the popover is next to the trigger element

### gluestack-ui Version

1.1.3

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

Workaround is to style the popover with flexbox but offset and placement are not working :(

**Comment by RishabhSahu24** [comment]
@sem4phor 
Could you please provide the code for us? This would aid in gaining a better understanding of your issue, enabling us to reproduce it more effectively.

**Comment by sem4phor** [comment]
Sue i added a repository for reproduction here: https://github.com/sem4phor/gluestack-ui-1751

Just open android and play around with the PopoverDemo's offset and placement props :)

**Comment by DaminiPandey** [comment]
Hey @sem4phor, 
Tried experimenting with the gluestack-ui Popover component [here](https://snack.expo.dev/@da_minnie/popover_example).
And it works fine on Android.

**Comment by sem4phor** [comment]
@DaminiPandey Okay yes in a sandbox it seems to work thank you! Not sure why it is not working for us 🤷  I will close this issue then.
