### ISSUE TITLE
Don't force select item value to be a string

### ISSUE THREAD

**Issue by erdemkeren** [gluestack/gluestack-ui#1753]
### Description

number accepted as a select item value

### Steps to reproduce

```ts
type item = {
    id: number
}

<SelectItem
    key={item.id}
    label={item.name}
    value={item.id}
/>
```

Should be valid. Helps when using with zod validation + hook forms as suggested by the pro package.

### gluestack-ui Version

1.1.3

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by artfb** [comment]
Bump. 
Could `SelectItem` accept ReactNode as option label? So I can use more complex options utilizing eg. HStack/VStack

**Comment by sra1kumar-NULL** [comment]
Hey @artfb , Currently this is not supported for the Select API , this will be a separate component combobox.
