### ISSUE TITLE
StatusBar backgroundColor not working (android-only)

### ISSUE THREAD

**Issue by Benoit-Kuzak** [gluestack/gluestack-ui#1756]
### Description

backgroundColor is a prop existing on react-native's StatusBar however it doesn't function when using Gluestack's. I can use react-native's for now but Ideally I would like to use my primary color code ($primary500) but the prop doesn't even work at all and I have to use the hex code on react-native's component. 

### Steps to reproduce

Add StatusBar anywhere on a screen. Set the backgroundColor to any color (hex or token) and expect the color to be applied on android.
It does not. T

### gluestack-ui Version

1.1.3

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by RishabhSahu24** [comment]
@Benoit-Kuzak 
Thank you for reporting the issue. We have addressed it and a pull request (PR) has been submitted.
