### ISSUE TITLE
Menu placement flickers on opening in latest version

### ISSUE THREAD

**Issue by DavidAmyot** [gluestack/gluestack-ui#1758]
### Description

I expect the menu placement to appear where it's supposed to at once instead of appearing at the top-left and then moving to where it's asked to be.

### CodeSandbox/Snack link

https://snack.expo.dev/@davidamyot/menu-placement-flicker?platform=android

### Steps to reproduce

1. Select the android platform
2. Press "tap to play"
3. Click the menu button

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

#1463 Temporarily fixed the issue for `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` and `@gluestack-style/react@1.0.41`, but the following versions regressed the fix including the latest version of gluestack.

When opening a menu, the menu items appear somewhere else on the screen rapidly before being placed properly instead of just appearing where the placement prop specifies to.

The snack included shows the behaviour.

@Viraj-10 Tagging you here since you were the one that fixed #1463.

Thanks for the help 🙏

**Comment by Viraj-10** [comment]
Hey @DavidAmyot, Thanks for reporting this issue. We will have a look.

**Comment by rajat693** [comment]
hi @DavidAmyot I am sharing below the expo snack with you, please update to the latest version and your problem will be resolved https://snack.expo.dev/@rajat693/menu-placement-flicker?platform=android

**Comment by Viraj-10** [comment]
Hey @DavidAmyot, This issue has been fixed in latest version of `@gluestack-ui/themed`
