### ISSUE TITLE
Animation not working for Modal and ActionSheet

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1759]
### Description

Link: https://discord.com/channels/1050761204852858900/1177660850014793830

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 
Juarez Leite — 24/11/2023 22:53
Hey guys, im trying to use Modal component but the Animation isn't working. Returns some errors, going to test other components that uses Animation also

Gilles — 08/12/2023 12:10
Hey @Shayan I'm facing the same issue with the modal
styledContext.setAnimationDriverData is not a function (it is undefined)
 
Seems like the modal is not correctly wrapped in the context provider, as the styledContext doesn't contain setAnimationDriverData
I'm not really familiar with the code under the hood

Juarez Leite — 24/01/2024 18:32
Yeah, im still having this issue and now with ActionSheet
Juarez Leite — 24/01/2024 19:51
Im trying to use my gluestack components on a storybook environment 
My provider is setted accordingly and etc
Juarez Leite — 24/01/2024 19:59
Other components work fine, but when I use now Actionsheet it shows the same msg
this one
![image](https://github.com/gluestack/gluestack-ui/assets/152247394/ec06800e-c701-44a3-b9b9-0a67ec553e56)

### gluestack-ui Version

 3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by ankit-tailor** [comment]
Please update `@gluestack-style/react` and `@gluestack-ui/themed` to latest version.
