### ISSUE TITLE
Documentation 404 errors

### ISSUE THREAD

**Issue by sovetski** [gluestack/gluestack-ui#1762]
### Description

We should not get 404 error

### Steps to reproduce

1. Go to https://gluestack.io/ui/docs/getting-started/incremental-adoption
2. Click on Follow [these](https://gluestack.io/ui/docs/getting-started/ui/docs/guides/install-expo) steps if you are using Expo **--- or click on ---** Follow [these](https://gluestack.io/ui/docs/getting-started/ui/docs/install-rn) steps if you are using React Native Bare App.
4. See error 404

https://gluestack.io/ui/docs/getting-started/ui/docs/guides/install-expo
https://gluestack.io/ui/docs/getting-started/ui/docs/install-rn

### gluestack-ui Version

1.1.3

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Other Platform

Docs

**Comment by RishabhSahu24** [comment]
Thank you for reporting this. We have updated our documentation and resolved the issue.
