### ISSUE TITLE
Please guide us how to add fonts to RN CLI in the documentation!

### ISSUE THREAD

**Issue by hristo87** [gluestack/gluestack-ui#1773]
### Description

Firstly, thank you for your hard work; it's truly appreciated. I would like to request adding a guide on how to add fonts to a React Native CLI project. While your documentation describes how to do it for Expo, it seems that method doesn't work as effectively. However, there's no information provided on how to do it for React Native CLI projects, which I believe is still the preferred choice for the majority of users. Could you please address this gap in the documentation?

### Problem Statement

I believe the description is self-explanatory enough.

### Proposed Solution or API

Just add a easy to follow guide.

**Comment by hristo87** [comment]
Thank you for your assistance with adding fonts to React Native. I initially encountered difficulties, but now it's working as expected. I apologize if I raised any unnecessary concerns. Your help is greatly appreciated.

**Comment by felipeemoreno** [comment]
> Thank you for your assistance with adding fonts to React Native. I initially encountered difficulties, but now it's working as expected. I apologize if I raised any unnecessary concerns. Your help is greatly appreciated.

Hello.
How did you solve this problem? I can use normal fonts with react-native styles, but gluestack doesn't work.

**Comment by hristo87** [comment]
Good day,

I haven’t done anything special, aside of adding the font that I need to the gluestack-ui.config.ts file like so:

***@***.***

And then when I need to use it, I am selecting heading for instance if this was the place where I have added the new font.

Add the font that you need like normal way for React Native (here is a simple guide: https://blog.logrocket.com/adding-custom-fonts-react-native/) and then follow gluestack-ui guide for Next.js.

I hope this make sense.

Regards


—
Hristo Dimitrov
Software Engineer II
Veliko Turnovo, Bulgaria


[https://lh7-us.googleusercontent.com/CQ7wMPqk5D65sXxhtUz00z8MOei9f5aur9PfwEp_vJWDtoMK6EpXWuiWao2ZQnlD3UGxHVrmu6jyRX6CVj1fTjrthGFZh3Sa6jUBqsWdXAaHoacTzl_OIBb9KmN6kgtbbrLjtZ_jhPvA4KsduVeaiBI]
***CONFIDENTIALITY NOTICE: The contents of this e-mail message and any attachments are confidential and are intended solely for the addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.




From: Felipe Estevão Moreno ***@***.***>
Date: Tuesday, 26 March 2024 at 22:55
To: gluestack/gluestack-ui ***@***.***>
Cc: Hristo Dimitrov ***@***.***>, State change ***@***.***>
Subject: Re: [gluestack/gluestack-ui] Please guide us how to add fonts to RN CLI in the documentation! (Issue #1773)

Thank you for your assistance with adding fonts to React Native. I initially encountered difficulties, but now it's working as expected. I apologize if I raised any unnecessary concerns. Your help is greatly appreciated.

Hello.
How did you solve this problem? I can use normal fonts with react-native styles, but gluestack doesn't work.
