### ISSUE TITLE
Page not showing - install with expo

### ISSUE THREAD

**Issue by pupattan** [gluestack/gluestack-ui#1778]
### Description

The follwing page not showing . how to install with expo. https://gluestack.io/ui/docs/getting-started/ui/docs/guides/install-expo

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by RishabhSahu24** [comment]
Thank you for reporting this. We have updated our documentation and resolved the issue.
