### ISSUE TITLE
The checkbox component is missing an indetermined icon.

### ISSUE THREAD

**Issue by doodle-codes** [gluestack/gluestack-ui#1787]
### Description

After integrating your checkbox component, I observed that the UI library lacks specific styling for checkboxes in the indeterminate state. It would be beneficial to enhance the component structure by incorporating an additional dash icon to visually represent this state. Additionally, I noticed that your documentation currently lacks an illustrative example showcasing this particular checkbox state. Including such an example would provide users with a clearer understanding of the indeterminate state and its visual representation.

![indeterminate-checkboxes](https://github.com/gluestack/gluestack-ui/assets/60889622/513282fc-a1fd-4791-839c-6d7ee91ac99a)

### Steps to reproduce

To reproduce the issue. Just set the `isIndetermined` prop state to true in the Checkbox component.

### gluestack-ui Version

1.0.4

### Platform

- [X] Expo
- [X] React Native CLI
- [X] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by doodle-codes** [comment]
![indeterminate-checkboxes](https://github.com/gluestack/gluestack-ui/assets/60889622/513282fc-a1fd-4791-839c-6d7ee91ac99a)

**Comment by doodle-codes** [comment]
Can someone with the rights add a `gluestack-style` label to this open issue?

**Comment by sem4phor** [comment]
Furthermore the checkbox indicator just doesn't render the checkbox icon when the checkbox is in indeterminate state :/

**Comment by Viraj-10** [comment]
@doodle-codes This is related to gluestack-ui and `@gluestack-ui/checkbox`. 
@sem4phor Thanks for suggestion. We will add this to our package.

**Comment by Viraj-10** [comment]
Hey @doodle-codes @doodle-codes, This can be achieved now with `forceMount` prop on checkbox icon. [PR](https://github.com/gluestack/gluestack-ui/pull/2438).
