### ISSUE TITLE
Menu opens behind screen on iOS when using `{ presentation: "modal" }`

### ISSUE THREAD

**Issue by brianGammon** [gluestack/gluestack-ui#1794]
### Description

The Menu opens behind the modal screen on iOS when using `{ presentation: "modal" }`. [EDIT] - There does not seem to be a `useRNModal` prop on Menu, which fixes this issue on other components.

This is easy to reproduce using the steps below:

### Steps to reproduce

1. Run `npx create-expo-app@latest --template tabs@50`
2. Intall gluestack: `npm i @gluestack-ui/themed @gluestack-style/react yarn add @gluestack-ui/config@latest react-native-svg@13.4.0`
3. Edit the file `app/_layout.tsx`, add the gluestack provider:
```
<ThemeProvider value={colorScheme === "dark" ? DarkTheme : DefaultTheme}>
      <GluestackUIProvider config={config}>
        <Stack>
          <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
          <Stack.Screen name="modal" options={{ presentation: "modal" }} />
        </Stack>
      </GluestackUIProvider>
    </ThemeProvider>
```
4. Edit the file `app/modal.tsx`, add the sample code from the Menu documentation:
```
import { StatusBar } from 'expo-status-bar';
import { Platform, StyleSheet } from 'react-native';
import { View } from '@/components/Themed';
import { AddIcon, Button, ButtonText, EyeIcon, GlobeIcon, Icon, Menu, MenuItem, MenuItemLabel, SettingsIcon, SunIcon } from '@gluestack-ui/themed';

export default function ModalScreen() {
  return (
    <View style={styles.container}>
      
      <Menu
        placement="top"
          trigger={({ ...triggerProps }) => {
            return (
              <Button {...triggerProps}>
                <ButtonText>Menu</ButtonText>
              </Button>
            );
          }}
        >
          <MenuItem key="Community" textValue="Community">
            <Icon as={GlobeIcon} size="sm" mr='$2'/>
            <MenuItemLabel size='sm'>
              Community
            </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Plugins" textValue="Plugins">
              {/* PuzzleIcon is imported from 'lucide-react-native' */}
              <Icon as={EyeIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Plugins
              </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Theme" textValue="Theme">
              {/* PaintBucket is imported from 'lucide-react-native' */}
              <Icon as={SunIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Theme
              </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Settings" textValue="Settings">
              <Icon as={SettingsIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Settings
              </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Add account" textValue="Add account">
              <Icon as={AddIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Add account
              </MenuItemLabel>
          </MenuItem>
        </Menu>

      {/* Use a light status bar on iOS to account for the black space above the modal */}
      <StatusBar style={Platform.OS === 'ios' ? 'light' : 'auto'} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  separator: {
    marginVertical: 30,
    height: 1,
    width: '80%',
  },
});

```
5. Run `npm run ios`
6. Open the modal, and press the Menu button

### gluestack-ui Version

1.1.6

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by salihcodes** [comment]
Here's a version of your code that should work

```typescript
import { StatusBar } from 'expo-status-bar';
import { Platform, StyleSheet } from 'react-native';
import { View } from '@/components/Themed';
import { AddIcon, Button, ButtonText, EyeIcon, GlobeIcon, Icon, Menu, MenuItem, MenuItemLabel, SettingsIcon, SunIcon,        OverlayProvider
 } from '@gluestack-ui/themed';

export default function ModalScreen() {
  return (
   <OverlayProvider>
    <View style={styles.container}>
      
      <Menu
        placement="top"
          trigger={({ ...triggerProps }) => {
            return (
              <Button {...triggerProps}>
                <ButtonText>Menu</ButtonText>
              </Button>
            );
          }}
        >
          <MenuItem key="Community" textValue="Community">
            <Icon as={GlobeIcon} size="sm" mr='$2'/>
            <MenuItemLabel size='sm'>
              Community
            </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Plugins" textValue="Plugins">
              {/* PuzzleIcon is imported from 'lucide-react-native' */}
              <Icon as={EyeIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Plugins
              </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Theme" textValue="Theme">
              {/* PaintBucket is imported from 'lucide-react-native' */}
              <Icon as={SunIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Theme
              </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Settings" textValue="Settings">
              <Icon as={SettingsIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Settings
              </MenuItemLabel>
          </MenuItem>
          <MenuItem key="Add account" textValue="Add account">
              <Icon as={AddIcon} size="sm" mr='$2'/>
              <MenuItemLabel size='sm'>
                Add account
              </MenuItemLabel>
          </MenuItem>
        </Menu>

      {/* Use a light status bar on iOS to account for the black space above the modal */}
      <StatusBar style={Platform.OS === 'ios' ? 'light' : 'auto'} />
    </View>
   <OverlayProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  separator: {
    marginVertical: 30,
    height: 1,
    width: '80%',
  },
});

```

In simple terms you need to add an <OverlayProvider> around the ModalScreen component.

**Comment by salihcodes** [comment]
> Here's a version of your code that should work
> 
> ```ts
> import { StatusBar } from 'expo-status-bar';
> import { Platform, StyleSheet } from 'react-native';
> import { View } from '@/components/Themed';
> import { AddIcon, Button, ButtonText, EyeIcon, GlobeIcon, Icon, Menu, MenuItem, MenuItemLabel, SettingsIcon, SunIcon,        OverlayProvider
>  } from '@gluestack-ui/themed';
> 
> export default function ModalScreen() {
>   return (
>    <OverlayProvider>
>     <View style={styles.container}>
>       
>       <Menu
>         placement="top"
>           trigger={({ ...triggerProps }) => {
>             return (
>               <Button {...triggerProps}>
>                 <ButtonText>Menu</ButtonText>
>               </Button>
>             );
>           }}
>         >
>           <MenuItem key="Community" textValue="Community">
>             <Icon as={GlobeIcon} size="sm" mr='$2'/>
>             <MenuItemLabel size='sm'>
>               Community
>             </MenuItemLabel>
>           </MenuItem>
>           <MenuItem key="Plugins" textValue="Plugins">
>               {/* PuzzleIcon is imported from 'lucide-react-native' */}
>               <Icon as={EyeIcon} size="sm" mr='$2'/>
>               <MenuItemLabel size='sm'>
>                 Plugins
>               </MenuItemLabel>
>           </MenuItem>
>           <MenuItem key="Theme" textValue="Theme">
>               {/* PaintBucket is imported from 'lucide-react-native' */}
>               <Icon as={SunIcon} size="sm" mr='$2'/>
>               <MenuItemLabel size='sm'>
>                 Theme
>               </MenuItemLabel>
>           </MenuItem>
>           <MenuItem key="Settings" textValue="Settings">
>               <Icon as={SettingsIcon} size="sm" mr='$2'/>
>               <MenuItemLabel size='sm'>
>                 Settings
>               </MenuItemLabel>
>           </MenuItem>
>           <MenuItem key="Add account" textValue="Add account">
>               <Icon as={AddIcon} size="sm" mr='$2'/>
>               <MenuItemLabel size='sm'>
>                 Add account
>               </MenuItemLabel>
>           </MenuItem>
>         </Menu>
> 
>       {/* Use a light status bar on iOS to account for the black space above the modal */}
>       <StatusBar style={Platform.OS === 'ios' ? 'light' : 'auto'} />
>     </View>
>    <OverlayProvider>
>   );
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>   },
>   title: {
>     fontSize: 20,
>     fontWeight: 'bold',
>   },
>   separator: {
>     marginVertical: 30,
>     height: 1,
>     width: '80%',
>   },
> });
> ```
> 
> In simple terms you need to add an OverlayProvider around the ModalScreen component.

## Note:  Same thing applies to all other components in the Overlay section if you're trying to trigger them from a different route group.

**Comment by brianGammon** [comment]
Hi, thanks for this info. I added the OverlayProvder as you suggested, it helps and the menu does appear, but there are still a couple of issues:
* The menu opens with a large margin between it and the trigger button
* The menu is not themed properly

<img width="482" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/16623517/674ec745-b3b4-45e8-a3a0-0db37b1cc15b">


Here is the updated code for modal.tsx for easy repro using the steps in my original message above. Note: I found that `<OverlayProvider>` is imported from @gluestack-ui/overlay, NOT @gluestack-ui/themed in your snippet.
```
import { StatusBar } from "expo-status-bar";
import { Platform, StyleSheet } from "react-native";
import { OverlayProvider } from "@gluestack-ui/overlay";
import {
  AddIcon,
  Button,
  ButtonText,
  EyeIcon,
  GlobeIcon,
  Icon,
  Menu,
  MenuItem,
  MenuItemLabel,
  SettingsIcon,
  SunIcon,
  View,
} from "@gluestack-ui/themed";

export default function ModalScreen() {
  return (
    <OverlayProvider>
      <View style={styles.container}>
        <Menu
          trigger={({ ...triggerProps }) => {
            return (
              <Button {...triggerProps}>
                <ButtonText>Menu</ButtonText>
              </Button>
            );
          }}
        >
          <MenuItem key="Community" textValue="Community">
            <Icon as={GlobeIcon} size="sm" mr="$2" />
            <MenuItemLabel size="sm">Community</MenuItemLabel>
          </MenuItem>
          <MenuItem key="Plugins" textValue="Plugins">
            {/* PuzzleIcon is imported from 'lucide-react-native' */}
            <Icon as={EyeIcon} size="sm" mr="$2" />
            <MenuItemLabel size="sm">Plugins</MenuItemLabel>
          </MenuItem>
          <MenuItem key="Theme" textValue="Theme">
            {/* PaintBucket is imported from 'lucide-react-native' */}
            <Icon as={SunIcon} size="sm" mr="$2" />
            <MenuItemLabel size="sm">Theme</MenuItemLabel>
          </MenuItem>
          <MenuItem key="Settings" textValue="Settings">
            <Icon as={SettingsIcon} size="sm" mr="$2" />
            <MenuItemLabel size="sm">Settings</MenuItemLabel>
          </MenuItem>
          <MenuItem key="Add account" textValue="Add account">
            <Icon as={AddIcon} size="sm" mr="$2" />
            <MenuItemLabel size="sm">Add account</MenuItemLabel>
          </MenuItem>
        </Menu>
        {/* Use a light status bar on iOS to account for the black space above the modal */}
        <StatusBar style={Platform.OS === "ios" ? "light" : "auto"} />
      </View>
    </OverlayProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
  },
  separator: {
    marginVertical: 30,
    height: 1,
    width: "80%",
  },
});

```

**Comment by brianGammon** [comment]
Hi @salihcodes, I did not dig into the code but did notice that if I give the Menu a `mt={-90}` prop it makes it line up with the triggering button. I moved onto other priorities but this is easy to replicate using the sample code above. Note - it is only an issue when using Menu on iOS for a screen with `presentation: 'modal'`.

**Comment by Viraj-10** [comment]
Hey @brianGammon @salihcodes, We have added feat of `useRNModal` on menu component. Please upgrade to latest version.
