### ISSUE TITLE
Select: Selected Value is not getting highlighted in native device. 

### ISSUE THREAD

**Issue by Viraj-10** [gluestack/gluestack-ui#1800]
### Description

I am seeing a regression on the Select component with the updated version. On 1.1.4, the selected item was highlighted on the ActionSheet (on native), however now on 1.1.6 the selected item is not highlighted at all. Screenshots before and after:  Gluestack 1.1.4 
<img width="250" alt="iPhone_14-3" src="https://github.com/gluestack/gluestack-ui/assets/16623517/b7859748-6e0c-41e0-9a1d-ffbb366f58a4"> 
Gluestack 1.1.6 
<img width="250" alt="iPhone_14-4" src="https://github.com/gluestack/gluestack-ui/assets/16623517/ac514534-76e2-48e9-ab35-c699cea368f1">

### gluestack-ui Version

1.1.6

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by AlexMachin1997** [comment]
Hey @Viraj-10 

I've just come across something like this, I've noticed it happening in version 1.1.4 as well not sure why as it seems to be working for you hmm.

I created a brand new repo with the Solito + Gluestack using one of the starters, originally it didn't experience the issue as it was using the following dependencies:

"@gluestack-style/react": "^1.0.15",
"@gluestack-ui/config": "^1.0.3",
"@gluestack-ui/themed": "^1.0.13",


After upgrading the brand new repo to use my current projects dependencies:

"@gluestack-style/react": "^1.0.47",
"@gluestack-ui/config": "^1.1.2",
"@gluestack-ui/themed": "^1.1.4",

It experiences the select options not being showing up in the selected state.

**Comment by Viraj-10** [comment]
@AlexMachin1997, This issue has been fixed. We have replaced this with `checked` instead of `active`. You can check code [here](https://github.com/gluestack/gluestack-ui/pull/1795/files#diff-00528209598a12b1a55a437d809823017c2849da82574ed4c438d19ec548249b).

**Comment by AlexMachin1997** [comment]
Hey @Viraj-10 That's great news, I can see its been merged into a branch named "patch" ? Has this been released or is this going to be merged into main pretty soon ?

**Comment by rajat693** [comment]
This issue is now resolved, so I am closing it. If you have any further questions or issues, please feel free to reopen it.
thank you
