### ISSUE TITLE
Pressable child prop does not work

### ISSUE THREAD

**Issue by ethandpowers** [gluestack/gluestack-ui#1813]
### Description

Pressable child state not changing

### Steps to reproduce

1. Go to Gluestack docs: https://gluestack.io/ui/docs/components/forms/pressable'
2. Scroll down to **Pressable child elements according to its states**
3. Click the Box and notice that the text does not change to pink. 

### gluestack-ui Version

default on website

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by rajat693** [comment]
Hi @ethandpowers , Thanks for reporting the issue. We will look into it.

**Comment by rajat693** [comment]
This issue is now resolved, so I am closing it.
