### ISSUE TITLE
Text component cut text when using larger fontSize

### ISSUE THREAD

**Issue by alfjesus** [gluestack/gluestack-ui#1836]
### Description

When using the Text component, the text is cut on the top when using bigger fontSizes (i.e 3xl, 4xl ))

### Steps to reproduce

`<Text color="$white" fontSize={'$4xl'}>Hello</Text>`

### gluestack-ui Version

1.1.8

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

Similar to earlier fixed issue #1653 

This bug is not happening if I use the Text component from react-native

**Comment by Viraj-10** [comment]
Hey @alfjesus, Thanks for reporting this issue. We have fixed this issue in latest version of `@gluestack-ui/config`.

**Comment by nicolascavallin** [comment]
> Hey @alfjesus, Thanks for reporting this issue. We have fixed this issue in latest version of `@gluestack-ui/config`.

Hey @Viraj-10, sorry for reaching out here, but I would like to understand how this fix applies to my gluestack setup if I have ejected the theme and now I have the `Text.tsx` component in my files and is not being reached from node_modules.

Thanks in advance 🙏🏼

**Comment by teckbeng-payboy** [comment]
Hi, I think the issue happen again.. all the lineheight is off

**Comment by Viraj-10** [comment]
> > Hey @alfjesus, Thanks for reporting this issue. We have fixed this issue in latest version of `@gluestack-ui/config`.
> 
> Hey @Viraj-10, sorry for reaching out here, but I would like to understand how this fix applies to my gluestack setup if I have ejected the theme and now I have the `Text.tsx` component in my files and is not being reached from node_modules.
> 
> Thanks in advance 🙏🏼

Hey @nicolascavallin, sorry for late reply. Here is a [PR](https://github.com/gluestack/gluestack-ui/pull/1838/files) link to check the differences.

**Comment by Viraj-10** [comment]
> Hi, I think the issue happen again.. all the lineheight is off

Hey @teckbeng-payboy, Please report this as a new issue with reproduction of the example.

**Comment by teckbeng-payboy** [comment]
@Viraj-10  so for the text component currently there is no line height been set by default right? 

Based on the PR, after you comment out the md, all the lineheight wont be working

**Comment by Viraj-10** [comment]
@teckbeng-payboy, Yes we have removed default `lineHeight` from `Text`.

**Comment by teckbeng-payboy** [comment]
Right now how can i add lineheight to the text component?

For example: 

```
xs: {
        fontSize: '$xs',
        lineHeight: '$xs',
      },
sm: {
      fontSize: '$sm',
      lineHeight: '$sm',
    },
```
