### ISSUE TITLE
Why must the Image component pass the alt props?

### ISSUE THREAD

**Issue by chenyunlin1** [gluestack/gluestack-ui#1857]
### Description

I don't need the alt attribute. If I don't add it, I get a warning ！ Please pass alt prop to Image component

### Steps to reproduce

<Image
        source={{
          uri: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
        }}
      />

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @chenyunlin1, As per W3C [guidelines](https://www.w3.org/TR/html401/struct/objects.html#edef-IMG). You have to provide alt for image. This Improves your accessibility score and helps screen reader to spell out description of your Image.
