### ISSUE TITLE
Help with my 'component showcase' project.

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#191]
Guys, I'm trying to do a showcase using this library... My intention with it, is to create a kind of documentation showing how every dev can personalize these components as they like. But in this process, I'm facing a lot of issues and questions about it...

The main concept, is customize every component "rebuilding itself", but adding my custom styles using "styled" from [dank.style](https://dank.style/). After that, I want to share my custom components to the other, like Select that depends on ActionSheet...

Said that, I'd like to know if there are somebody that I can share my private project, for now, and show exactly what I'm trying to do and what's making me stucked?

I'm big fan of NativeBase and I'm enjoying GluestackUI, even these issues. 💪🏼

**Comment by mayank-96** [comment]
Sure! @NandoMB I can help you here.

**Comment by NandoMB** [comment]
> Sure! @NandoMB I can help you here.

Great @mayank-96! I already added you to the project

**Comment by NandoMB** [comment]
At the project, I opened some issues to describe my questions.
