### ISSUE TITLE
Text Variants

### ISSUE THREAD

**Issue by nicolascavallin** [gluestack/gluestack-ui#1924]
### Description

With **Native Base** was possible to have variants for text style, i.e.: we use a variant called `subtitle1` to bring a specific font-size, line-height, color, and font-weight. 

### Problem Statement

I'm not finding the same API with Text from `@gluestack-ui/themed`. Just some modifiers as `bold`, `isTruncated`, `highlight`, etc.

### Proposed Solution or API

A similar `variant` API in components (also Heading, Button, etc) that makes it possible to have "a variant" without creating a new component with `styled`, etc...

**Comment by surajahmed** [comment]
@nicolascavallin You can eject the library and add custom variant to the components. Please follow this link to eject library: https://gluestack.io/ui/docs/theme-configuration/customizing-theme/eject-library

**Comment by nicolascavallin** [comment]
Thanks @surajahmed 

My point is: this will be available in the future in the Gluestack roadmap? Or should I eject if I want this kind of feature? 

Thanks in advance!

**Comment by Viraj-10** [comment]
@nicolascavallin, for additional features you have to eject your theme and going forward we are promoting ejecting theme for more customisation. We are creating powerful cli tooling around it which will help. Ejecting theme more easy.

**Comment by nicolascavallin** [comment]
Thanks @Viraj-10
