### ISSUE TITLE
Active state styling ':active' for Button doesn't apply in React native app

### ISSUE THREAD

**Issue by JuarezCout** [gluestack/gluestack-ui#1953]
### Description

I added in my Button.ts config style the prop ':active' so that while the user press on the button, include a shadow on it. But I tried in so many ways and no success.  

### Steps to reproduce

1. Go to config file Button.ts and add a ':active' prop. 
2. Test in application pressing the button

### gluestack-ui Version

1.0.34

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

### Additional Information

Where I added the active prop
<img width="807" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/22419281/935c1606-6892-424d-aca1-304c90c88ac9">

**Comment by JuarezCout** [comment]
This apparently have the same error for web because when I click a button with active prop in this page on Gluestack documentation: [https://gluestack.io/ui/docs/styling/utility-and-sx-props], it doesn't either.

**Comment by Viraj-10** [comment]
Hey @JuarezCout, 
```
    ":active": {
    _web:{
          boxShadow: "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
          },
             },
```
Try this 

> Note this will not work on native.
