### ISSUE TITLE
Tabs component documentation using non-existent components

### ISSUE THREAD

**Issue by snksergio** [gluestack/gluestack-ui#1970]
### Description

The usage example in the tabs component documentation does not reflect reality

### gluestack-ui Version

1.0.32 (themed)

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

The documentation recommends use following the structure:

```
export default () => (
  <Tabs>
    <TabsList>
      <TabsTrigger>
        <TabsText />
      </TabsTrigger>
    </TabsList>
    <TabsContents>
      <TabsContent />
    </TabsContents>
  </Tabs>
)
```

However, some components such as TabsTrigger were not found and others such as TabsList underwent a name update at some point. The structure I managed to work with was::

```
const TabsExample = () => {
  return (
    <G.Tabs>
      <G.TabsTabList>
        <G.TabsTab>
          <G.TabsTabTitle>Example 1</G.TabsTabTitle>
        </G.TabsTab>
        <G.TabsTab>
          <G.TabsTabTitle>Example 2</G.TabsTabTitle>
        </G.TabsTab>
      </G.TabsTabList>
      <G.TabsTabPanels>
        <G.TabsTabPanel>
          <G.Text>Body 1</G.Text>
        </G.TabsTabPanel>
        <G.TabsTabPanel>
          <G.Text>Body 2</G.Text>
        </G.TabsTabPanel>
      </G.TabsTabPanels>
    </G.Tabs>
  );
};
```

**Comment by Viraj-10** [comment]
Hey @snksergio, Tab is under `api-draft` phase. We are currently working on this component but we have yet to release it.
`API-DRAFT` tag stands for in future component api might look like that. 
here is a PR [link](https://github.com/gluestack/gluestack-ui/pull/1735).


<img width="944" alt="Screenshot 2024-03-19 at 5 51 34 PM" src="https://github.com/gluestack/gluestack-ui/assets/66306233/d2cba492-4c35-4d28-8427-7527d02a9505">

**Comment by snksergio** [comment]
Oh, my bad! Thanks for responding anyway!
