### ISSUE TITLE
VSCode Intellisense slows down with `@gluestack-ui/themed` imports

### ISSUE THREAD

**Issue by DavidAmyot** [gluestack/gluestack-ui#1976]
### Description

I expect the @gluestack-ui/themed imports to not impact VSCode Intellisense performance.

### Steps to reproduce

1. Have some imports such as `import { Box, Fab, FlatList, Heading, Text } from "@gluestack-ui/themed";`
2. Make a typo somewhere to trigger an error.
3. Hover on where you made the typo and wait for it to show there's an error.
4. Remove the typo, comment out the `@gluestack-ui/themed` imports and repeat step 2 and 3.
5. Notice that the Intellisense is much faster.

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Related closed PR: https://github.com/gluestack/gluestack-ui/issues/903

Sometimes it's so slow I have to run the _Reload Window_ command from the command palette on VSCode.

Demo video:
https://github.com/gluestack/gluestack-ui/assets/60398892/e972600b-e3d4-49aa-9830-8a1ab2ca51c0

**Comment by surajahmed** [comment]
Hey @DavidAmyot, Can you please try updating `@gluestack-ui/themed`, `@gluestack-style/react` and `@gluestack-ui/config` to latest?

**Comment by James-Whitfield** [comment]
Upgraded to Gluestack from native base. VS Code now runs very slow for intellisense.

"@gluestack-style/react": "^1.0.52",
"@gluestack-ui/config": "^1.1.18",
"@gluestack-ui/themed": "^1.1.18",
        
 npx tsc --diagnostics --noEmit  
 
 Files:             1839
Lines:           252040
Identifiers:     305962
Symbols:        1027005
Types:            76074
Instantiations: 3290758
Memory used:    749434K
I/O read:         0.21s
I/O write:        0.00s
Parse time:       0.96s
Bind time:        0.21s
Check time:      24.39s
Emit time:        0.00s
Total time:      25.56s

Before upgrade:

Files:             1778
Lines:           272524
Identifiers:     307756
Symbols:         334010
Types:            78128
Instantiations:  273688
Memory used:    412670K
I/O read:         0.06s
I/O write:        0.00s
Parse time:       0.68s
Bind time:        0.22s
Check time:       0.99s
Emit time:        0.00s
Total time:       1.90s

Hopefully this can be resolved soon. It is making development for my teams very painful.

**Comment by MatheusAVZ** [comment]
Hey, i have the same problem, the VSCode Intellisense slows down with @gluestack-ui/themed imports

"@gluestack-style/react": "latest",
"@gluestack-ui/config": "latest",
"@gluestack-ui/themed": "latest",

Platform

- [ ] Expo
- [x]  React Native CLI
- [ ]  Next
- [ ]  Web
- [ ]  Android
- [ ]  iOS

**Comment by DavidAmyot** [comment]
@surajahmed Any update on this?

**Comment by ankit-tailor** [comment]
Hey @DavidAmyot, Please try below versions.

```
"@gluestack-style/react": "^1.0.53",
"@gluestack-ui/config": "^1.1.18",
"@gluestack-ui/themed": "^1.1.22",
```

**Comment by James-Whitfield** [comment]
@ankit-tailor 

Your latest versions listed below have caused no improvement in my project.
```
"@gluestack-style/react": "^1.0.53",
"@gluestack-ui/config": "^1.1.18",
"@gluestack-ui/themed": "^1.1.22",
```
```
jameswhitfield@Jamess-MacBook-Pro mobile % npx tsc --diagnostics --noEmit
Files:              1826
Lines:            251366
Identifiers:      305448
Symbols:         1642228
Types:            195630
Instantiations:  7896064
Memory used:    1139343K
I/O read:          0.05s
I/O write:         0.00s
Parse time:        0.72s
Bind time:         0.21s
Check time:       40.36s
Emit time:         0.00s
Total time:       41.29s
```
If i remove gluestack from the project
```
jameswhitfield@Jamess-MacBook-Pro mobile % npx tsc --diagnostics --noEmit 
Files:             1389
Lines:           234915
Identifiers:     276046
Symbols:         286118
Types:            60673
Instantiations:  260626
Memory used:    359674K
I/O read:         0.04s
I/O write:        0.00s
Parse time:       0.60s
Bind time:        0.20s
Check time:       0.82s
Emit time:        0.00s
Total time:       1.62s
```

Are you able to share any diagnostics for your changes and the impact you were hoping to see in the latest updates?

**Comment by huix9527** [comment]
`    "@gluestack-style/react": "^1.0.52",
    "@gluestack-ui/config": "^1.1.18",
    "@gluestack-ui/themed": "^1.1.22",
`

` npx tsc --diagnostics --noEmit
Files:             1298
Lines:           179610
Identifiers:     164305
Symbols:         809868
Types:           136352
Instantiations: 4853127
Memory used:    628113K
I/O read:         0.18s
I/O write:        0.00s
Parse time:       0.81s
Bind time:        0.21s
Check time:      17.78s
Emit time:        0.00s
Total time:      18.81s
`
