### ISSUE TITLE
tintColor prop on image doesn't accept tokens

### ISSUE THREAD

**Issue by lhguerra** [gluestack/gluestack-ui#1978]
### Description

When i set a tint color with a color token I get invalid value error

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.1.17

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

 ERROR  Warning: Failed prop type: Invalid prop `tintColor` supplied to `Image`: $white.default
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

    at BaseImage (http://192.168.15.3:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:77578:70)
    in StyledComponent (created by Image)

**Comment by lhguerra** [comment]
I also don't know how the reset its value, no matter what I pass (like null or an empty string) gives me the invalid color error. We should be able to unset such value! Like this `tintColor={reactionStatus === ReactionType.dislike ? "#D33030" : ""}`

**Comment by surajahmed** [comment]
@lhguerra You can use `useToken` hook available in `@gluestack-ui/themed`. With this hook, you can access the token value, which can then be passed to the respective prop. For more details, follow this link https://gluestack.io/ui/docs/hooks/use-token

**Comment by lhguerra** [comment]
I know that, but why would I need to do that using a Gluestack component?

**Comment by sra1kumar-NULL** [comment]
hey @lhguerra @philippbosch @RobertSasak , we are closing this issue for now, please feel free to reopen this issue if there is any issue / concern / queries regarding this issue context.
