### ISSUE TITLE
How can i bind data whithon <InputField/> components

### ISSUE THREAD

**Issue by JohniFirst** [gluestack/gluestack-ui#2015]
### Description

I can' t get the input value via onChange callback

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.1.17

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @JohniFirst, Please refer this [snack](https://snack.expo.dev/@viraj_10/input-onchange-example).

**Comment by JohniFirst** [comment]
> Hey @JohniFirst, Please refer this [snack](https://snack.expo.dev/@viraj_10/input-onchange-example).

Sure, I noticed this api, but the onChangeText fn can only get the current input word, and I don't know the current operation is add or delete, this is different with other plotforms.  Usually I‘ll get all the contents of the current input field.
