### ISSUE TITLE
Jest Test Error Cannot read properties of undefined (reading 'displayName')

### ISSUE THREAD

**Issue by Cowner** [gluestack/gluestack-ui#2039]
### Description

Jest test failing when a gluestack component is rendered on the screen

### CodeSandbox/Snack link

https://github.com/Cowner/gluestack-test-error

### Steps to reproduce

1. Create a fresh gluestack project using `npm create gluestack`
2. Setup jest package for nextjs following https://nextjs.org/docs/app/building-your-application/testing/jest
3. Resolve module transpiling issues (react-native, react-native-svg)
4. Create simple jest test for `Page.tsx` rendering a gluestack View (or any other gluestack component)
5. Run test and receive: `TypeError: Cannot read properties of undefined (reading 'displayName')`
(see Sandbox repo)

### gluestack-ui Version

1.1.17

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by surajahmed** [comment]
@Cowner Thanks for reporting this. We'll have a look.

**Comment by UmberBn** [comment]
@Cowner you can update your gluestack packages and verify if the error is resolved?

**Comment by Cowner** [comment]
@UmberBn thank you for getting onto this, due to the projects tight deadline we had to pivot and setup with Tamagui, but will keep this in mind for future projects :thumbsup:
