### ISSUE TITLE
Dark mode props overwriting light props

### ISSUE THREAD

**Issue by jordmccord** [gluestack/gluestack-ui#2058]
### Description

While styling my button spinner I've noticed that the dark mode styles, when applied via the prop color value, overwrite the light mode styles

### Steps to reproduce

1. Apply styles to the button component via the config
2. Update the spinner styles by adding prop -> color -> `value`
3. Update the dark styles
4. The light mode has the dark mode styles

### gluestack-ui Version

1.1.22

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

### Additional Information

![Screenshot 2024-04-09 at 14 33 13](https://github.com/gluestack/gluestack-ui/assets/7591840/88135edc-5a32-44dc-8f8a-3206f012d4a0)
![Screenshot 2024-04-09 at 14 33 44](https://github.com/gluestack/gluestack-ui/assets/7591840/b3561077-699b-47b1-a249-e6017a8887a5)
![Screenshot 2024-04-09 at 14 42 44](https://github.com/gluestack/gluestack-ui/assets/7591840/dec59e06-2b2e-43f2-8748-cd4a108c47c0)
![Screenshot 2024-04-09 at 14 42 51](https://github.com/gluestack/gluestack-ui/assets/7591840/2fc38d50-b269-4795-a645-60e869f2428c)

**Comment by surajahmed** [comment]
@jordmccord Thanks for reporting this.

**Comment by surajahmed** [comment]
Closing this issue since it has been resolved in the latest version. If the problem continues, please feel free to reopen it.
Please update `@gluestack-ui/themed` and `@gluestack-style/react` to the latest version.
