### ISSUE TITLE
[Select Component] Annoying forwardRef

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#206]
On Terminal

<img width="1440" alt="Select Refs 1" src="https://user-images.githubusercontent.com/5796053/229561924-743ed621-f1b6-4ba2-a042-6531ca2dd83c.png">

On Simulator

![Select Refs 2](https://user-images.githubusercontent.com/5796053/229562144-aaff69f5-458a-47f7-8ec0-df92d35bf21c.jpeg)

**Comment by mayank-96** [comment]
Hello @NandoMB , 
This issue is fixed with latest version of select `0.1.1`
