### ISSUE TITLE
Scroll not working on web

### ISSUE THREAD

**Issue by mathis-kdio** [gluestack/gluestack-ui#2065]
### Description

Scroll not working only on web

### CodeSandbox/Snack link

https://snack.expo.dev/@matkdio/e86a22

### Steps to reproduce

Use the `ScrollView` or `FlatList` or any other component with scroll

### gluestack-ui Version

1.1.22

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @mathis-kdio, Please apply `<SafeAreaView style={{flex:1}}>` this changes to code base. 
for more details please read react native docs [here](https://reactnative.dev/docs/scrollview).

**Comment by mathis-kdio** [comment]
I don't know why it works in the Snack code, but it doesn't work in my project. 
I have to add `height={'$1'}` to the `<Scrollview>` for it to work
