### ISSUE TITLE
InputSlot, Text not apply color attribute

### ISSUE THREAD

**Issue by andrconstruction** [gluestack/gluestack-ui#2068]
### Description

InputSlot, Text not apply color attribute

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.52

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by andrconstruction** [comment]
![image](https://github.com/gluestack/gluestack-ui/assets/7435330/2cb6c223-889c-4b73-aed9-5249199dc074)
DarkMode

**Comment by andrconstruction** [comment]
![image](https://github.com/gluestack/gluestack-ui/assets/7435330/59dc712f-ef4a-4fda-aede-0edf4903322f)
LightMode

**Comment by andrconstruction** [comment]
`<InputSlot px="$2"
                                               bg={ isDark ? "$brandPrimary":  "$secondary300" }
                                               color={ isDark ? "$secondary300":  "$brandPrimary" }

                                    >`

**Comment by andrconstruction** [comment]
bg is works as expected, but not color

**Comment by Viraj-10** [comment]
Hey @andrconstruction, can you give create snack example of this and share with us?

**Comment by DaminiPandey** [comment]
Hey @andrconstruction In order to give color to the text inside InputSlot, you need to pass the color prop to the <Text> component.


Something like this:

`
           <Input>
            <InputField />
            <InputSlot bg="$primary600" p="$2">
              <Text color="$fuchsia50" sx={{
                "_darK": {
                  color: "$black"
                }
              }}>Press</Text>
            </InputSlot>
          </Input>
`

I've created an example demo [here](https://snack.expo.dev/@da_minnie/inputslot-example). Hope it will be helpful to you.

**Comment by andrconstruction** [comment]
im so sorry, the problem is that <Text> did imported from react-native instead gluestack, now all work as expected

**Comment by DaminiPandey** [comment]
Great! @andrconstruction, I'm closing the issue as it is resolved, please feel free to reopen it in case of any problem.
