### ISSUE TITLE
[Select Component] Visual problems

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#207]
#### When you use the default Select component, imported from gluestack, it seems like this:

![IMG_BE9AFFF4923B-1](https://user-images.githubusercontent.com/5796053/229563323-357a0c17-ee38-4ef1-975d-fca0eeab91d1.jpeg)

#### Fix:
Change the default width to ```100%``` and height to ```auto```
![Select Problem FIX](https://user-images.githubusercontent.com/5796053/229564147-d4792935-0724-489d-a0f6-63ff1772886b.png)

#### Part 2
And when you add many components, the size of Actionsheet breaks the layout, like this:

https://user-images.githubusercontent.com/5796053/229563230-a836e30d-0002-4af7-ac25-e005bfe74bc8.MP4

#### Fix:
Add a scrollView to the Actionsheet's container:
![Select Problem1](https://user-images.githubusercontent.com/5796053/229564778-51b69419-899c-4fc6-a758-17b674f8ce28.png)

Here, ```maxHeight``` could be calculated by a component prop... I put it fixed just to test. 
![Select Problem2](https://user-images.githubusercontent.com/5796053/229564804-0aef79dd-f24b-422a-af3c-d0afd74bf39c.png)

#### After that, the layout will look more concise:
```Ignore all the colors, it's just to test```
![Select Problem](https://user-images.githubusercontent.com/5796053/229565668-54d1ca6b-8d11-48e9-9a7f-108a0cceba74.jpeg)

**Comment by mayank-96** [comment]
Hello @NandoMB ,
This issue is fixed with latest version of `select@0.1.1`
