### ISSUE TITLE
[Command Line] npx gluestack-ui

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#208]
### The command ```npx gluestack-ui``` is bringing an ```undefined``` option:

<img width="892" alt="Screenshot 2023-03-30 at 00 26 39" src="https://user-images.githubusercontent.com/5796053/229566231-20f325e9-e9f0-4baf-a601-cf7a3062c0d4.png">

**Comment by ankit-tailor** [comment]
Hey @NandoMB, Thanks for reporting the issue. We will fix it.

**Comment by mayank-96** [comment]
Hey @NandoMB, This issue has been fixed with new version of `gluestack-ui@0.2.0`
