### ISSUE TITLE
Broken styled reference

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#209]
### When install the a component, not only Button, the reference of ```styled``` is broken...

<img width="1440" alt="Captura de Tela 2023-04-03 às 13 16 22" src="https://user-images.githubusercontent.com/5796053/229568350-51771825-f6a8-449c-9b06-863298bebe39.png">

```tsx
// Change from
import { styled } from '../../styled'; // Broken reference

// To
import { styled } from '@dank-style/react'; // Fixed reference
```

**Comment by mayank-96** [comment]
Hey @NandoMB,
You will need to re-initialise the project with latest version of gluestack-ui, which will add styled folder along with gluestack-ui-provider folder. This styled folder will provide pre-configured styled function with animation-plugin. So the local path written in some components for importing styled function is refereeing to this file.
