### ISSUE TITLE
styled.ts

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#210]
### The ```styled.ts``` is missing on ```npx gluestack-ui``` installation.

```ts
export { styled } from '@dank-style/react';
```

**Comment by mayank-96** [comment]
Hey @NandoMB, 
You will need to re-initialise the project with latest version of `gluestack-ui`, which will add `styled` folder along with `gluestack-ui-provider` folder. This styled folder will provide pre-configured `styled` function with `animation-plugin`. So the local path written in some components for importing `styled` function is refereeing to this file.

**Comment by Viraj-10** [comment]
Duplicate Issue #209
