### ISSUE TITLE
Actionsheet covers up screen behind it

### ISSUE THREAD

**Issue by ydlooming** [gluestack/gluestack-ui#2103]
### Description

When opening an Actionsheet, instead of fading the background, it covers it up completely. Select works fine in the same setup.

### Steps to reproduce

1. Create a screen to render custom button components (triggers for the Actionsheet)
2. Inside each button component, host an Actionsheet, similar to the example in the docks (fragment with two children - the button and the action sheet).
3. Have the state for open/closed inside the trigger component itself
4. Trigger the action sheet by pressing the button

Expected: the action sheet appears with a semi-transparent backdrop, still showing the content behind it.
Actual: there is some view behind the backdrop which covers up the screen behind it.

This same setup works fine with Select. Here is a screenshot, inspecting the backdrops of both components:
<img width="765" alt="Screenshot 2024-04-29 at 18 38 16" src="https://github.com/gluestack/gluestack-ui/assets/147612411/c98f4d5f-e342-4bcb-9fad-df11bcf90a29">

### gluestack-ui Version

1.1.22

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

### Additional Information

I also tried taking the Actionsheet out into the main screen that hosts the mapped buttons, but that didn't work either.

**Comment by rajat693** [comment]
please share the full contents of your `package.json` file, I need to check the versions of few packages.

**Comment by ydlooming** [comment]
Hello, @rajat693 . Here it is:
`{
  "name": "ampecoinstaller",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "andr": "react-native run-android",
    "ios": "npx react-native run-ios --simulator='iPhone 15 Pro'",
    "lint": "eslint .",
    "start": "npx react-native start --reset-cache",
    "test": "jest"
  },
  "dependencies": {
    "@gluestack-style/react": "^1.0.52",
    "@gluestack-ui/config": "^1.1.18",
    "@gluestack-ui/themed": "^1.1.22",
    "@hookform/resolvers": "^3.3.4",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@reduxjs/toolkit": "^2.2.3",
    "react": "18.2.0",
    "react-hook-form": "^7.51.3",
    "react-native": "0.73.6",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.30.1",
    "react-native-svg": "^13.4.0",
    "react-native-vector-icons": "^10.0.3",
    "react-redux": "^9.1.0",
    "yup": "^1.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/preset-typescript": "^7.24.1",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@tsconfig/react-native": "^3.0.5",
    "@types/react": "^18.2.6",
    "@types/react-native-vector-icons": "^6.4.18",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^6.21.0",
    "@typescript-eslint/parser": "^6.21.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-config-react": "^1.1.7",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jsonc": "^2.15.0",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.1.0",
    "eslint-plugin-unused-imports": "^3.1.0",
    "eslint-plugin-wdio": "^7.25.3",
    "jest": "^29.6.3",
    "metro-react-native-babel-preset": "^0.77.0",
    "prettier": "^3.2.5",
    "react-test-renderer": "18.2.0",
    "reactotron-react-native": "^5.1.6",
    "reactotron-redux": "^3.1.9",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
`

**Comment by ydlooming** [comment]
@rajat693 hey, Rajat! Is there anything else you'd need?

**Comment by zainkhas** [comment]
If you're using KeyboardAvoidingView, try adding pointerEvents="box-none".

**Comment by ydlooming** [comment]
> If you're using KeyboardAvoidingView, try adding pointerEvents="box-none".

thanks for you suggestion! Unfortunately that didn't work. Here's the structure of the host screen:

```
const Screen = () => {
  return (
    <SafeAreaView flex={1} bg="$white">
      <VStack flex={1} bg="$white" px={px} gap="$3" paddingTop={0} alignItems="center" justifyContent="center">
        {isLoading ? (
          <LoaderIcon />
        ) : (
          <KeyboardAvoidingView
            flex={1}
            behavior={isIos ? 'padding' : 'height'}
            keyboardVerticalOffset={isKeyboardVisible ? (isIos ? 100 : keyboardHeight) : undefined}
            pointerEvents="box-none"
          >
            <ScrollView flex={1}>
              <VStack gap="$1" pt="$5" pb="$8">
                {configurations
                  ? Object.values(configurations)?.map(field => {
                      return <ConfigurationInput key={field.name} field={field} chargePointId={chargePoint?.id} />;
                    })
                  : null}
                <GradientButton
                  startIcon={<SaveIcon color={white} />}
                  label={t('labels.save-changes')}
                  onPress={goToReboot}
                  disabled={isPending}
                />
              </VStack>
            </ScrollView>
          </KeyboardAvoidingView>
        )}
      </VStack>
    </SafeAreaView>
  );
};
```

The Actionsheet lives inside the ConfigurationInput component. Here's its code:
```
  return (
    <>
      <VStack>
        <Text ml="$2" variant="caption">
          {label}
        </Text>
        <Pressable onPress={() => setIsOpen(true)}>
          <HStack
            justifyContent="space-between"
            borderColor={getInputBorderColor({ error, isSuccess, isPending })}
            bg="$bluePrimary"
            borderRadius="$lg"
            borderWidth="$1"
            px="$3"
            h="$10"
            alignItems="center"
          >
            <Text variant="description" numberOfLines={1} maxWidth="85%">
              {selected.join(', ')}
            </Text>
            <Arrow direction={isOpen ? 'up' : 'down'} />
          </HStack>
        </Pressable>
        <InputMessage message={warning ?? error} type={warning ? 'warning' : 'error'} />
      </VStack>
      <Actionsheet bg="$bluePrimary" isOpen={isOpen} onClose={onClose} zIndex={-1}>
        <ActionsheetBackdrop />
        <ActionsheetContent pb="$12" maxHeight={screenHeight * 0.6}>
          <ActionsheetDragIndicatorWrapper>
            <ActionsheetDragIndicator />
          </ActionsheetDragIndicatorWrapper>
          <VStack gap="$3">
            <ActionsheetScrollView w="$full">
              <VStack gap="$2" w="$full" pt="$4">
                {items.map(({ value, label }) => {
                  const isSelected = selected.includes(value);

                  return (
                    <ActionsheetItem
                      key={value}
                      onPress={() => onItemPress(value)}
                      justifyContent="space-between"
                      bg="$bluePrimary"
                      borderRadius="$lg"
                    >
                      <ActionsheetItemText>{label}</ActionsheetItemText>
                      {/* Aria-label is necessary due to a typing bug in gluestack */}
                      <Checkbox
                        value={value}
                        isChecked={isSelected}
                        aria-label="checkbox"
                        onChange={() => onItemPress(value)}
                      >
                        <CheckboxIndicator mr="$2">
                          <CheckboxIcon as={Check} />
                        </CheckboxIndicator>
                      </Checkbox>
                    </ActionsheetItem>
                  );
                })}
              </VStack>
            </ActionsheetScrollView>
            <GradientButton onPress={handleSubmit} label={t('labels.save')} />
          </VStack>
        </ActionsheetContent>
      </Actionsheet>
    </>
  );
};
```

**Comment by ydlooming** [comment]
> Hi @ydlooming,
> 
> I tried to debug your issue, but it works fine for me. I'm attaching the GitHub repo below. If you still have issues, please share a GitHub repo or a minimal codebase that demonstrates the problem. repo - https://github.com/rajat693/rn-actionsheet-themed Thank you.

@rajat693 ok, so it runs out you shouldn't put a `backgroundColor` on the `StyleSheet` component. That was the issue. Thanks for your assistance!
