### ISSUE TITLE
AddIcon doesn't exist?

### ISSUE THREAD

**Issue by Bossburnz** [gluestack/gluestack-ui#2107]
### Description

I'm really new at using gluestack-ui, react native and expo. So the problem is that I can't seems to use the button compenent? 

### Steps to reproduce

![qemu-system-x86_64_dEDlo4mlUv](https://github.com/gluestack/gluestack-ui/assets/71087051/a163b6d3-31ba-4d7c-ae4f-e54e43d34efa)

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by surajahmed** [comment]
@Bossburnz Thanks for reporting this. We'll have a look.

**Comment by DaminiPandey** [comment]
Hey @Bossburnz, Could you please provide the code snippet of how you're using the button component? Also, it seems like the AddIcon is not being imported properly. Can you let me know from where you're importing it? It would be really helpful.

**Comment by DaminiPandey** [comment]
For reference you can use it like this:

```
 import {Icon, AddIcon} from '@gluestack-ui/themed';
 
 <Icon as={AddIcon} w="$4" h="$4" />
```
