### ISSUE TITLE
Unable to resolve "@legendapp/motion"

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#211]
#### When I updated my components this error started to be shown, even after I had delete the main component folder:

Unable to resolve "@legendapp/motion" from "gluestack/components/core/Actionsheet/styled-components/Content.tsx"

**Comment by Viraj-10** [comment]
Hey @NandoMB, 
- Delete actionsheet folder from your project. 
- run command
`npx gluestack-ui@latest add actionsheet`. 
PS:- This will remove all the existing styling of actionsheet. 
if you don't want to remove them simply add @legendapp/motion with your package manager.
