### ISSUE TITLE
Switch activeThumbColor type error

### ISSUE THREAD

**Issue by sdfricke** [gluestack/gluestack-ui#2110]
### Description

There is a type error when trying to use activeThumbColor prop with Switch component

### Steps to reproduce

When trying to utilize the Switch component from @gluestack-ui/themed I get a type error when using the activeThumbColor prop: Property 'activeThumbColor' does not exist on type 'IntrinsicAttributes & StyledComponentProps<StyleProp<ViewStyle>, unknown, SwitchProps, "Switch"> & RefAttributes<...> & IInterfaceSwitchProps'.  The prop works as expected however.  I converted onTrackColor prop to this prop based on the migration guide.  Thank you for any help you can provide.

### gluestack-ui Version

1.1.22

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by surajahmed** [comment]
@sdfricke Thanks for reporting this. We'll have a look.

**Comment by DaminiPandey** [comment]
Hey @sdfricke, this is an expected type error as "activeThumbColor" prop is currently not supported in react-native's [Switch](https://reactnative.dev/docs/switch) component.
This prop is only supported on [react-native-web](https://necolas.github.io/react-native-web/docs/switch/) and would work fine on the web.

**Comment by DaminiPandey** [comment]
Closing this issue for now, feel free to reopen it if you face any problems.

**Comment by sdfricke** [comment]
@DaminiPandey thank you for getting back to me.  I'm confused as to why that prop is recommended to use in the migration guide: https://geekyants.notion.site/Switch-96202d04cd3a45edb5a0c3fa1978d75e as a replacement for `onThumbColor` which was the prop in the native-base Switch
