### ISSUE TITLE
[Button] Spinner color is not propagating

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#212]
![spinner color not propagating](https://user-images.githubusercontent.com/5796053/229567707-66c45720-de14-4c5f-b290-0ac7ce1a5100.png)

**Comment by mayank-96** [comment]
Hi @NandoMB ,

This isn't a bug. In `Button.Spinner` component, `ActivityIndicator` component is passed from react-native, which has `color` as the reserved prop. So reserved props should be passed as per the following syntax.

```
   '_spinner': {
      props: {
        color: '$textLight50',
      },
      _dark: {
        props: { color: '$textDark50' },
      },
    },
```

**Comment by NandoMB** [comment]
Wow, my bad @mayank-96! I'll test it. Thanks for the attention.
