### ISSUE TITLE
Styled component type errors

### ISSUE THREAD

**Issue by jordmccord** [gluestack/gluestack-ui#2128]
### Description

Since upgrading to @gluestack-style/react 1.0.55 I'm now getting several type errors like: 
```
src/components/Alert/AlertCloseButton/styled-components/Icon.tsx:6:5 - error TS2353: Object literal may only specify known properties, and 'width' does not exist in type 'ITheme<unknown, ComponentType<RNProps & { as?: any; }>>'.  6     width: 16,       ~~~~~
``` 
and 
```
src/components/Alert/AlertLink/styled-components/Text.tsx:7:5 - error TS2353: Object literal may only specify known properties, and 'fontSize' does not exist in type 'ITheme<unknown, typeof Text>'.  7     fontSize: 16,       ~~~~~~
```
for example along with many others. All with simple valid style values

### Steps to reproduce

1. Add styles to a component for example:
```js
import { styled } from '@gluestack-ui/themed';
import { Text } from 'react-native';

const AlertLinkText = styled(
  Text,
  {
    fontSize: 16,
    lineHeight: 24,
    fontFamily: 'Work Sans',
    fontWeight: '600',
  },
  {
    componentName: 'AlertLinkText',
    descendantStyle: [],
    ancestorStyle: ['_text'],
  } 
);

export default AlertLinkText;
```
2. Run `tsc` to compile code

### gluestack-ui Version

1.0.55

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by jordmccord** [comment]
@ankit-tailor I think it may have been the recent fix https://github.com/gluestack/gluestack-ui/commit/ec89e51e640c86f9ae8789ab6e657be5215ad047

**Comment by ankit-tailor** [comment]
It's fixed now. Please upgrade `@gluestack-style/react` and `@gluestack-ui/themed`.

**Comment by jordmccord** [comment]
Nice one thanks again @ankit-tailor
