### ISSUE TITLE
Compatilibity with Expo SDK 51

### ISSUE THREAD

**Issue by kralion** [gluestack/gluestack-ui#2142]
### Description

Compatility errors when upgrading to the new version of expo sdk

### Steps to reproduce

1. Create a project with npm create gluestack
2. Select expo router v3 
3. upgrade to the sdk because that's a requirement for emulating on Expo Go App
4. npm install expo@latest
5. npx expo install --fix
6. See the errors

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

I have a project built with nativebase, and i am having the same issue, so i tried to upgrade the ui library to gluestack, but there is also compatibility errors, because of the new sdk by expo.

**Comment by vzla0094** [comment]
Where are you upgrading from? This issue might be related: https://github.com/gluestack/gluestack-ui/issues/1669

**Comment by pierrebiver** [comment]
I have the same problem and I think its due to the react native svg dependency:
<img width="937" alt="Screenshot 2024-05-11 at 12 02 40" src="https://github.com/gluestack/gluestack-ui/assets/13810999/218b13ee-d16f-45e0-943f-198ce312bc53">

**Comment by kralion** [comment]
> What version are you upgrading from? This issue might be related: #1669

Upgrading from the SDK 49

**Comment by myleftshoe** [comment]
Yep, I get compat issues too when trying to add gluestack to an existing expo project @51.0.9

![image](https://github.com/gluestack/gluestack-ui/assets/32611040/3e919f27-54f9-4bda-85dd-383064e3b542)
 
I tried  upgrading react to 18.3.1 but that caused other issues with expo

**Comment by sawankumar1012** [comment]
i have the same issue ,anyone found resolution to this ?
<img width="1073" alt="Screenshot 2024-07-15 at 8 24 53 PM" src="https://github.com/user-attachments/assets/5cb7d622-0283-48ba-b49e-460dba827433">
