### ISSUE TITLE
Just question

### ISSUE THREAD

**Issue by andrconstruction** [gluestack/gluestack-ui#2152]
### Description

What is better, use sx props or special props

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.56

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

I mean 
<Text color="$white" $dark-color="$black" />
OR
<Text sx={{ __dark: 'black' ...etc }}/>

**Comment by ankit-tailor** [comment]
Hey @andrconstruction, Utility props are internally converted to SX prop only. But if you are not using babel plugin it may add runtime overhead for this conversion.
