### ISSUE TITLE
if the text too long, the toast will overflow.

### ISSUE THREAD

**Issue by xiaohuantech** [gluestack/gluestack-ui#2159]
### Description

How to make it wrap automatically

### CodeSandbox/Snack link

https://gluestack.io/ui/docs/components/feedback/toast

### Steps to reproduce

it's can be reprodced by official documents.
Link: https://gluestack.io/ui/docs/components/feedback/toast
<img width="454" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/165459847/1fa8aa5a-6011-4d80-a927-7d124ecd6108">

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @xiaohuantech, Thanks for reporting this issue. It's layout issue in example not a toast. We have fixed it. It will be live soon.
