### ISSUE TITLE
Nativewind TextInput and TextArea does not apply custom colors defined from config 

### ISSUE THREAD

**Issue by nathan-charles** [gluestack/gluestack-ui#2176]
### Description

TextInput and Texarea does not apply custom colors from nativewind defined in config

### CodeSandbox/Snack link

https://github.com/gluestack/ui-example-nativewind

### gluestack-ui Version

nativewind

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

<img width="721" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/16949322/cc2f9351-725b-4e85-8336-3e4141e5334c">

Issue is re producable even in example nativewind demo (look at search text input in dark mode it's ignoring the `text-typography-900`)

![image](https://github.com/gluestack/gluestack-ui/assets/16949322/1074329f-cc4c-424c-ac8e-e1375629e2d7)

**Comment by rajat693** [comment]
Hi @Nathan-Charles,
Thanks for reporting this issue. We are working on it and will inform you once it is resolved.
Thank you.

**Comment by rajat693** [comment]
This issue is now resolved, so I am closing it.
