### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by KStockton** [gluestack/gluestack-ui#2180]
### Description

There is a ; in the jsx code that is confusing.

### CodeSandbox/Snack link

If you go to the Documentation for GluestackUIStyledProvider its in the box

### Steps to reproduce

1. Search GluestackUiStyledProvider in the docs
2. See error.
![Screenshot 2024-05-22 at 5 07 44 PM](https://github.com/gluestack/gluestack-ui/assets/34406483/cca4332a-c48f-4061-8592-fb416755e900)

### gluestack-ui Version

Docs

### Platform

- [X] Expo
- [X] React Native CLI
- [X] Next
- [X] Web
- [X] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @KStockton, Thanks for reporting this issue. We will have a look.

**Comment by cnt000paramount** [comment]
I found another error in the same part of the documentation: 

<img width="987" alt="Screenshot 2024-07-15 at 12 05 27" src="https://github.com/user-attachments/assets/71cf9499-2642-4e0c-8c3d-d62e90ebfb5f">

I created this PR to fix that: https://github.com/gluestack/gluestack-ui/pull/2306
