### ISSUE TITLE
Modal content in React native is not displayed properly

### ISSUE THREAD

**Issue by showtan001** [gluestack/gluestack-ui#2222]
### Description

The ios and Android simulators are normal, but the Android real machine is not normal.

### CodeSandbox/Snack link

https://snack.expo.dev

### Steps to reproduce

Because after using <GluestackUIProvider config={config}>Android packaging, the content of the React native Modal component is not displayed properly, and the TouchableOpacity component cannot be clicked. This is the case with any code. Remove <GluestackUIProvider config={config}> and it will be normal. Therefore, the "CodeSandbox/Snack link" above is of no reference significance.

### gluestack-ui Version

1.1.26

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

Normal screenshot: 
![image](https://github.com/gluestack/gluestack-ui/assets/32892347/4e22bd2e-dba3-4464-af16-33dbb626581d)

Android packaged and run screenshots:
![4021717667549_ pic](https://github.com/gluestack/gluestack-ui/assets/32892347/73f5f78e-5360-4b41-8d66-078d723b0fa6)

code:
![image](https://github.com/gluestack/gluestack-ui/assets/32892347/a786e7b6-0229-4ec2-8c7b-ef3be35f0e61)

**Comment by Viraj-10** [comment]
Hey @showtan001, Please provide github repo link with issue reproduction.

**Comment by showtan001** [comment]
> Hey @showtan001, Please provide github repo link with issue reproduction.

This problem only occurs on Android after packaging, and there is no problem with the test environment
