### ISSUE TITLE
`FormControl` _dark mode styles not applied on iOS or Android

### ISSUE THREAD

**Issue by jordmccord** [gluestack/gluestack-ui#2231]
### Description

When applying `:disabled` styles inside the `_dark` property the styles are not applied for a `FormControl` and it's descendants on iOS or Android.

### CodeSandbox/Snack link

/

### Steps to reproduce

1. Update a `FormControl` `_dark` prop
2. See nothing happen

### gluestack-ui Version

"@gluestack-style/react": "1.0.56",   "@gluestack-ui/themed": "1.1.29"

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by Viraj-10** [comment]
Hey @jordmccord, Please provide small reproduction of the bug.

**Comment by jordmccord** [comment]
I couldn't provide small reproduction as all is working as expected in simple example https://snack.expo.dev/@utilitywarehouse/broken-disabled

The issue was resolved in my codebase by removing child styles declared in the theme 'FormControlLabel` `createStyle` method and declaring them in the parent `FormControl` `createStyle` method.
