### ISSUE TITLE
How to effectively use typed forwardRefs

### ISSUE THREAD

**Issue by marcosdourado** [gluestack/gluestack-ui#2246]
### Description

It may seem like a simple question, but I started building a component and got typing errors when trying to use forwardRef on a Button. The approach I'm used to didn't work, I followed the examples at [React Typescript Cheatsheet]( https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/forward_and_create_ref) and I wasn't successful either.

Would there be an example available?

### Problem Statement

It may seem like a simple question, but I started building a component and got typing errors when trying to use forwardRef on a Button. The approach I'm used to didn't work, I followed the examples at [React Typescript Cheatsheet]( https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/forward_and_create_ref) and I wasn't successful either.

Would there be an example available?

### Proposed Solution or API

I think it is a common demand and it would be interesting to have an example in the documentation.

**Comment by ludwighen** [comment]
I have the same issue with ref types just not working reliably at all. It feels like either a big oversight or I am doing something wrong.

Just something like this won't work:

```
const viewRef = useRef<View>();

return (
<View ref={viewRef} />
)
```

Getting type MutabaleRefObject<View> is not assignable to LegacyRef<typeof View>.

But changing to useRef<typeof View> or ComponentProps<typeof View> doesn't work either.
How are ref types supposed to be done? Cannot find anything in the documentation either.

**Comment by Viraj-10** [comment]
Hey @marcosdourado @ludwighen, please upgrade to latest version and try following code. 

```js
import { Button } from "@gluestack-ui/themed";

const ButtonWithForwardRef = React.forwardRef<
  React.ComponentRef<typeof Button>,
  React.ComponentPropsWithoutRef<typeof Button>
>((props, ref) => {
  return <Button ref={ref} {...props} />;
});

```
