### ISSUE TITLE
iOS EAS Build fails (Android is OK) while using gluestack-ui v2 with EXPO 51

### ISSUE THREAD

**Issue by tkhwang** [gluestack/gluestack-ui#2332]
### Description

iOS EAS-BUILD fails after using gluestack-ui 

### CodeSandbox/Snack link

GItHub https://github.com/tkhwang/expo-gluestack-ui-ios-eas-build-error

### Steps to reproduce

* create expo app using `create-expo-app`
* init gluestack-ui v2
* add gluestack-ui components : `VStack`, `HStack`, `Text`

common libraries

```
    "expo": "~51.0.21",
    "react-native": "0.74.3",
```

 `gluestack-ui` libraries

```
    "@gluestack-ui/nativewind-utils": "^1.0.21",
    "@gluestack-ui/overlay": "^0.1.15",
    "@gluestack-ui/toast": "^1.0.7",
```

* `eas-build` iOS fails and Android builds well.

## iOS EAS BUILD: Error

Error occurs in `Run fastlane` step

```
...
› Packaging expo-eas-client Pods/EASClient » libEASClient.a
› Executing expo-eas-client Pods/EASClient » Copy generated compatibility header
› Executing expo-updates Pods/EXUpdates » [CP-User] Generate updates resources for expo-updates

❌  error: global.css: A jest worker process (pid=6452) was terminated by another process: signal=SIGTERM, exitCode=null. Operating system logs may contain more information on why this occurred.



❌ Metro encountered an error:
global.css: A jest worker process (pid=6452) was terminated by another process: signal=SIGTERM, exitCode=null. Operating system logs may contain more information on why this occurred.
Learn more: https://docs.expo.dev/build-reference/troubleshooting
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution [CP-User]\ Generate\ updates\ resources\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/tkhwangwhattodo-dmyphtzpxtrumyaygvpyoswkfeln/Build/Intermediates.noindex/ArchiveIntermediates/tkhwangwhattodo/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E0001C260.sh (in target 'EXUpdates' from project 'Pods')
▸ (1 failure)
** ARCHIVE FAILED **
```

## Android EAS BUILD : OK

It builds well.

### gluestack-ui Version

v2

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

Full log attached:  
[Xcode build log 2d6d45c1.log](https://github.com/user-attachments/files/16321127/Xcode.build.log.2d6d45c1.log)

**Comment by Viraj-10** [comment]
Hey @tkhwang, Thanks for reporting this issue. We will have a look.

**Comment by evelant** [comment]
Also running into this. I think it's something with nativewind but I haven't been able to figure out a workaround yet.

**Comment by mjcarnaje** [comment]
+1, I've encountered it too just now, when building for ios development build

**Comment by evelant** [comment]
Also facing this. It's difficult to debug since the EAS output offers no useful error message. I've tried a lot of variations on metro config, the import, and pre-building the css without luck.

**Comment by evelant** [comment]
OK I figured it out @tkhwang it's probably not a gluestack problem. Node is running out of memory. Add an environment variable in eas.json to increase node heap size and it will no longer crash ex: `"NODE_OPTIONS": "--max-old-space-size=4096",
`

**Comment by tkhwang** [comment]
@evelant  Oh. I also observed with increasing heap size, the build error has gone. Thanks.

```json
    "production": {
      "ios": {
        "image": "latest",
        "resourceClass": "m-medium"
      },
      "channel": "production",
      "env": { 
        "NODE_OPTIONS": "--max-old-space-size=4096"
      }
    }
```
