### ISSUE TITLE
Dependency conflict @legendapp/motion - nativewind@2.0.0 and  gluestack-ui nativewind@4.0.36

### ISSUE THREAD

**Issue by SimonYS001** [gluestack/gluestack-ui#2337]
### Description

dependency conflict @legendapp/motion - nativewind@2.0.0 and  gluestack-ui nativewind@4.0.36

### CodeSandbox/Snack link

https://snack.expo.dev/

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

It looks like @legendapp is no longer updated, is it possible to replace it with another library?

**Comment by Viraj-10** [comment]
Hey @SimonYS001, Please use `--legacy-peer-deps` flags while installing. Thanks for reporting this we will add it to our cli.

**Comment by TimotiusAnrez** [comment]
my team also got simillar issue, although we can use npm --legacy-peer-deps on our local machine, but we are not able to build it on EAS.

**Comment by Viraj-10** [comment]
Hey @TimotiusAnrez, create `.npmrc` file inside your project and write `legacy-peer-deps=true`. We are updating our cli to do the same.

**Comment by rajat693** [comment]
The issue has been resolved, so I am closing it for now. If you have any further questions or if the issue persists, please feel free to reopen it. We are here to help!
Thank You
