### ISSUE TITLE
Slider 轨道SliderTrack 问题

### ISSUE THREAD

**Issue by 7chenys** [gluestack/gluestack-ui#2338]
### Description

SliderTrack 在SliderThumb不可见的情况下，最左侧多出一段距离

Translation :- SliderTrack adds some distance to the left when SliderThumb is invisible.

### CodeSandbox/Snack link

null

### Steps to reproduce

1. 将SliderThumb 背景颜色设置为透明
2. 发现问题

### gluestack-ui Version

1.1.29

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by sra1kumar-NULL** [comment]
hey @7chenys  I'm unable to reproduce the above issue you've reported please add a working repo here.

**Comment by sra1kumar-NULL** [comment]
Hey @7chenys , we are closing this issue for now, please feel free to reopen the issue if you are still facing it/ having any queries about it.
