### ISSUE TITLE
Migration guide link on website broken

### ISSUE THREAD

**Issue by danharten-sovtech** [gluestack/gluestack-ui#2344]
### Description

404 on the migration guide

### CodeSandbox/Snack link

https://gluestack.io/ui/docs/migration/native-base-to-gluestack-ui

### Steps to reproduce

1. Go to (https://gluestack.io/ui/docs/migration/native-base-to-gluestack-ui)
2. See 404 message

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Other Platform

N/A

### Additional Information

N/A

**Comment by eyupdogan** [comment]
++

**Comment by ankit-tailor** [comment]
Thanks for reporting the issue. It's fixed now!
