### ISSUE TITLE
Gluestack v2 Modal has dependency issue

### ISSUE THREAD

**Issue by jeffbmartinez** [gluestack/gluestack-ui#2350]
### Description

Modal component won't install, dependency @legendapp/motion is missing, and has a dependency problem when trying to install it manually with npm

### CodeSandbox/Snack link

https://github.com/jeffbmartinez/gluestackmodalproblem/blob/main/App.js

### Steps to reproduce

1. Create new expo app: `npx create-expo-app gluestackmodalproblem --template blank`
1. Add gluestack: `npx gluestack-ui init` (default "yes" for prompts)
2. Add modal: `npx gluestack-ui add modal`
3. Add code to use '<Modal>' in the project
4. See error (`Unable to resolve "@legendapp/motion" from "components/ui/modal/index.tsx"`)

Extra notes:
- Trying to install `@legendapp/motion` with npm fails with peer dependency
- Installing `@legendapp/motion` with npm option `--legacy-peer-deps` seems to work for the installation, but I was seeing runtime issues when actually using the modal down the line.

### gluestack-ui Version

v2

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by vaibhk20** [comment]
Hi @jeffbmartinez, thank you for reporting the issue we are looking into it.

**Comment by rajat693** [comment]
The issue has been resolved, so I am closing it for now. If you have any further questions or if the issue persists, please feel free to reopen it. We are here to help!
Thank You

**Comment by rajat693** [comment]
The issue has been resolved, so I am closing it for now. If you have any further questions or if the issue persists, please feel free to reopen it. We are here to help!
Thank You

**Comment by SHAGGYER** [comment]
its shit, still doesnt work

**Comment by Viraj-10** [comment]
Hey @SHAGGYER, Can you please specify issue and if possible please provide reproducible environment.

**Comment by SHAGGYER** [comment]
@Viraj-10 no, i dont care to. using plain components. you should know that expo is at a new version now and that there is nextjs like routing now. i tried to install everything without specifying versions, which is a hacky solution and everything should work outside the box. which it doesnt. so no

**Comment by Viraj-10** [comment]
@SHAGGYER, It's working for us and lots of other users. 
### why specific version?
version of npm (v7), by default, npm install will fail when it encounters conflicting peerDependencies. you can read more [here](https://github.blog/news-insights/product-news/npm-7-is-now-generally-available/#peer-dependencies). 
passing `--legacy-peer-deps` ignore all peerDependencies when installing, in the style of npm version 4 through version 6.
