### ISSUE TITLE
MenuItem doesn't support TestID and onPress

### ISSUE THREAD

**Issue by Snotax** [gluestack/gluestack-ui#2353]
### Description

Props must be supported

### CodeSandbox/Snack link

-

### Steps to reproduce

1. setup Gluestack v2
2. Try to use Menu
3. Props missing...

### gluestack-ui Version

    "@gluestack-ui/menu": "^0.2.34",

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by Viraj-10** [comment]
Hey @Snotax, Thanks for reporting the issue. We have fixed it in [commit](https://github.com/gluestack/gluestack-ui/commit/ac2e79dc106ced2c513c9fad82ee99e9a096b253) 
run `npx gluestack-ui add menu` to update menu component.
