### ISSUE TITLE
Support installing dependencies with Bun when initializing

### ISSUE THREAD

**Issue by sujang958** [gluestack/gluestack-ui#2384]
### Description

![image](https://github.com/user-attachments/assets/a5f3ceb5-499f-4a26-a58e-b39fc9ce90f4)
![image](https://github.com/user-attachments/assets/596f16e5-a8c9-4cef-a235-2ed64076754c)

When a project is based on Bun, Gluestack CLI doesn't detect the lock file.

### Problem Statement

NPM, Yarn, and Pnpm are much slower than Bun and more and more people are using Bun.

### Proposed Solution or API

Add codes that detect Bun's lockfile.

**Comment by vaibhk20** [comment]
Hi @sujang958 , thank you for raising the issue. Currently, the gluestack-ui CLI doesn't have support for bun, but we have it in our roadmap.

**Comment by vaibhk20** [comment]
Support for Bun has been added in the latest version of the CLI. This resolves the issue.
