### ISSUE TITLE
Select: snapPoints on Android make the `SelectPortal` have extra bottom margin

### ISSUE THREAD

**Issue by aaronatbissell** [gluestack/gluestack-ui#2388]
### Description

When using `snapPoints` on the `SelectPortal`, it adds too much bottom margin

### CodeSandbox/Snack link

https://github.com/aaronatbissell/gluestack-issue-repro

### Steps to reproduce

1. Clone https://github.com/aaronatbissell/gluestack-issue-repro
2. npm install
3. npm run android
4. Click on the select box and see the added bottom margin (like in this screenshot):

<img src="https://github.com/user-attachments/assets/11672b6c-c181-4a6d-a446-49a8ecf1dad0" width=300>

### gluestack-ui Version

@gluestack-ui/select: 0.1.28

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by aaronatbissell** [comment]
For comparison, this is what it looks like on iOS:

<img src="https://github.com/user-attachments/assets/a3c90f58-50b0-4923-994c-66d50ce36832" width=300>

**Comment by rajat693** [comment]
please update the version of `@gluestack-ui/actionsheet`.
thank you
