### ISSUE TITLE
Select (native): Lists of many items make the portal extend all the way to the top

### ISSUE THREAD

**Issue by aaronatbissell** [gluestack/gluestack-ui#2389]
### Description

When you have a list of many items, the `SelectPortal` (without using snapPoints) goes all the way to the top, which makes dragging the `DragIndicator` impossible because it's under the notification shade

### CodeSandbox/Snack link

https://github.com/aaronatbissell/gluestack-issue-repro

### Steps to reproduce

1. Clone https://github.com/aaronatbissell/gluestack-issue-repro
2. npm install
3. npm run ios
4. Open the select and then try to dismiss the `SelectPortal` without selecting an option.

<img src="https://github.com/user-attachments/assets/55f0e9de-cb77-43b6-af79-69b48e028c51" width=300>

This happens on both iOS and Android.

### gluestack-ui Version

@gluestack-ui/select: 0.1.28

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

I would suggesting adding a maximum height to the portal (maybe something like 80% screen height or something)

**Comment by rajat693** [comment]
"Hi @aaronatbissell, If you are not providing `snapPoints` to the `SelectPortal`, you can set the **maxHeight** property on the `SelectContent` to control the height.

**Comment by aaronatbissell** [comment]
Thanks! That works!
