### ISSUE TITLE
Input border - certain colors don't work on Native

### ISSUE THREAD

**Issue by aaronatbissell** [gluestack/gluestack-ui#2409]
### Description

When using an `Input` field and trying to set the border color, only some border colors work.
This appears to be a problem on both `data-[focused:true]` as well as just setting the border color

### CodeSandbox/Snack link

https://github.com/aaronatbissell/gluestack-issue-repro

### Steps to reproduce

1. Go to https://github.com/aaronatbissell/gluestack-issue-repro
2. Clone the repo
3. npm install
4. npm run ios

❌ The first input box border should be yellow when in focus (it's black) - using a custom color I added to the config `color-custom-test`
✅ The second input box border should be orange when in focus (it's orange) - using a predefined `color-tertiary-500`
❌ The third input box border should be red when in focus (it's black) - using a predefined `color-indicator-error`

<img src="https://github.com/user-attachments/assets/c86a898c-9fb1-499c-a5ea-bcdba8fdd420" width=300>

<img src="https://github.com/user-attachments/assets/4e8212b9-6428-4e5f-b407-903c273949cd" width=300>

<img src="https://github.com/user-attachments/assets/6798a73c-4fac-4a7f-9fec-3ed952c49445" width=300>

Just setting the base border colors:
<img src="https://github.com/user-attachments/assets/a30ea94b-a825-4aac-9e16-56b9e194c846" width=300>

### gluestack-ui Version

@gluestack-ui/input: 0.1.31

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by aaronatbissell** [comment]
Just opened this back up today and it looks like the borders are working as I would expect now:

<img src="https://github.com/user-attachments/assets/2609d881-7afe-420a-bc17-c499ce88d41c" width=300>

**Comment by aaronatbissell** [comment]
This still isn't working with our debug builds - it looks like it works when running with metro after it initially loads. I'm having a tough time reproducing it 100% of the time, but it's definitely not working for actual builds on Native

**Comment by rajat693** [comment]
hi @aaronatbissell, If you want to use **dynamic colors** with **state-based styling** (using the data-* attribute), you'll need to define the color values in the `safelist` section of the `tailwind.config.js` file for now. We are working on this fix and will update you once done.
thank you

**Comment by aaronatbissell** [comment]
Thank you @rajat693 - this worked! Looks like a couple pre-defined colors (`indicator` and `status`) aren't includes in the default `safelist` and I had to also include our own custom colors.

Thanks again!!
