### ISSUE TITLE
Actionsheet v1 - scroll lock should not kick in if backdrop is not rendered

### ISSUE THREAD

**Issue by FezVrasta** [gluestack/gluestack-ui#2450]
### Description

When I use the Actionsheet component without a backdrop I can't scroll the page. If I don't use a backdrop I would expect the background scroll to work.

### CodeSandbox/Snack link

n/a

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

@gluestack-ui/actionsheet: 0.2.44

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by wandson88** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by rajat693** [comment]
hi @FezVrasta, thanks for reporting the issue, we will have a look.

**Comment by rajat693** [comment]
hi @FezVrasta, Thank you for your suggestion! `ActionSheets` typically freeze background content to maintain focus. For scrollable background content, we recommend using our customizable `Popover` component instead.

**Comment by FezVrasta** [comment]
Thanks but they do look quite different and don't provide the same interactions (like being resizable).

Native action sheet on ios has an option to allow for background interaction and it's widely used, see Apple Maps, Flighty, and more

**Comment by rajat693** [comment]
Thanks for your suggestion @FezVrasta, we'll review it and plan to update this feature in our actionsheet in the future.

**Comment by FezVrasta** [comment]
@rajat693 I sent a PR to address this issue if you would like to review it.
