### ISSUE TITLE
Button component breaks cliend-side navigation when used in Next.js' Link component

### ISSUE THREAD

**Issue by ruckerzerg** [gluestack/gluestack-ui#2452]
### Description

Button component breaks cliend-side navigation when used in Next.js' Link component

### gluestack-ui Version

2

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Additional Information

On click it triggers a full page reload instead of handling it on the client side.

**Comment by vaibhk20** [comment]
Hey @ruckerzerg , thank you for reporting the issue. We'll look into it and get back to you soon!

**Comment by sra1kumar-NULL** [comment]
hey @ruckerzerg @philippbosch @RobertSasak , you should be wraping link with the button ( swap parent with children) , then it will not break in the client side ie..,
```  
       <Button size="md" variant="solid" action="primary">
            <Link href="/about">Go to about client ▶</Link>
        </Button>
```
Closing this issue for now. Please feel free to open this issue again if had queries in this same context.
