### ISSUE TITLE
Component shadows not rendering

### ISSUE THREAD

**Issue by natkinson1** [gluestack/gluestack-ui#2469]
### Description

Shadows not rendering onto components. Referring to this url: https://gluestack.io/ui/docs/home/theme-configuration/default-tokens#shadows

### CodeSandbox/Snack link

https://snack.expo.dev/j05o1SrDjdwS_YYnaV0pU

### Steps to reproduce

For example in this example:

```       
<Box className='flex-row justify-between items-center p-5 mb-2 mt-2 shadow-soft-1'>
<HStack className='items-center'>
<Avatar size="sm" className='mr-2'>
<AvatarImage source={require('../assets/images/profile.png')} />
</Avatar>
<Heading size='md'>{data.user}</Heading>
</HStack>
<Text>Review Stars</Text>
</Box>
```

Here is my tailwind.config.js file

```
boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
        '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
      },
```

I am using Expo~51.0.28, emulating on Android using Expo Go.

Is this a bug or am I misusing how shadows are meant to be used.

Thanks in advance!

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by rajat693** [comment]
`NativeWind v4` doesn't currently support `Expo Snack`, so you won't be able to use `Gluestack v2` in `Expo Snack` at the moment. However, it works properly in a regular `Expo` project.

**Comment by natkinson1** [comment]
Hey, thanks for your reply.

I was using Expo snack to show an example of the code I am developing while using "shadow-soft-1" as a parameter in the className.

I am using a regular Expo project when developing. Do you have a usage example which works on your side?

**Comment by acodexm** [comment]
does anyone got any solution to this? it seems like shadows does not work without `elevation-` and any shadow-soft|hard-x props from gluestack does not seems to affect the shape of the shadows, or they break them altogether. can someone point to a working project that uses nativewind and shadows with expo?

**Comment by Maltronic** [comment]
> does anyone got any solution to this? it seems like shadows does not work without `elevation-` and any shadow-soft|hard-x props from gluestack does not seems to affect the shape of the shadows, or they break them altogether. can someone point to a working project that uses nativewind and shadows with expo?

I have this problem with shadows too, the only solution I've found is to do some platform specific selection everywhere, e.g. ``className{`${Platform.OS === "android" ? "elevation-lg" : "shadow-hard-1"} p-2...`}``
