### ISSUE TITLE
Using the Grid component in react-navigation/bottom-tabs triggers 

### ISSUE THREAD

**Issue by chenerge** [gluestack/gluestack-ui#2479]
### Description

the warning: "Error: Text strings must be rendered within a <Text> component."

### CodeSandbox/Snack link

.

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by chenerge** [comment]
import React, {useState} from 'react';

import GuestLayout from '@/layouts/GuestLayout';
import {useNavigation} from '@react-navigation/native';
import {
  Center,
  Box,
  Text,
  Card,
  Heading,
  Avatar,
  HStack,
  Icon,
  VStack,
  Button,
  ButtonIcon,
  GridItem,
  Grid,
} from '@/components/ui';
import {EditIcon, User} from 'lucide-react-native';
import ButtonList from './component/ButtonList';

export const HomeScreen = () => {
  return (
    <GuestLayout>
      <Center>
        <Box className="w-full">
          <VStack space="md">
            <Card size="lg" variant="outline" className="w-full">
              <HStack space="md">
                <Avatar className="rounded-full bg-secondary-50">
                  <Icon as={User} size="lg" />
                </Avatar>
                <VStack>
                  <Heading size="sm">Kevin James</Heading>
                  <Text size="sm">Web Designer</Text>
                </VStack>
              </HStack>
            </Card>

            <Grid
              className="gap-y-2 gap-x-4"
              _extra={{
                className: 'grid-cols-6',
              }}>
              <GridItem
                className="bg-background-50 p-4 rounded-md text-center"
                _extra={{
                  className: 'col-span-6 md:col-span-3 lg:col-span-2',
                }}>
                <Text className="text-sm">01</Text>
              </GridItem>
              <GridItem
                className="bg-background-50 p-4 rounded-md text-center"
                _extra={{
                  className: 'col-span-6 md:col-span-3 lg:col-span-2',
                }}>
                <Text className="text-sm">02</Text>
              </GridItem>
              <GridItem
                className="bg-background-50 p-4 rounded-md text-center"
                _extra={{
                  className: 'col-span-6 md:col-span-3 lg:col-span-2',
                }}>
                <Text className="text-sm">03</Text>
              </GridItem>
              <GridItem
                className="bg-background-50 p-4 rounded-md text-center"
                _extra={{
                  className: 'col-span-6 md:col-span-3 lg:col-span-2',
                }}>
                <Text className="text-sm">04</Text>
              </GridItem>
              <GridItem
                className="bg-background-50 p-4 rounded-md text-center"
                _extra={{
                  className: 'col-span-6 md:col-span-3 lg:col-span-2',
                }}>
                <Text className="text-sm">05</Text>
              </GridItem>
              <GridItem
                className="bg-background-50 p-4 rounded-md text-center"
                _extra={{
                  className: 'col-span-6 md:col-span-3 lg:col-span-2',
                }}>
                <Text className="text-sm">06</Text>
              </GridItem>
            </Grid>
          </VStack>
        </Box>
      </Center>
    </GuestLayout>
  );
};

**Comment by Tshabzz** [comment]
I'm Having exactly the same error

**Comment by Viraj-10** [comment]
Hey @Tshabzz @chenerge, Could you please share a repository with a minimal reproduction of the issue?

**Comment by chenerge** [comment]
No repository uploaded

> 嘿，您能否分享一个对问题进行最低限度复制的存储库？
