### ISSUE TITLE
gluestack-ui-starter-kits getting stuck at compilation

### ISSUE THREAD

**Issue by raky291** [gluestack/gluestack-ui#2493]
### Description

getting stuck at compilation

### CodeSandbox/Snack link

https://github.com/gluestack/gluestack-ui-starter-kits

### Steps to reproduce

I tried creating an expo + gluestack v2 project but it always gets stuck at X%.
I used the following commands:
```
npx create-expo-app@latest
npx gluestack-ui init
```

and then I tried to run an already configured project and I have the same problem.

1. I downloaded the repo: https://github.com/gluestack/gluestack-ui-starter-kits
2. run: cd expo-app
3. run: yarn or npm i
4. run: yarn run web or npm run web
5. getting stuck at X%

![Captura de pantalla 2024-09-26 222721](https://github.com/user-attachments/assets/989d9e0f-a5cc-4bac-813e-d6fac5925242)

### gluestack-ui Version

not sure

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by vaibhk20** [comment]
Hi @raky291 , have you tried running a bare Expo project or a project with just NativeWind installed? Did you face any similar issues while trying to run those configurations? This could help isolate the problem.

**Comment by raky291** [comment]
Yes, the issue was the `nativewind` library, I had to install the latest version to solve the issue, thanks.

`"nativewind": "4.1.10",`
