### ISSUE TITLE
Popover not working on mobile

### ISSUE THREAD

**Issue by boussaidev** [gluestack/gluestack-ui#2497]
### Description

Popover component not working as expected on mobile

### CodeSandbox/Snack link

https://gluestack.io/ui/docs/components/popover

### Steps to reproduce

use https://gluestack.io/ui/docs/components/popover component on mobile
but it's not working

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by rajat693** [comment]
hi @boussaidev, could you please specify what exactly the problem you are facing in using Popover component in mobile.

**Comment by JavanPoirier** [comment]
+1 here, on mobile the backdrop appears with no content. I also noticed a regression with toasts too. All on V1, separate issue I know, toasts are throwing a native error.

**Comment by GiuSantos0** [comment]
+1 here. Popover Works on iOS, but doesn't work on Android.

**Comment by rajat693** [comment]
please install the latest version of `@gluestack-ui/popover`.
