### ISSUE TITLE
AlertDialog is not shown in a modal screen

### ISSUE THREAD

**Issue by zhouhao27** [gluestack/gluestack-ui#2498]
### Description

AlertDialog is not shown in a modal screen

### CodeSandbox/Snack link

https://github.com/zhouhao27/alertDialog-demo

### Steps to reproduce

1. Run my application
2. Click on 'Open a modal view' 
3. No AlertDialog is shown

![Simulator Screenshot - iPhone 15 Pro - 2024-10-03 at 15 07 42](https://github.com/user-attachments/assets/ffbfb771-2dd8-4521-b42b-f49748df7fff)

To make it work:
1. Goto `_layout.tsx` at root.
2. Remove `presentation: modal`
3. Run the app again
5. Click on 'Open a modal view' 

![Simulator Screenshot - iPhone 15 Pro - 2024-10-03 at 15 07 22](https://github.com/user-attachments/assets/fbea7a19-2909-4728-809c-6a627bcf789c)

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by sra1kumar-NULL** [comment]
Hey @zhouhao27 , Thanks for reporting we've updated the alert Dialog component, please update to the latest version of alert dialog that should fix this issue.
Closing this issue for now. Please feel free to reopen this issue again if the issues persists.
