### ISSUE TITLE
Add SECURITY.md file

### ISSUE THREAD

**Issue by bananabr** [gluestack/gluestack-ui#2507]
### Description

The repository doesn't contain a SECURITY.md file with contact instructions to report security vulnerabilities.

### CodeSandbox/Snack link

N/A

### Steps to reproduce

Please add a SECURITY.md file or provide instructions for a security vulnerability to be reported.

Thank you,

### gluestack-ui Version

latest

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @bananabr, `gluestack-ui` is a UI component library that depends on numerous npm packages, each of which may have their own dependencies. To check for security vulnerabilities and related issues in your project, you can run `npm audit` in your repository. This will give you a detailed report of any identified vulnerabilities.

**Comment by bananabr** [comment]
Hey @Viraj-10,

Sorry if I didn't make myself clear enough. I have something to report to the gluestack-ui project maintainers. Best practice dictates that security contacts be made public through a SECURITY.md file to facilitate this sort of sensitive communication.
