### ISSUE TITLE
How to trigger Button active style onPress?

### ISSUE THREAD

**Issue by DavidAmyot** [gluestack/gluestack-ui#2523]
### Description

On Native, upon pressing a **Button** with the `onPress` event, I'd expect the _active style_ to be triggered, namely the `data-[active=true]:bg-primary-700` data selector in the **Button** component.

### CodeSandbox/Snack link

N/A

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

I'm using the latest expo and the latest gluestack-ui v2. By memory, I think before in v1 the `onPress` active style was working.

From what I can see [here](https://www.nativewind.dev/v4/core-concepts/states#data-selectors), even in v4 of nativewind, it seems like the data selectors are for web only?

If I put `active:bg-red-500` as className, it does work.
```tsx
<Button
	size="xl"
	variant="solid"
	action="primary"
	onPress={(): void => {}}
	className="active:bg-red-500"
>
	<ButtonText>Hello World!</ButtonText>
</Button>
```

However, I'd expect the the default `data-[active=true]:bg-primary-700` set in the primary buttonStyle of the Button component to work which it does not.

Am I missing something?

Thank you for the hard work, v2 is still much better than v1 imo and a very good step in the right direction!

**Comment by DavidAmyot** [comment]
@sra1kumar-NULL It really is not working for me in our project. I tried with the bit of code you shared as is and funnily, it worked at first because I had kept the `--not-working-- active:bg-red-500`, but as soon as I removed it to just have `className="data-[active=true]:bg-red-700"`, it didn't work anymore. 

My point was also that the default active style from the Button component does not seem to be applied either. Is there an existing Snack with gluestack-ui v2 installed for me to try it out?

Thanks!

**Comment by sra1kumar-NULL** [comment]
hey @DavidAmyot , That's wierd. If you could share you repository then that would be very much helpful for us to debug the issue.
And no currently we don't have any snack with gluestack-ui v2 , but we have a whole starter kit application you can check / try this out.
https://github.com/gluestack/gluestack-ui-starter-kits

**Comment by DavidAmyot** [comment]
@sra1kumar-NULL Yeah, I had cloned it, installed the packages for the expo app inside, launched it and in expo go it just crashes with the latest expo sdk (same for our app). I then tried to make a dev build locally and I was getting an error but haven't had the time to check it out yet. 

In case you know, below is a screenshot of the error. I'm running this on an m2 max macbook pro, I can build locally just fine on my own project.

![image](https://github.com/user-attachments/assets/46777547-0bc7-4bae-80e8-b4e00310c0d2)

**Comment by DavidAmyot** [comment]
@sra1kumar-NULL Fixed. I'm confused as to how this happened, but i had `@gluestack-ui/button` 1.0.7 installed from a while ago, but when I checked the content of its index.tsx versus the one from the starter-kit, there were a lot of differences even though the version was the same. I really don't know how this could have happened since I've never modified the file itself and had installed it with the cli of gluestack-ui...

But yeah, unless you know why or you need to say anything, feel free to close this, fixed on my end by running `npx gluestack-ui add button`.
