### ISSUE TITLE
How can I upgrade a component in v2 ?

### ISSUE THREAD

**Issue by llr101** [gluestack/gluestack-ui#2525]
### Description

How can I upgrade a component in v2 ?
And how to check if all components I installed are the latest version?

### Problem Statement

How can I upgrade a component in v2 ?
And how to check if all components I installed are the latest version?

### Proposed Solution or API

v2

**Comment by sra1kumar-NULL** [comment]
hey @llr101 ,
To upgrade a component in v2 - please use ``` npx gluestack-ui add <component_name>``` command.
To check if all components are in latest version or not - currently we don't have any, but we are working on a script to check and update all the components to the latest versions of them.
Closing this issue for now, feel free to reopen the issue if you have any more queries regarding the same context.
