### ISSUE TITLE
Errors with `npx gluestack-ui@latest add icon`.

### ISSUE THREAD

**Issue by GollyJer** [gluestack/gluestack-ui#253]
I can't get the app to load after installing icons. I'm in a nextjs 13 application.

I used `npx gluestack-ui@latest add icons` with an `s`. I think the docs are incorrect.
After additionally installing all the dependencies, I get this with the nextjs app loads.

I've been able to troubleshoot most of the bugs to this point, but not sure what to do with this one. Thanks!

> <img width="600" alt="image" src="https://user-images.githubusercontent.com/689204/230984243-b5616692-5d0c-40bf-b2f0-b76596968ba4.png">

**Comment by ankit-tailor** [comment]
Hi @GollyJer, Thanks for reporting the issue. We are looking into it.

**Comment by ankit-tailor** [comment]
Hey @GollyJer, I was able to get icons to work in Next.js 13.  It would be great if you can share minimal reproduction of the issue.

**Comment by mayank-96** [comment]
Hello @GollyJer, try running `yarn` or `npm install` once, you are facing this issue because dependencies are not installed properly.
