### ISSUE TITLE
Accordion not working with new architecture enabled

### ISSUE THREAD

**Issue by nnphong1904** [gluestack/gluestack-ui#2545]
### Description

The accordion component doesn't work with new architecture enabled

### CodeSandbox/Snack link

https://github.com/nnphong1904/glutstack-accordion-reproduction

### Steps to reproduce

1. Clone project
2. Run `bun i` to install all dependencies
3. Run `bun expo run ios`
4. Test around with accordion component

### gluestack-ui Version

v2

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

### Additional Information
- I made some investigation. The `onLayout` function in `AnimatedHeight` will be fired with the 0 height. So the calculation for the children's height will not be correct.

**Comment by rajat693** [comment]
hi @nnphong1904 please install the latest version of `react-native-svg`.

**Comment by rajat693** [comment]
@nnphong1904 `react-native-svg` is used in `icon`. For now instead of using `bun` you can use `npm`. We are working on resolving this issue.

**Comment by nnphong1904** [comment]
@rajat693 I don't have any issue with the icon. The icon is still working. The problem is with the accordion content. It doesn't open when I press the trigger. I think it is related to the StyleSheet. absolutely. I removed it and replace with `position: absolute` and the issue is fixed

**Comment by Kirill5k** [comment]
@nnphong1904, I am facing the same issue. could you please explain how did you manage to fix it?

**Comment by rajat693** [comment]
hi @nnphong1904 this issue is resolved now with latest stable release of gluestack-ui v2 with nativewind 4.1v
