### ISSUE TITLE
Support for react-native 0.7 is missing

### ISSUE THREAD

**Issue by CodeMode365** [gluestack/gluestack-ui#2573]
### Description

Previous component implementation of gluestack-ui v2 is not working in react-native bridgeless version i.e 0.7

### Problem Statement

This features enables to make faster and latest react native app with gluestack ui

### Proposed Solution or API

I don't have the code, but i tried using it with version react native version 0.7 and expo version 52 but i throws an error

**Comment by roy-law** [comment]
```
iOS Bundling failed 481ms node_modules/expo-router/entry.js (12 modules)
 ERROR  SyntaxError: $HOME/node_modules/@expo/metro-runtime/src/location/install.native.ts: Missing semicolon. (16:37)

  14 | import getDevServer from '../getDevServer';
  15 |
> 16 | const manifest = Constants.expoConfig as Record<string, any> | null;
     |                                      ^
  17 |
  18 | function getOrigin() {
  19 |   if (process.env.NODE_ENV !== 'production') {
```

To reproduce:
- Init an expo project with expo router
- Verify if it works with bare project (It does)
- Run `npx gluestack-ui init`
- Re-start the server
- Verify if anything broken after installing a bunch of stuff (Failed)

**Comment by jordcodes** [comment]
I am experiencing this after moving to expo sdk52 and RN with new arch. 

Did you find any solutions?

**Comment by ha0min** [comment]
same issue happening to me do... 
can't even run the template project created by `npx create-expo-app@latest
` after run `npx gluestack-ui init`

**Comment by Viraj-10** [comment]
Hey @roy-law, @jordcodes, and @CodeMode365,  

Please review your NativeWind configuration using [these docs](https://www.nativewind.dev/getting-started/expo-router). Let us know which fixes worked for you.  

If you're unable to resolve the issue, please share a github repo.

**Comment by Viraj-10** [comment]
This issue has been fixed with latest version of CLI.
