### ISSUE TITLE
The project built with a monorepo includes Next.js and Expo.

### ISSUE THREAD

**Issue by chenerge** [gluestack/gluestack-ui#2582]
### Description

The Next.js startup fails, and the components used by Expo are not styled.

### CodeSandbox/Snack link

.

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

https://github.com/chenerge/scud-monorepo.git

**Comment by Viraj-10** [comment]
Hey @chenerge, Please use `react-native-svg` version 13.4.0.

**Comment by chenerge** [comment]
> 嘿，请使用 13.4.0 版本。`react-native-svg`
Hello, I made the modifications and Next.js is running, but Expo still doesn't have the styles.

**Comment by chenerge** [comment]
I encountered an error when using toast in Next.js.
NativeAnimatedHelper.js:428 Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation. To resolve this, add `RCTAnimation` module to this app, or remove `useNativeDriver`. Make sure to run `bundle exec pod install` first. Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
