### ISSUE TITLE
Android  &  iOS 全新app样式未生效

### ISSUE THREAD

**Issue by 7chenys** [gluestack/gluestack-ui#2595]
### Description

yarn start 运行创建全新的app时，样式没有生效

### CodeSandbox/Snack link

null

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by 7chenys** [comment]
"tailwindcss": "^3.4.14"

**Comment by Viraj-10** [comment]
@7chenys, please share a github repository and also check out this [steps](https://www.nativewind.dev/getting-started/expo-router).

**Comment by 7chenys** [comment]
> @7chenys，请分享一个 github 存储库并查看这些[步骤](https://www.nativewind.dev/getting-started/expo-router)。

是的，我就是这么做的，很遗憾，依旧不行🙅

**Comment by 7chenys** [comment]
[gluestack-ui.config.json](https://github.com/user-attachments/files/17838752/gluestack-ui.config.json)

**Comment by 7chenys** [comment]
这是我的metro文件

const {withNativeWind} = require('nativewind/metro');
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = mergeConfig(getDefaultConfig(__dirname), {});

module.exports = withNativeWind(config, {
  input: './global.css',
});

**Comment by 7chenys** [comment]
这是tailwind.config.js 文件
const gluestackPlugin = require('@gluestack-ui/nativewind-utils/tailwind-plugin');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'media',
  content: [
    './App.{tsx,jsx,ts,js}',
    './index.{tsx,jsx,ts,js}',
    './src/**/*.{tsx,jsx,ts,js}',
    './components/**/*.{tsx,jsx,ts,js}',
  ],
  presets: [require('nativewind/preset')],
  safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark)/,
    },
  ],
  theme: {
   // extend: {},
  },
  plugins: [gluestackPlugin],
};

**Comment by 7chenys** [comment]
这是babel.config.js 文件
module.exports = {
  presets: ['module:@react-native/babel-preset', 'nativewind/babel'],

  plugins: [
    [
      'module-resolver',
      {
        root: ['./'],
        extensions: ['.js', '.ts', '.tsx', '.jsx'],

        alias: {
          '@': './',
          'tailwind.config': './tailwind.config',
        },
      },
    ],
    'react-native-reanimated/plugin'
  ],
};

**Comment by 7chenys** [comment]
这是 global.css文件
@tailwind base;
@tailwind components;
@tailwind utilities;

**Comment by 7chenys** [comment]
tsconfig.ts 文件
{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compilerOptions": {
    "paths": {
      "@/*": [
        "./*"
      ],
      "tailwind.config": [
        "./tailwind.config.js"
      ]
    }
  }
}

**Comment by 7chenys** [comment]
@Viraj-10 请帮我分析一下问题是什么，为什么全新app会没有样式，按钮也不出现

**Comment by Viraj-10** [comment]
Hey @7chenys, without github repo. I can't actually help you much but [here](https://github.com/Viraj-10/expo-gluestack-ui) is expo project with gluestack-ui. Let me know if it works for you.

**Comment by dcatindoy** [comment]
Hi @Viraj-10, I encountered the same issue. Please see below details for you reference:

#### Environment
- **Node.js version**: v22.11.0 (installed and used via `nvm`)
- **Expo CLI version**: Latest (as of the issue date)
- **Gluestack UI version**: Installed via `npx gluestack-ui init`

#### Steps to Reproduce
1. Install Node.js version 22.11.0:
   ```bash
   nvm install 22.11.0
   nvm use 22.11.0
   ```
2. Create a new Expo app:
   ```bash
   npx create-expo-app@latest
   ```
   - **Sample project name**: `gluestack-expo-bug`
3. Navigate to the project directory:
   ```bash
   cd gluestack-expo-bug
   ```
4. Initialize Gluestack UI:
   ```bash
   npx gluestack-ui init
   ```
5. Start the project:
   ```bash
   npm start
   ```

#### Expected Behavior
The Expo project should start without errors, and Gluestack UI should be ready for use.

#### Actual Behavior
The following error occurs after running `npm start`:
```
file:///Users/dcatindoy/Desktop/PROJECTS/gluestack-expo-bug/node_modules/@gluestack-ui/nativewind-utils/tailwind-plugin/index.js:1
const plugin = require('tailwindcss/plugin');
               ^

ReferenceError: require is not defined
    at file:///Users/dcatindoy/Desktop/PROJECTS/gluestack-expo-bug/node_modules/@gluestack-ui/nativewind-utils/tailwind-plugin/index.js:1:16
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:366:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:325:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1381:24)
    at Module._compile (node:internal/modules/cjs/loader:1503:5)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
```

#### Additional Details
- **Project directory**: `/Users/dcatindoy/Desktop/PROJECTS/gluestack-expo-bug`
- **Error source file**: `/node_modules/@gluestack-ui/nativewind-utils/tailwind-plugin/index.js`
- **Public Repo for the bug**: `https://github.com/dcatindoy/gluestack-expo-bug.git`

Let me know if you have any questions, Thanks in advance! 👋

**Comment by Viraj-10** [comment]
Hey @dcatindoy, Please check this [PR](https://github.com/dcatindoy/gluestack-expo-bug/pull/1). It should fix the issue.

**Comment by dcatindoy** [comment]
> Hey @dcatindoy, Please check this [PR](https://github.com/dcatindoy/gluestack-expo-bug/pull/1). It should fix the issue.

Hi @Viraj-10, checking on it. Thanks for your quick response. Appreciated! 👋

**Comment by trdp30** [comment]
Is this issue resolved? I'm still facing this issue.
<img width="802" alt="Screenshot 2024-11-29 at 4 26 23 PM" src="https://github.com/user-attachments/assets/7a80ac7a-9e8d-4815-ad30-5178fc80288d">

**Comment by Viraj-10** [comment]
Hey @trdp30, please run `@gluestack-ui/nativewind-utils@alpha`

**Comment by trdp30** [comment]
Thanks @Viraj-10. It works.

**Comment by Viraj-10** [comment]
Hey @trdp30, I would suggest you should init using `--alpha` tag it comes with latest version of `nativewind` and will be going live on monday.

**Comment by trdp30** [comment]
> Hey @trdp30, I would suggest you should init using `--alpha` tag it comes with latest version of `nativewind` and will be going live on monday.
> 

I just updated the version in the package.json. once the new version is up, I'll update it properly.
