### ISSUE TITLE
TypeScript Error: Children prop not allowed on SelectIcon despite documentation example

### ISSUE THREAD

**Issue by kamarul-ariffin-github** [gluestack/gluestack-ui#2600]
### Description

Using SelectIcon component with children as shown in the documentation causes TypeScript errors, despite the code working functionally. The error indicates that the 'children' property is not allowed in the type definition.

### CodeSandbox/Snack link

dont have

### Steps to reproduce

1. Create a new React Native project with Gluestack UI
2. Install dependencies:
```
npm install @gluestack-ui/themed@^1.1.9 @gluestack-style/react@^1.1.49 @gluestack-ui/config@^1.1.16
```
3. Create a Select component following the documentation:
```
 <SelectTrigger variant="underlined">
  <SelectInput placeholder="Select one" />
  <SelectIcon mr="$2">
    <Icon as={ChevronDown} />
  </SelectIcon>
</SelectTrigger>
```
4. TypeScript will show the following error:
```
Type '{ children: Element; mr: "$2"; }' is not assignable to type 'IntrinsicAttributes & StyledComponentProps<...>'.
Property 'children' does not exist on type 'IntrinsicAttributes & StyledComponentProps<...>'
```

Expected behavior: The code should compile without TypeScript errors since it follows the pattern shown in the official documentation: https://ui.gluestack.io/docs/components/forms/select#select-with-icon

gluestack-ui Version:

@gluestack-ui/themed: ^1.1.9
@gluestack-style/react: ^1.1.49
@gluestack-ui/config: ^1.1.16

### gluestack-ui Version

1.1.9

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

### Additional Information

Environment details:

react-native: 0.74.1
react: 18.2.0
typescript: ~5.3.3
expo: ^51.0.8
The component works functionally despite the TypeScript error. Attempted workarounds like using asChild prop did not resolve the issue. This appears to be a type definition issue rather than a functional one.

**Comment by Viraj-10** [comment]
Hey @kamarul-ariffin-github, Thanks for reporting the issue. This issue is related to docs. 
Correct Way of using `SelectIcon` is as follows
```jsx
  <SelectIcon className="mr-3" as={ChevronDownIcon} />
  ```
