### ISSUE TITLE
Can't get styling with storybook/react-webpack5

### ISSUE THREAD

**Issue by JavanPoirier** [gluestack/gluestack-ui#2612]
### Description

Can't get styling with storybook/react-webpack5

### CodeSandbox/Snack link

https://github.com/JavanPoirier/gluestack-sb-web

### Steps to reproduce

I am coming from V1 and have a working setup with my Storybook instance running react-webpack5, a NextJS web client and a expo client. Instead of 2 storybook instances I opted for a single root level one. 

I am considering dropping NextJS support and just using Expo for web, of which I have GlueStack v2 working with Expo. I would still like to know what I am missing here... The goal would be to be able to have my SB instance separate from NextJS and Expo. 

I suspect the issue to be something to do with the tailwind config. not being added...?

Thanks.

1. Go to https://github.com/JavanPoirier/gluestack-sb-web
2. Run and view Button story.
4. See lack of styling

![image](https://github.com/user-attachments/assets/3cd69a06-f90a-4e7a-b17a-b51db63ce86f)

### gluestack-ui Version

v2

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by JavanPoirier** [comment]
Resolved. Was caused by missing component path in the `content` array of `tailwind.config.js`.

![image](https://github.com/user-attachments/assets/63c06fb7-8e86-4f03-9486-874a3f300ea8)

**Comment by Under-Warz** [comment]
Same issue here. I've double check tailwind configuration and it's working fine with `react-native` composant (`Pressable`, `View`...) but when I'm using the `Button` from gluestack, all the tailwind classes disappear. Only the nativewind classes remain.

I also try to use the storybook projects from `exemple` directory, they are not working...

PS : I have to use the `nativewind@4.0.36` to be able to make tailwind working, with the last version, all my tailwind classes disappear on render
