### ISSUE TITLE
Cannot Focus Input Fields

### ISSUE THREAD

**Issue by rlee1990** [gluestack/gluestack-ui#2624]
### Description

```Type 'RefObject<TextInput>' is not assignable to type 'LegacyRef<TextInputProps> | undefined'.   Type 'RefObject<TextInput>' is not assignable to type 'RefObject<TextInputProps>'.     Type 'TextInput' has no properties in common with type 'TextInputProps'.ts(2322) index.d.ts(303, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & Omit<IInputFieldProps, "ref"> & RefAttributes<TextInputProps>'```

### CodeSandbox/Snack link

*

### Steps to reproduce

Create an expo project and add a few input fields. Set the ref to React.useRef<React.ElementRef<typeof TextInput>>(null); and then add it to the inputfield.

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by ugnmura** [comment]
I'm having the same problems on `3.0.6`

**Comment by AiMAnsarie** [comment]
Having the same issue on `3.0.11`

**Comment by yure-nogueira** [comment]
Having the same issue on `3.0.12` (ios devices)
