### ISSUE TITLE
Styles are not working, 9/10 times.

### ISSUE THREAD

**Issue by gablabelle** [gluestack/gluestack-ui#2629]
### Description

Hello I have a setup a monorepo with an expo app and have initialized gluestack in the monorepo. When I start the app, most of the times the styles don't work. That's like 9 times out of 10. But once in a while, the styles will load correctly, but that's 1/10 times if not less.  Could someone tell me what I'm missing? Please note that if you start the web app before starting expo, the styles always work.

### CodeSandbox/Snack link

https://github.com/gablabelle/gluestack-ui-bug

### Steps to reproduce

1. Clone the [repo](https://github.com/gablabelle/gluestack-ui-bug)
2. `pnpm install`
3. `pnpm run:native`
4. Choose IOS simulator

### gluestack-ui Version

latest (installed using --all yesterday, Dec 4th)

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

⚠️ Please note that if you start the web app before starting expo, the styles always work.

If it doesn't work you'll see this
![Screenshot 2024-12-04 at 14 03 53](https://github.com/user-attachments/assets/0ad3ad45-2528-4380-9a73-0a79891d1d7e)

But if it works you'll see this
![Screenshot 2024-12-04 at 16 28 06](https://github.com/user-attachments/assets/939a853e-b664-4d98-9139-4d88c9d688d7)

**Comment by Viraj-10** [comment]
Hey @gablabelle, Please upgrade to stable version. you can find a blog about [here](https://gluestack.io/blogs/gluestack-ui-v2-stable-release-with-nativewind-v4-1-support)

**Comment by gablabelle** [comment]
Works

**Comment by gablabelle** [comment]
Works

**Comment by danglekhoa1912** [comment]
Hi @Viraj-10 In case I have already initialized it before, how can I upgrade the version? Thank you.
<img width="442" alt="Screenshot 2024-12-13 at 01 33 31" src="https://github.com/user-attachments/assets/9bed4f5b-87c8-4cd5-b1cb-dab579c6c1c2" />

**Comment by gablabelle** [comment]
> Hi @Viraj-10 In case I have already initialized it before, how can I upgrade the version? Thank you. <img alt="Screenshot 2024-12-13 at 01 33 31" width="442" src="https://private-user-images.githubusercontent.com/58388376/395286476-9bed4f5b-87c8-4cd5-b1cb-dab579c6c1c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjg3ODUsIm5iZiI6MTczNDAyODQ4NSwicGF0aCI6Ii81ODM4ODM3Ni8zOTUyODY0NzYtOWJlZDRmNWItODdjOC00Y2Q1LWIxY2ItZGFiNTc5YzZjMWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE4MzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDkwYWZhNGYxMDNlMTM5NDhmOWJhZTA2OWI3YzQ1ZGYxOThkMTdjNGMyMDEyOGU5ODRkNDRhY2Q0ZDc1YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HvsSgg_Cdn_3smu9t2TIn8WcaUL0n00vxC_-s8lXJy8">

Good question, I had to check the source code of their CLI to figure it out. You need to delete the folder of the `ui/gluestack-ui-provider` folder in order to be able to install.

IMO this is a bad way to check that the lib is installed.

But anyways after removing that folder you should be able to run the init again.

**Comment by danglekhoa1912** [comment]
Works, thanks.
