### ISSUE TITLE
ActionSheet not working at all

### ISSUE THREAD

**Issue by tacheraSasi** [gluestack/gluestack-ui#2630]
### Description

The actionSheet doesnot open even though i did everything correctly

### CodeSandbox/Snack link

https://github.com/mencorium/takeNotes

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

### Additional Information

Does not work

**Comment by Viraj-10** [comment]
Hey @tacheraSasi, I am getting 404 while opening you repo link. Please reopen a issue with correct link.
<img width="1365" alt="Screenshot 2024-12-06 at 12 26 58 PM" src="https://github.com/user-attachments/assets/b7dddae6-f391-41cd-b1ea-beddddbd6f89">

**Comment by tacheraSasi** [comment]
> Hey @tacheraSasi, I am getting 404 while opening you repo link. Please reopen a issue with correct link.
> <img width="1365" alt="Screenshot 2024-12-06 at 12 26 58 PM" src="https://github.com/user-attachments/assets/b7dddae6-f391-41cd-b1ea-beddddbd6f89">
> 

Ahh i see i made the repo was private

**Comment by tacheraSasi** [comment]
> Hey @tacheraSasi, I am getting 404 while opening you repo link. Please reopen a issue with correct link.
> <img width="1365" alt="Screenshot 2024-12-06 at 12 26 58 PM" src="https://github.com/user-attachments/assets/b7dddae6-f391-41cd-b1ea-beddddbd6f89">
> 

This here is exactly what i did 




      function App(){
        const [showActionsheet, setShowActionsheet] = React.useState(false);
        const handleClose = () => setShowActionsheet(false);
          return (
            <>
              <Button onPress={() => setShowActionsheet(true)}>
                <ButtonText>Open Actionsheet</ButtonText>
              </Button>
              <Actionsheet isOpen={showActionsheet} onClose={handleClose}>
                <ActionsheetBackdrop />
                <ActionsheetContent>
                  <ActionsheetDragIndicatorWrapper>
                    <ActionsheetDragIndicator />
                  </ActionsheetDragIndicatorWrapper>
                  <ActionsheetItem onPress={handleClose}>
                    <ActionsheetItemText>Edit Message</ActionsheetItemText>
                  </ActionsheetItem>
                  <ActionsheetItem onPress={handleClose}>
                    <ActionsheetItemText>Mark Unread</ActionsheetItemText>
                  </ActionsheetItem>
                  <ActionsheetItem onPress={handleClose}>
                    <ActionsheetItemText>Remind Me</ActionsheetItemText>
                  </ActionsheetItem>
                  <ActionsheetItem onPress={handleClose}>
                    <ActionsheetItemText>Add to Saved Items</ActionsheetItemText>
                  </ActionsheetItem>
                  <ActionsheetItem isDisabled onPress={handleClose}>
                    <ActionsheetItemText>Delete</ActionsheetItemText>
                  </ActionsheetItem>
                </ActionsheetContent>
              </Actionsheet>
            </>
          );
        }
