### ISSUE TITLE
No font size with name `text-md` exist

### ISSUE THREAD

**Issue by stefan-schweiger** [gluestack/gluestack-ui#2632]
### Description

`text-md` but this is not a valid style but used by components

### CodeSandbox/Snack link

https://snack.expo.dev

### Steps to reproduce

Some components use the style `text-md` but this is not a font size that exists. I think it was used by mistake instead of `text-base`.

https://github.com/search?q=repo%3Agluestack%2Fgluestack-ui+text-md&type=code

### gluestack-ui Version

v2-latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by rajat693** [comment]
hi @stefan-schweiger, This issue is fixed now, please feel free to reopen this if you still have any queries.
