### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by swsvindland** [gluestack/gluestack-ui#2635]
### Description

Domain looks to be expired

### CodeSandbox/Snack link

https://gluestack.io/lander

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by sanketsahu** [comment]
We are looking into it. Thanks for raising this issue.

**Comment by sanketsahu** [comment]
It's fixed!
