### ISSUE TITLE
Menu component error

### ISSUE THREAD

**Issue by thgh** [gluestack/gluestack-ui#432]
### Description

Menu error: `MenuContext` must be used within `MenuContext`  

### Steps to reproduce

1. Go to https://ui.gluestack.io/docs/components/overlay/menu
2. Click the hamburger
3. See error in console: `MenuContext` must be used within `MenuContext`
  

### gluestack-ui Version

website

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [X] Next

**Comment by Viraj-10** [comment]
Hey @thgh, This issue is fixed. Thanks for reporting.
