### ISSUE TITLE
Pure React Native compatibility

### ISSUE THREAD

**Issue by 404-html** [gluestack/gluestack-ui#436]
### Description

Enable the framework to work with pure React Native projects.

### Problem Statement

Looks like currently the framework is working only with Expo projects.

### Proposed Solution or API

Enable the framework to work with pure React Native projects.

**Comment by ZanaNabaz** [comment]
1+

**Comment by mayank-96** [comment]
Hey @404-html @ZanaNabaz, `gluestack-ui` is compatible with pure react native. Can you please specify the error you are facing ?

**Comment by gauravguha** [comment]
We support React Native CLI. Going to add it in the docs very soon. If you face any issues feel free to report it.

**Comment by jedi2209** [comment]
Thanx, @gauravguha!

I look forward to an update of the documentation as soon as possible!
