### ISSUE TITLE
TypeError: Cannot convert undefined value to object

### ISSUE THREAD

**Issue by jasonz1360** [gluestack/gluestack-ui#464]
### Description

Errors are reported when running in the ios simulator, but the web side is fine

### Steps to reproduce

1. Run yarn expo:ios
2. waiting for ios simulator ( iPhone 14 Pro simulator and iPad Pro 12.9 third generation simulator) launch, then open expo go.
3. the Error show as below:
<img width="405" alt="2023-05-19 16 16 30" src="https://github.com/gluestack/gluestack-ui/assets/96457197/bb61b34a-8a4b-468e-a479-a6a425489326">
4.At first I suspected it was a problem with the expo or expo go version, but I tried some old version, and the problem remained. When i run yarn expo:web, everything is ok, it's weird.
5.package.json

{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "expo:start": "expo start",
    "expo:android": "expo start --android",
    "expo:ios": "expo start --ios",
    "expo:web": "expo start --web"
  },
  "overrides": {
    "react-error-overlay": "6.0.9"
  },
  "dependencies": {
    "@dank-style/animation-plugin": "latest",
    "@dank-style/react": "latest",
    "@expo-google-fonts/space-grotesk": "^0.2.2",
    "@expo/html-elements": "latest",
    "@expo/match-media": "^0.4.0",
    "@expo/webpack-config": "^18.0.1",
    "@gluestack-ui/actionsheet": "latest",
    "@gluestack-ui/avatar": "latest",
    "@gluestack-ui/button": "latest",
    "@gluestack-ui/form-control": "latest",
    "@gluestack-ui/hstack": "latest",
    "@gluestack-ui/input": "latest",
    "@gluestack-ui/link": "latest",
    "@gluestack-ui/pressable": "latest",
    "@gluestack-ui/provider": "latest",
    "@gluestack-ui/select": "latest",
    "@gluestack-ui/spinner": "latest",
    "@gluestack-ui/toast": "latest",
    "@gluestack-ui/vstack": "latest",
    "@legendapp/motion": "latest",
    "@react-native-aria/interactions": "^0.2.8",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "~6.0.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native-stack": "^6.0.2",
    "@react-navigation/stack": "~6.0.1",
    "apisauce": "2.1.5",
    "date-fns": "^2.29.2",
    "expo": "^48.0.15",
    "expo-application": "~5.1.1",
    "expo-constants": "~14.2.1",
    "expo-device": "~5.2.1",
    "expo-file-system": "~15.2.1",
    "expo-font": "~11.1.1",
    "expo-linking": "~4.0.1",
    "expo-localization": "~14.1.1",
    "expo-modules-core": "~1.2.3",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "formik": "^2.2.9",
    "i18n-js": "3.9.2",
    "jsencrypt": "^3.2.1",
    "mobx": "6.6.0",
    "mobx-react-lite": "3.4.0",
    "mobx-state-tree": "5.1.5",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-bootsplash": "4.5.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-pager-view": "^6.2.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-vector-icons": "^9.2.0",
    "reactotron-mst": "3.1.4",
    "reactotron-react-js": "^3.3.7",
    "reactotron-react-native": "5.0.3",
    "yup": "^1.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/cli-platform-ios": "^8.0.2",
    "@rnx-kit/metro-config": "^1.3.5",
    "@rnx-kit/metro-resolver-symlinks": "^0.1.26",
    "@types/i18n-js": "3.8.2",
    "@types/jest": "^29.2.1",
    "@types/react": "~18.0.27",
    "@types/react-native": "^0.71.6",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "5.28.0",
    "@typescript-eslint/parser": "5.28.0",
    "babel-jest": "^29.2.1",
    "babel-loader": "8.2.5",
    "babel-plugin-root-import": "^6.6.0",
    "eslint": "8.17.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-config-standard": "17.0.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "6.0.0",
    "eslint-plugin-react": "7.30.0",
    "eslint-plugin-react-native": "4.0.0",
    "expo-modules-autolinking": "~1.1.0 || ~1.2.0",
    "fbjs-scripts": "3.0.1",
    "jest": "^29.2.1",
    "jest-circus": "29",
    "jest-environment-node": "29",
    "jest-expo": "^48.0.0",
    "metro-config": "0.75.1",
    "metro-react-native-babel-preset": "0.75.1",
    "metro-source-map": "0.75.1",
    "mocha": "6",
    "patch-package": "6.4.7",
    "postinstall-prepare": "1.0.1",
    "prettier": "2.6.2",
    "query-string": "^7.0.1",
    "react-devtools-core": "4.24.7",
    "react-dom": "18.2.0",
    "react-native": "^0.70.7",
    "react-native-web": "^0.18.12",
    "react-test-renderer": "18.2.0",
    "reactotron-core-client": "^2.8.10",
    "regenerator-runtime": "^0.13.4",
    "ts-jest": "29",
    "typescript": "^4.8.4"
  },
  "resolutions": {
    "@types/react": "^18",
    "@types/react-dom": "^18"
  },
  "prettier": {
    "printWidth": 100,
    "semi": false,
    "singleQuote": false,
    "trailingComma": "all"
  },
  "eslintConfig": {
    "root": true,
    "parser": "@typescript-eslint/parser",
    "extends": [
      "plugin:@typescript-eslint/recommended",
      "plugin:react/recommended",
      "plugin:react-native/all",
      "standard",
      "prettier"
    ],
    "plugins": [
      "@typescript-eslint",
      "react",
      "react-native"
    ],
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      },
      "project": "./tsconfig.json"
    },
    "settings": {
      "react": {
        "pragma": "React",
        "version": "detect"
      }
    },
    "globals": {
      "__DEV__": false,
      "jasmine": false,
      "beforeAll": false,
      "afterAll": false,
      "beforeEach": false,
      "afterEach": false,
      "test": false,
      "expect": false,
      "describe": false,
      "jest": false,
      "it": false
    },
    "rules": {
      "@typescript-eslint/ban-ts-ignore": 0,
      "@typescript-eslint/ban-ts-comment": 0,
      "@typescript-eslint/explicit-function-return-type": 0,
      "@typescript-eslint/explicit-member-accessibility": 0,
      "@typescript-eslint/explicit-module-boundary-types": 0,
      "@typescript-eslint/indent": 0,
      "@typescript-eslint/member-delimiter-style": 0,
      "@typescript-eslint/no-empty-interface": 0,
      "@typescript-eslint/no-explicit-any": 0,
      "@typescript-eslint/no-object-literal-type-assertion": 0,
      "@typescript-eslint/no-var-requires": 0,
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          "argsIgnorePattern": "^_",
          "varsIgnorePattern": "^_"
        }
      ],
      "comma-dangle": 0,
      "multiline-ternary": 0,
      "no-undef": 0,
      "no-unused-vars": 0,
      "no-use-before-define": 0,
      "no-global-assign": 0,
      "quotes": 0,
      "react-native/no-raw-text": 0,
      "react/no-unescaped-entities": 0,
      "react/prop-types": 0,
      "space-before-function-paren": 0
    }
  }
}

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

TypeError: Cannot convert undefined value to object

This error is located at:
    in NewComp (created by DankStyledComponent)
    in DankStyledComponent (created by ErrorDetails)
    in RCTView (created by View)
    in View (created by ErrorDetails)
    in RCTView (created by View)
    in View (created by ScreenWithoutScrolling)
    in RCTView (created by View)
    in View (created by ScreenWithoutScrolling)
    in ScreenWithoutScrolling (created by Screen)
    in RCTView (created by View)
    in View (created by KeyboardAvoidingView)
    in KeyboardAvoidingView (created by Screen)
    in RCTView (created by View)
    in View (created by Screen)
    in Screen (created by ErrorDetails)
    in ErrorDetails (created by ErrorBoundary)
    in ErrorBoundary (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App (created by IgniteApp)
    in IgniteApp (created by withDevTools(IgniteApp))
    in withDevTools(IgniteApp)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

**Comment by jasonz1360** [comment]
Hi, my expo-cli version is 6.3.7, and node.js version is 16.20.0. I also try using node v14.21.3 (npm v6.14.18), expo 5.4.12, the Problem remained.

**Comment by jasonz1360** [comment]
Hi, I found out that's because of a null route error on my navigator startup page.

`const route = useNavigationState((state) => state.routes[state.index]);`

Because the routes is undefined, then app crash, cause gluestack provider not initiated correctly.

**Comment by antondrob** [comment]
I am getting the same error when importing the gluestack icon to the component and trying to run the app on the web.
Android is working fine at the same time.
