### ISSUE TITLE
When I run 'yarn web', it throws a 'Failed to parse source map' error.

### ISSUE THREAD

**Issue by heijinggh** [gluestack/gluestack-ui#465]
### Description

When I run 'yarn web', it throws a 'Failed to parse source map' error.

### Steps to reproduce

1. ```git clone https://github.com/heijinggh/expo-gluestack-template.git```
2. ```yarn``` 
3. ```yarn web```
4. Open http://localhost:19006
5. See errors in the terminal console

### gluestack-ui Version

@dank-style/react@0.4.7

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

```
WARNING in ./node_modules/@dank-style/react/lib/module/core/colorMode.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/node_modules/@dank-style/react/lib/src/colorMode.ts' file: Error: ENOENT: no such file or directory, open '/node_modules/@dank-style/react/lib/src/colorMode.ts'
```

**Comment by AshwiniKumar007** [comment]
Hey @heijinggh ,
Thanks for reporting. We will look into this.

**Comment by Viraj-10** [comment]
Hey @heijinggh, This be should working now. Here is [snack](https://snack.expo.dev/@gluestack/gluestack-ui-starter) with the example of web running. 
Let us know if you still face issues we will reopen it.
