### ISSUE TITLE
ERROR: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?

### ISSUE THREAD

**Issue by amanape** [gluestack/gluestack-ui#466]
### Description

After installing the `Button` component following https://ui.gluestack.io/docs/getting-started/install-expo, I get the error above when starting the app and no other information.

### Steps to reproduce

1. Create app with `npx create-expo-app my-app --template expo-template-blank-typescript`
2. Follow instructions in [Getting Started](https://ui.gluestack.io/docs/getting-started/install-expo)
3. Run `npm start`

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by AshwiniKumar007** [comment]
Hey @amanape ,
Thanks for reporting. We will look into this.

**Comment by saaymeen** [comment]
Also happens using bare `react-native@0.71.8`

**Comment by amanape** [comment]
Hi @makkarMeenu, the issue has been resolved after updating to the latest version. Thanks!
