### ISSUE TITLE
Menu onPress "pressing" items behind menu

### ISSUE THREAD

**Issue by capturetheworld** [gluestack/gluestack-ui#491]
### Description

When a menu item is selected in Chrome (but not in Safari) elements behind the menu are pressed.

### Steps to reproduce

1. Use a Menu component 
2. Click the Menu button
3. Click a Menu.Item with an onPress event
4. (bug) the onPress event then presses items behind it.

### gluestack-ui Version

latest 0.1.3

### Platform

- [ ] Android
- [x] Expo
- [ ] iOS
- [ ] Next

### Other Platform

Expo Web

### Additional Information

This only occurs in Chrome, but not in Safari.

**Comment by Viraj-10** [comment]
Hey @capturetheworld, Thanks for reporting the issue. We will have a look.

**Comment by makkarMeenu** [comment]
It is solved with the latest version of Menu. Please check and re-open the issue if it still exists.

**Comment by PiTiLeZarD** [comment]
Not sure if it's related or not, but I just discovered that the onPress on MenuItem does work on ios/android but not in chrome/safari, I'm using expo as well, should I open a new bug for this? @makkarMeenu

**Comment by blalitkumarpancholi** [comment]
Its still not working when i use screenOptions={{ presentation: "formSheet" }} then i get this error
