### ISSUE TITLE
defaultValue Prop on Switch not working

### ISSUE THREAD

**Issue by capturetheworld** [gluestack/gluestack-ui#502]
### Description

Setting the defaultValue prop = true doesn't turn the switch on.

### Steps to reproduce

I am currently using the defaultValue prop in order to "set" what the switch's initial state is based off of an API call. But it doesn't work, when I set it to a static defaultValue={true} it also doesn't work. This is a problem on Chrome and Safari.

### gluestack-ui Version

latest 0.1.3

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

### Other Platform

web

**Comment by akash3gtm** [comment]
@capturetheworld Could you share the snack link or a sandbox link?

**Comment by capturetheworld** [comment]
@akash3gtm I don't have a snack link or sandbox, but when I just pass in a value of {true} to the prop defaultValue, the switch is not in the on position.

**Comment by akash3gtm** [comment]
Hi @capturetheworld 
we're working on it, thank you for bringing it to our attention.

**Comment by makkarMeenu** [comment]
Can you please check with the latest version of Switch `0.1.10` ? It is working fine now. 
Feel free to open the issue again if still an issue
