### ISSUE TITLE
Heading: TS typing bug

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#514]
### Description

Ts error 2322: children property not exists

### Steps to reproduce

Install and try to use the <Heading>My text</Heading> as documented.

### gluestack-ui Version

latest

### Platform

- [X] Android
- [X] Expo
- [X] iOS
- [ ] Next

### Other Platform

react-native

### Additional Information

<img width="624" alt="Captura de pantalla 2023-05-31 a la(s) 20 15 57" src="https://github.com/gluestack/gluestack-ui/assets/517228/9c1b5cca-0ca1-40e6-b82a-3ea73ca1efa9">

<img width="447" alt="Captura de pantalla 2023-05-31 a la(s) 20 18 02" src="https://github.com/gluestack/gluestack-ui/assets/517228/784d6ca9-58a3-48f4-95c2-bfe9ac3a1a77">

**Comment by Viraj-10** [comment]
Hey @jacargentina, Thanks for reporting we will look into this.

**Comment by Viraj-10** [comment]
Hey @jacargentina, I tried it with the latest version I am unable to reproduce this. Please check on your end. 
If it is still there we will reopen this issue.

**Comment by jacargentina** [comment]
I've found it!

In a monorepo setup via Yarn, with TS, every required module (in this case '@expo/html-elements') MUST BE added to the "nohoist": [] setting, so TS find all types fine.

Leaving the comment for anybody having the same problem
