### ISSUE TITLE
TextArea invalid multiline prop

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#521]
### Description

Using <TextArea> as explained on documentation

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest / textarea-0.1.5

### Platform

- [x] Android
- [x] Expo
- [X] iOS
- [ ] Next

### Additional Information

        <TextArea>
          <TextArea.Input
            onChangeText={(text) => {
              useListsStore.getState().setList(listName, listKey, text);
            }}
            value={listText}
            autoCorrect={false}
            {...inputProps}
          />
        </TextArea>

Warning: Failed prop type: Invalid props.style key `multiline` supplied to `ForwardRef(TextInput)`.
Bad object: {
  "padding": 8,
  "multiline": true,
  "color": "#262626",
  "textAlignVertical": "top",
  "flex": 1,
  "paddingHorizontal": 12,
  "paddingVertical": 10,
  "fontSize": 16,
  "outlineWidth": "0",
  "outline": "none"
}
Valid keys: [
  "alignContent",
  "alignItems",
  "alignSelf",
  "aspectRatio",
  "borderBottomWidth",
  "borderEndWidth",
  "borderLeftWidth",
  "borderRightWidth",
  "borderStartWidth",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "columnGap",
  "direction",
  "display",
  "end",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "gap",
  "height",
  "justifyContent",
  "left",
  "margin",
  "marginBlock",
  "marginBlockEnd",
  "marginBlockStart",
  "marginBottom",
  "marginEnd",
  "marginHorizontal",
  "marginInline",
  "marginInlineEnd",
  "marginInlineStart",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginTop",
  "marginVertical",
  "maxHeight",
  "maxWidth",
  "minHeight",
  "minWidth",
  "overflow",
  "padding",
  "paddingBlock",
  "paddingBlockEnd",
  "paddingBlockStart",
  "paddingBottom",
  "paddingEnd",
  "paddingHorizontal",
  "paddingInline",
  "paddingInlineEnd",
  "paddingInlineStart",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingTop",
  "paddingVertical",
  "position",
  "right",
  "rowGap",
  "start",
  "top",
  "width",
  "zIndex",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "backfaceVisibility",
  "backgroundColor",
  "borderBottomColor",
  "borderBottomEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStartRadius",
  "borderColor",
  "borderCurve",
  "borderEndColor",
  "borderLeftColor",
  "borderRadius",
  "borderRightColor",
  "borderStartColor",
  "borderStyle",
  "borderTopColor",
  "borderTopEndRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "elevation",
  "opacity",
  "pointerEvents",
  "color",
  "fontFamily",
  "fontSize",
  "fontStyle",
  "fontVariant",
  "fontWeight",
  "includeFontPadding",
  "letterSpacing",
  "lineHeight",
  "textAlign",
  "textAlignVertical",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "textShadowColor",
  "textShadowOffset",
  "textShadowRadius",
  "textTransform",
  "userSelect",
  "verticalAlign",
  "writingDirection"
]

**Comment by jacargentina** [comment]
@Viraj-10 

To help you, think here are the problematic things:

gluestack/core/TextArea/styled-components/Input.tsx:8

```
//@ts-ignore
    multiline: true,
```

Also removing that, surfaces two other errors:

gluestack/core/TextArea/styled-components/Root.tsx: 72

```
'_input': {
            outlineWidth: '0',
            outline: 'none',
          },
```

**Comment by Viraj-10** [comment]
Hey @jacargentina, Thanks for reporting this issue. I will have a look.

**Comment by makkarMeenu** [comment]
This is resolved in the latest version of `Textarea`. Feel free to re-open the issue if it still exists,
