### ISSUE TITLE
HStack can't apply backgroundColor

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#522]
### Description

Applying backgroundColor="red" has no effect

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [X] Android
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

migrating from nativebase; the Stack accepted backgroundColor (typings on HStack from gluestack seems to accept it) but it is not working

**Comment by akash3gtm** [comment]
Hi @jacargentina ,
we use [gluestack-style](https://style.gluestack.io/) for styling of our components, values are in the form of tokens.

So the code should we written as
`backgroundColor="$red"`

Please refer  [gluestack-style](https://style.gluestack.io/) for styling.
Hope this helps.

**Comment by jacargentina** [comment]
@makkarMeenu how can I test that? don't know very much the library inner workings without your help.

**Comment by Viraj-10** [comment]
Hey @jacargentina, you can find a working example in this [snack](https://snack.expo.dev/@viraj_10/hstack-backgroundcolor-issue). 
Thanks for reporting the issue closing it now feel free to comment and we will reopen it.
