### ISSUE TITLE
Select: display "label" in place of "value"

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#523]
### Description

Select to choose from available app languages like this

```tsx
  var localesItems = getLocalesForPicker(getDefaultLocale()).map((l) => {
    return <Select.Item p="$2" key={l.value} label={l.label} value={l.value} />;
  });

        <Select
          selectedValue={locale}
          onValueChange={(val) => {
            useSettingsStore.setState({ locale: val });
          }}>
          <Select.Trigger w="100%">
            <Select.Input />
            <Select.Icon mr="$2">
              <Icon as={ChevronDownIcon} />
            </Select.Icon>
          </Select.Trigger>
          <Select.Portal>
            <Select.Backdrop />
            <Select.Content pb="$8">
              <Select.DragIndicatorWrapper>
                <Select.DragIndicator />
              </Select.DragIndicatorWrapper>
              {localesItems}
            </Select.Content>
          </Select.Portal>
        </Select>

```

localesItems is:

[<Select.Item label="Default - English (United States of America)" p="$2" value="default" />, <Select.Item label="Deutsch" p="$2" value="de" />, <Select.Item label="Deutsch (Austria)" p="$2" value="de-AT" />, <Select.Item label="English" p="$2" value="en" />, <Select.Item label="English (Philippines)" p="$2" value="en-PH" />, <Select.Item label="Español" p="$2" value="es" />, <Select.Item label="Français" p="$2" value="fr" />, <Select.Item label="Italiano" p="$2" value="it" />, <Select.Item label="Kiswahili (Tanzania, United Republic of)" p="$2" value="sw-TZ" />, <Select.Item label="Lietuvių (Lithuania)" p="$2" value="lt-LT" />, <Select.Item label="Polski" p="$2" value="pl" />, <Select.Item label="Português (Brazil)" p="$2" value="pt-BR" />, <Select.Item label="Português (Portugal)" p="$2" value="pt-PT" />]

When  "de" is selected, user sees "de" on the Input, but I need for it to show "Deutsch" (the label)
It is shown ok on the Select Content items, but not on the selected one.

### Problem Statement

Selected value should show the item "label"

### Proposed Solution or API

Somehow make it work!

**Comment by sandeepgeeky** [comment]
Hi @jacargentina ,

Thank you for reporting, we will look into this.
