### ISSUE TITLE
CONTRIBUTING.md and how to help on development

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#568]
### Description

Would love to help with development

### Steps to reproduce

- Follow CONTRIBUTING.md and trying to run iOS simulator (for developing and testing changes for react-native)
- After `yarn ios`
- Below clic on "SIDEBAR"
- Choose stories/FORMS/Select
- Choose Select
- Clic on "Select Option"

![Simulator Screenshot - iPhone 14 Pro - 2023-06-07 at 16 59 42](https://github.com/gluestack/gluestack-ui/assets/517228/8605579d-4046-4795-ac9c-a97744a6cb53)

### gluestack-ui Version

main branch

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

Tried asking this on Discord but no luck.

I would LOVE to help on development.

**Comment by Viraj-10** [comment]
Hey @jacargentina, please replace fontWeights of `gluestack-ui.config.ts` with following code.
```
 fontWeights: {
        hairline: '100',
        thin: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
        extraBlack: '950',
      },
```

It is due to font weights being in number it should be a string.

**Comment by jacargentina** [comment]
@Viraj-10 worked!, should I make a PR with that change?

**Comment by makkarMeenu** [comment]
@jacargentina No worries, it is done! Closing this issue.
