### ISSUE TITLE
ActionSheet not showing after updating to latest

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#595]
### Description

My ActionSheets where working just fine, broke after updating to  latest

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

I've changed:
`@dank-style/animation-plugin` =>  `@gluestack-style/animation-plugin`
`@dank-style/react` =>  `@gluestack-style/react`

Also did:
`npx gluestack-ui@latest update --all`

**Comment by AshwiniKumar007** [comment]
Hey @jacargentina, Thanks for reporting this.
Ideally it should work. We will check this and update you.

**Comment by makkarMeenu** [comment]
@jacargentina Is it not working in your repository? Is it possible to share the repository?

**Comment by jacargentina** [comment]
https://github.com/jacargentina/iResucito

**Comment by jacargentina** [comment]
I 've solved it by creating an empty new testApp, adding gluestack-ui, adding all components; then:
- Updated gluestack-ui.config.ts with some detected changes
- Removed my components folder, and copied from the new testApp/components

The thing with working on alpha software
