### ISSUE TITLE
Color style not being propagated to the descendants

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#62]
The _spinner property is not propagating the **color** attribute to the 'spinner descendant'. The backgroundColor works well, but color not.

```ts
const Root = styled(Pressable, {
  // ...
  _spinner: {
    color: '#F00', // Not propagated...
    backgroundColor: '#000' // Propagated
  },
  // ...
}, {
  descendantStyle: ['_text', '_spinner', '_icon'],
  ancestorStyle: ['_button'],
});
```

**Comment by AshwiniKumar007** [comment]
Hey @NandoMB, 
Thanks for reporting. We will look into this.

**Comment by NandoMB** [comment]
> Hey @NandoMB, Thanks for reporting. We will look into this.

My pleasure, this library is awesome!

**Comment by mayank-96** [comment]
Duplicate issue #212
