### ISSUE TITLE
Error after install Select/Actionsheet components

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#63]
This error starts to be thrown after I had install these two packages...

```
 ERROR  Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
```

**Comment by AshwiniKumar007** [comment]
Hey @NandoMB ,
Thanks for reporting. We will check this

**Comment by NandoMB** [comment]
Great!

**Comment by mayank-96** [comment]
Hey @NandoMB, this issue has been fixed. Please upgrade your Actionsheet version to 0.2.1.
Closing this issue, feel free to re-open if you any doubts.
