### ISSUE TITLE
State changes for style prop in Pressable are not triggering when pressing on the element

### ISSUE THREAD

**Issue by freddybreitenstein** [gluestack/gluestack-ui#659]
### Description

Pressable from react-native is properly triggering press events for style prop but gluestack isn't. Because of this you can't apply styling when pressing the element

### Steps to reproduce

1. Create a custom component with Pressable with some styling like a background color
2. Add the a style prop: `style={({pressed}) => pressed ? {opacity: 0.5} : {}}
3. Notice that the style never changes

Works with Pressable from react-native

### gluestack-ui Version

Pressable: 0.1.5, gluestack-ui/react: 0.1.23

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by makkarMeenu** [comment]
Hey @freddybreitenstein , thanks for reporting. We will look into `Pressable` issues today and try to fix it ASAP.

**Comment by makkarMeenu** [comment]
This is fixed in the latest version of pressable. Feel free to re-open if you face any issue.

**Comment by rishabhgupta** [comment]
is this fixed, i am still facing this issue.
