### ISSUE TITLE
Typescript errors in provider@0.1.5 and toast@0.1.10

### ISSUE THREAD

**Issue by daviddripps** [gluestack/gluestack-ui#706]
### Description

latest versions of packages throw errors in tsc

### Steps to reproduce

1. `npx create-expo-app -t expo-template-blank-typescript`
2. Follow Steps 1 & 2 in the [gluestack-ui Expo Installation instructions](https://ui.gluestack.io/docs/getting-started/install-expo)
3. `npm install @gluestack-ui/provider@0.1.4 @gluestack-ui/toast@0.1.9`
4. `npx tsc` - See there are no Typescript errors
5. `npm install @gluestack-ui/provider@latest @gluestack-ui/toast@latest`
6. `npx tsc` - See that Typescript cannot find declaration files

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

I created a repository at the link below with repro steps 1-3 for quicker testing. Just `npm install @gluestack-ui/provider@latest @gluestack-ui/toast@latest && npx tsc` to repro.
https://github.com/daviddripps/gluestack-test

**Comment by Viraj-10** [comment]
Hey @daviddripps, Thanks for reporting this issue. We will look into this.

**Comment by daviddripps** [comment]
Thanks. Happy to answer questions or jump on a Zoom to repro if that would be helpful.

**Comment by makkarMeenu** [comment]
Can you check if this still exists in latest version of `Toast` and `Provider`?

**Comment by daviddripps** [comment]
It's fixed now. Thanks!
