### ISSUE TITLE
Can't update to latest components

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#707]
### Description

It was working, not anymore

### Steps to reproduce

<img width="1077" alt="Captura de pantalla 2023-06-27 a la(s) 13 40 03" src="https://github.com/gluestack/gluestack-ui/assets/517228/00fb0c13-6283-4d99-9b11-610f18e4de72">

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

I was using this command to keep using latest fixes; now it is giving me error

Component "--all" not found.

**Comment by mfrfinbox** [comment]
I can't even install using `npx gluestack-ui@latest`

**Comment by Viraj-10** [comment]
Hey @jacargentina, @mfrfinbox, Thanks for reporting this issue. We will have a look.

**Comment by jacargentina** [comment]
@Viraj-10  tried again the update , and now it works.

<img width="340" alt="Captura de pantalla 2023-07-03 a la(s) 16 53 02" src="https://github.com/gluestack/gluestack-ui/assets/517228/57269dfe-1e61-427f-abf5-19358d852195">

**Comment by akash3gtm** [comment]
@jacargentina 
Hope this issue is resolved, we are closing this for now.

@mfrfinbox If the issue still persists, inform us and we will re-open the issue.
