### ISSUE TITLE
 Error: ENOENT: no such file or directory, open 'gluestack/cache/gluestack-ui/example/storybook/src/ui-components/Hstack/config.json'

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [gluestack/gluestack-ui#731]
### Description

can not add HStack or VStack missing in storybook 

### Steps to reproduce

1. yarn create expo-app
2.npx gluestack-ui@latest init
3.Installs the required dependencies: @gluestack-style/react, @gluestack-style/animation-plugin, and @gluestack-ui/provider.
4. import { Text } from "react-native"
import { GluestackUIProvider } from "./components"
import { config } from "./gluestack-ui.config"

export default function App() {
  return (
    <GluestackUIProvider config={config.theme}>
      <Text>Hello World!</Text>
    </GluestackUIProvider>
  )
}

### gluestack-ui Version

5- npx expo start 
6- npx gluestack-ui@latest add hstack also npx gluestack-ui@latest add HStack also npx gluestack-ui@latest add Hstack

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

hello anyone can help? i create expo app by yarn then i used npx gluestack-ui@latest init then i use official code 
<import { Text } from 'react-native';
import { GluestackUIProvider } from './components';
import { config } from './gluestack-ui.config';

export default function App() {
  return (
    <GluestackUIProvider config={config.theme}>
      <Text>Hello World!</Text>
    </GluestackUIProvider>
  );
}>
then I add many components but HStack and VStack give me errors as in the pictures till I try to choose it from the core component. also need an example to add gluestack in existing javaScript  expo app  
![Screenshot from 2023-07-01 14-41-45](https://github.com/gluestack/gluestack-ui/assets/76538677/d95ce29c-891a-4b4d-b8a1-cbdb0da25772)
![Screenshot from 2023-07-01 14-38-39](https://github.com/gluestack/gluestack-ui/assets/76538677/6e34cc88-a48d-4271-91c4-d7a2bca6e6a2)
![Screenshot from 2023-07-01 14-35-03](https://github.com/gluestack/gluestack-ui/assets/76538677/01404da3-b388-4968-ae2f-2b201e10c57c)
anyone

**Comment by Viraj-10** [comment]
Hey @Ahmed-Ibrahim-Anter, Thanks for reporting this issue. We will have a look.

**Comment by vidhi499** [comment]
Hey @Ahmed-Ibrahim-Anter This issue is fixed in the latest release of `gluestack-ui`. Try running `npx gluestack-ui@latest add hstack` and feel free to reach out to us if this issue persists.

**Comment by Ahmed-Ibrahim-Anter** [comment]
still face it 
![Screenshot from 2023-07-15 06-01-27](https://github.com/gluestack/gluestack-ui/assets/76538677/f6381aab-396a-4c07-8fae-408dda0426c1)
