### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGSvgView

### ISSUE THREAD

**Issue by AllBitsEqual** [gluestack/gluestack-ui#762]
### Description

Using GluestackUI in a clean new projekt with Expo SDK 49 causes a rendering issue when implementing the provider

### CodeSandbox/Snack link

https://github.com/AllBitsEqual/Prototyping/tree/gluestack/gluestack

### Steps to reproduce

either follow the link above for my demo repo with a clean new project or complete the following steps:

1. create new expo project: `npx create-expo-app@latest --template expo-template-blank-typescript@sdk-49`
2. install missing packages, pick name, cd into project
3. install expo router requirements `yarn expo install expo-router react-native-safe-area-context react-native-screens expo-linking expo-constants expo-status-bar react-native-gesture-handler`
4. (optional) install requirements for web `yarn expo install react-native-web@~0.19.6 react-dom@18.2.0`
5. follow other changes from https://docs.expo.dev/routing/installation/ (change package.json, app.json and babel.config.js as described)
6. install gluestack UI `npx gluestack-ui@latest`
7. start project and run it in your emulator (web doesn't seem to be affected)
8. make a page (optional with a base _layout.tsx) and implement the provider `<GluestackUIProvider config={config.theme}>`
9. update the app in your emulator and the error should occur 

![image](https://github.com/gluestack/gluestack-ui/assets/43298587/cef8dd41-0ca3-443c-a07a-6ef96466318e)

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by AllBitsEqual** [comment]
a temporary fix is to downgrade `react-native-svg` to `13.4.0`

**Comment by rbinksy** [comment]
Hi @makkarMeenu. I think this issue still needs to be resolved. Can you re-open it? The fix above is only temporary. 

Considering Expo is now the default way to create React native apps, I suspect many folks will encounter the same issue, especially as this occurs in the latest expo release.

**Comment by fdfontes** [comment]
When I downgrade `react-native-svg` to `13.4.0`, I get another error: `Invariant Violation: requireNativeComponent: "RNSVGSvgView" was not found in the UIManager.` Has anyone found a solution that doesn't lead you right back to `Tried to register two views with the same name RNSVGSvgView` ?

**Comment by Musta-Pollo** [comment]
Same for me

**Comment by Jore** [comment]
Yeah this is still an issue for me.

**Comment by wallacerenan** [comment]
temporary fix:

rm -rf node_modules

include this on your package.json

 "resolutions": {
    "react-native-svg": "13.4.0"
  },
  overrides: {
      "react-native-svg": "13.4.0"
  }

run [yarn/npm] install

**Comment by fdfontes** [comment]
> include this on your package.json
> 
> "resolutions": { "react-native-svg": "13.4.0" }, overrides: { "react-native-svg": "13.4.0" }

Unfortunately, it didn't work for me. I cleared package-lock.json as well. No luck.

**Comment by juliusbangert** [comment]
This is still an issue for me. I'd like to use the latest version of expo and all the correct versions of packages for that managed workflow. I'd also like to use glue stack. Any updates would be greatly appreciated.

**Comment by OmarFaruk-0x01** [comment]
I am facing the same issue. Any updates?

**Comment by periabyte** [comment]
> temporary fix:
> 
> rm -rf node_modules
> 
> include this on your package.json
> 
> "resolutions": { "react-native-svg": "13.4.0" }, overrides: { "react-native-svg": "13.4.0" }
> 
> run [yarn/npm] install

I tried to use this as a fix, but it didn't work, what worked was this

```json
"resolutions": {
    "@gluestack-ui/react/**/react-native-svg": "13.9.0"
  },
```

**Comment by mrvisser** [comment]
I suppose a proper fix is all dependencies to react-native-svg need to be peer dependencies, or use a looser version expression.

For example, the fab spec is `13.4.0`, but that could be `^13.4.0` instead and would allow minor version bumps to be still be hoisted.

**Comment by GollyJer** [comment]
This is super frustrating.  I can't get this to work at all using `yarn` with Expo v49.

**Comment by GollyJer** [comment]
Figured out how to use new `yarn` functionality to force 13.4.0 to resolve to 13.9.0.
`yarn set resolution react-native-svg@npm:13.4.0 npm:13.9.0`

Decent workaround for now. No unexpected errors yet.

**Comment by Viraj-10** [comment]
I tried to reproduce this issue but I was unable to do it.
Steps I followed to reproduce. 

- `npx create-expo-app@latest --template expo-template-blank-typescript@sdk-49`.
- `npm i @gluestack-ui/themed react-native-svg@13.4.0`
- Updated my App.tsx

```
import { GluestackUIProvider, Text, Box, config } from "@gluestack-ui/themed";

export default function App() {
  return (
    <GluestackUIProvider config={config.theme}>
      <Box width="100%" justifyContent="center" alignItems="center" flex={1}>
        <Text>Open up App.js to start working on your app!</Text>
      </Box>
    </GluestackUIProvider>
  );
}
```

- `npm run android -c`.

PS:- `@gluestack-ui/themed` is currently locked to `react-native-svg` version `13.4.0`. We are working on removing lock version till then please make sure you have right version installed in your project. Best Way to check version is to `package.json` inside your `node_modules/react-native-svg`.

**Comment by bvisserbb** [comment]
I see you've added it to expo, but it's not in the RN existing project installation instructions yet: https://ui.gluestack.io/docs/guides/install-rn

**Comment by njt1982** [comment]
I had to switch from 13.13 to 13.4.0 (and do a pod install, too) to get the icons to work.

Weirdly, looking in package-lock, I could see `@gluestack-ui` entries for that specific version inside a nested node_modules folder as well as my own 13.13.x version.

I dont think this should be closed...  I think a good outcome would either be:

a) Properly enforce dependencies so that the right version is automatically loaded without us needing to manually include precisely the right one at the top level...
or
b) Fix whatever that bug is that causes the duplicate views (guessing it's because the same package is loaded twice, but with different versions).

I suspect there is a world where the final fix combines both A and B ;)

**Comment by njt1982** [comment]
Looks like same bug here? https://github.com/gluestack/gluestack-ui/issues/868

**Comment by Viraj-10** [comment]
> > PS:- @gluestack-ui/themed is currently locked to react-native-svg version 13.4.0. We are working on removing lock version till then please make sure you have right version installed in your project. Best Way to check version is to package.json inside your node_modules/react-native-svg.
> 
> @Viraj-10 this lock to 13.4.0 is the issue being reported here. Why close this ticket when this issue isn't resolved? Are you able to link to another issue that is tracking the removal of the 13.4.0 lock?
> 
> At least update the documentation for themed to say it won't work if you have a different version of react-native-svg?

Hey @bvisserbb, This issue is different. It is comes under critical issue since this crashes your app. 
Moving from locking version doesn't come under this. I have reported this internally and we have it in our roadmap. Sorry I didn't create a issue on github which points the same. #995 here I have created a issue.

**Comment by njt1982** [comment]
@Viraj-10 nice! Thanks for responding so quickly.
