### ISSUE TITLE
next.js withGluestack fails in nx monorepo

### ISSUE THREAD

**Issue by Evanion** [gluestack/gluestack-ui#763]
### Description

service next fails due to withGluestack looking for `node_modules` in the wrong location

### Steps to reproduce

* generate a new nx repo with next.js:
  `npx create-nx-workspace@latest` &&
  `nx g @nx/next:app frontend`

* follow instructons to add gluestack manually
* follow the code in template repo to make sure everything is correct `https://github.com/gluestack/gluestack-ui-nextjs-app-router-template`
* start serving the app `nx serve frontend`

```bash
nx serve frontend

> nx run frontend:serve:development

- ready started server on 0.0.0.0:4200, url: http://localhost:4200
Error: ENOENT: no such file or directory, scandir '/Users/evanion/Projects/Personal/courses/courses/apps/frontend/node_modules'
    at Object.readdirSync (node:fs:1446:3)
    at traverseFolder (/Users/evanion/Projects/Personal/courses/courses/node_modules/@gluestack/ui-next-adapter/dist/ui-next-adapter.cjs.development.js:63:18)
    at getExactDependenciesFromNodeModules (/Users/evanion/Projects/Personal/courses/courses/node_modules/@gluestack/ui-next-adapter/dist/ui-next-adapter.cjs.development.js:82:25)
    at withGluestackUI (/Users/evanion/Projects/Personal/courses/courses/node_modules/@gluestack/ui-next-adapter/dist/ui-next-adapter.cjs.development.js:159:33)
    at /Users/evanion/Projects/Personal/courses/courses/node_modules/@nx/next/src/utils/compose-plugins.js:12:40
    at Generator.next (<anonymous>)
    at fulfilled (/Users/evanion/Projects/Personal/courses/courses/node_modules/tslib/tslib.js:164:62) {
  type: 'Error',
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/evanion/Projects/Personal/courses/courses/apps/frontend/node_modules'
}
 >  NX   Next.js app exited with code 1
   Pass --verbose to see the stacktrace.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project frontend failed

   Failed tasks:
   
   - frontend:serve:development
   
   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at https://cloud.nx.app/runs/7PgIjSlgnd
   ```

### gluestack-ui Version

2.1.5

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [X] Next

### Other Platform

nx

### Additional Information

It seems like `withGluestack` is looking in the project root, but it's located two directories up, but I can't find any config that I can pass to tell gluestack where to look, and it seems like the yarn workspace package doesn't support nx.

**Comment by makkarMeenu** [comment]
Hi @Evanion , I was able to run next project with gluestack with nx monorepo.  Although, I don't have much idea about nx-monorepo. Can you please share the next config file and the project structure?

**Comment by Evanion** [comment]
@makkarMeenu here is a reproduction repo with nx, next and gluestack
https://github.com/Evanion/reprod-gluestack

When the `withGluestackUI` is commented out, it fails to load the react-native parts, and with the `withGluestackUI` plugin enabled,  it fails with `Error: ENOENT: no such file or directory, scandir '<path to repo root>/apps/frontend/node_modules'`

**Comment by Evanion** [comment]
Had to reorder and place the `withGluestackUI` plugin before `withNx` plugin. And now it works, thank!
