### ISSUE TITLE
Input's type is error

### ISSUE THREAD

**Issue by zfben** [gluestack/gluestack-ui#764]
### Description

Input component display error.

### Steps to reproduce

Code is:
```tsx
<Input>
  <Input.Input />
</Input>
```
Error is:
![image](https://github.com/gluestack/gluestack-ui/assets/215433/d2d2a793-6bc4-4377-8098-142011e1ca6c)

### gluestack-ui Version

0.1.9

### Platform

- [X] Android
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by makkarMeenu** [comment]
Please re-open the issue if you still face the same.
