### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'gluestack/cache/gluestack-ui/example/storybook/src/ui-components/Hstack/config.json'

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [gluestack/gluestack-ui#782]
### Description

Error: ENOENT: no such file or directory, open 'gluestack/cache/gluestack-ui/example/storybook/src/ui-components/Hstack/config.json'

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next
![Screenshot from 2023-07-15 06-09-56](https://github.com/gluestack/gluestack-ui/assets/76538677/8fbd36a4-9eb7-40c5-b26a-32bf585f1411)
![Screenshot from 2023-07-15 06-10-12](https://github.com/gluestack/gluestack-ui/assets/76538677/c5e9b001-423f-4962-9ea2-6ac9f00d224f)

### Additional Information

[https://github.com/gluestack/gluestack-ui/issues/731#issue-1783847331](url)
still facing the problem even taking it from your core

**Comment by Ahmed-Ibrahim-Anter** [comment]
even with pnpm 
![Screenshot from 2023-07-15 22-24-44](https://github.com/gluestack/gluestack-ui/assets/76538677/e38352de-d982-4a4f-b3a4-d43a0508b31d)

**Comment by surajahmed** [comment]
@Ahmed-Ibrahim-Anter Thanks for reporting. We'll have a look. 
For now, Can you please try cleaning up the cache once?
```rm -rf ~/.gluestack/cache```

**Comment by Ahmed-Ibrahim-Anter** [comment]
@surajahmed 
![Screenshot from 2023-07-18 01-25-48](https://github.com/gluestack/gluestack-ui/assets/76538677/56d1ae13-fc9e-4bf9-9748-8b3885a449b2)
![Screenshot from 2023-07-18 01-26-35](https://github.com/gluestack/gluestack-ui/assets/76538677/a8e260ab-3579-454a-81a5-41fdc5020c02)

**Comment by yaojiach** [comment]
I've encountered the same error.

**Comment by Ali-Aref** [comment]
Same here! **I got the error** while adding the `hstack` as `npx gluestack-ui@latest add hstack` as 
```
➜ npx gluestack-ui@latest add hstack
┌  gluestack-ui
│
◇  Repository already cloned.
│
◇  Git pull successful.
│
◆  gluestack-ui is already initialized in your project!
│
■  The hstack does not exists. Kindly choose from the below list.
│
■  Error: ENOENT: no such file or directory, open '/home/ali/.gluestack/cache/gluestack-ui/
example/storybook/src/ui-components/Hstack/config.json'
...
```

**Comment by Ali-Aref** [comment]
I found a **temporary solution** for my self and wanted to share here too.
the messages says that `no such file or directory, open '/home/ali/.gluestack/cache/gluestack-ui/example/storybook/src/ui-components/Hstack/config.json'` 

so  I check the location that was right there is a folder named `HStack` but **not  `Hstack`**
then I renamed the folder `HStack` to `Hstack` and re-run the command
```
npx gluestack-ui@latest add hstack
```
and that worked for me!

**Comment by makkarMeenu** [comment]
We have bundled the library to `@gluestack-ui/react` which exports all the components. Please look into installation steps will solve this issue.
