### ISSUE TITLE
Input placeholderTextColor prop does not get the color from the theme tokens

### ISSUE THREAD

**Issue by schmitzc** [gluestack/gluestack-ui#829]
### Description

Invalid prop `placeholderTextColor` warning for Input component

### Steps to reproduce

components/core/Input/styled-components/Input.tsx:

```
// @ts-nocheck
import { styled } from '../../styled';
import { TextInput } from 'react-native';

export default styled(
  TextInput,
  {
    flex: 1,
    color: '$textLight900',
    props: {
      placeholderTextColor: '$textLight500',
    },
    _dark: {
      color: '$textDark50',
      props: {
        placeholderTextColor: '$textDark400',
      },
    },
    _web: {
      'cursor': 'text',
      ':disabled': {
        cursor: 'not-allowed',
      },
    },
  },
  { ancestorStyle: ['_input'], resolveProps: ['placeholderTextColor'] },
  {
    propertyTokenMap: {
      placeholderTextColor: 'colors',
    },
  }
);
```

1. Add the Input component to your view 
2. You will get the following error: "Warning: Failed prop type: Invalid prop `placeholderTextColor` supplied to `TextInput`: $textLight500"

### gluestack-ui Version

0.1.9 (@gluestack-ui/input)

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by AshwiniKumar007** [comment]
Hey @schmitzc , Thanks for reporting.
We will fix this

**Comment by Ali-Aref** [comment]
+1 The same issue!

**Comment by lzychowski** [comment]
+1

**Comment by jihyundotkim** [comment]
Experiencing same issue with non-Expo Android build

**Comment by njt1982** [comment]
Hi - what is the rough fix needed here? Is it passing the raw `$textLight500` through to RN without applying the style?

**Comment by jihyundotkim** [comment]
> Hi - what is the rough fix needed here? Is it passing the raw `$textLight500` through to RN without applying the style?

I don't know if this helps but my temporary fix was just commenting out the `placeholderTextColor: '$textLight500',`
in `themed/build/components/Input/styled-components/Input.js`

**Comment by njt1982** [comment]
It seems to be [a valid property](https://reactnative.dev/docs/textinput#placeholdertextcolor) - so I'm wondering if there is a bug somewhere that's causing the property value to not be parsed from that token to its value?

**Comment by jihyundotkim** [comment]
> It seems to be [a valid property](https://reactnative.dev/docs/textinput#placeholdertextcolor) - so I'm wondering if there is a bug somewhere that's causing the property value to not be parsed from that token to its value?

I'm not sure about that but when I override the `placeholderTextColor` in `gluestack-ui.config.ts` like so:

```
  components: {
    InputField: {
      theme: {
        props: {
          placeholderTextColor: '#eeeeee'
        }
      }
    }
  },
```

VSCode will mark it as error saying not assignable to type defined at `@gluestack-style/react/lib/typescript/types.d.ts`
at line 147 `GlobalVariantSX`
but when I actually run it, no error. So you're right that `placeholderTextColor` is a valid property, perhaps it was left out somewhere in the type definitions and that is causing the token to not bind? (because `color:'$textLight900'` doesn't cause an error, so it's not having problem getting the colors from the tokens.)

Anyway this would be a better temporary solution.

**Comment by njt1982** [comment]
That's a much nicer (temporary) solution than telling RN to ignore the warning :) Thanks @jihyundotkim

**Comment by makkarMeenu** [comment]
This is fixed in the latest version of `@gluestack-ui/themed` and `@gluestack-style/react` .

**Comment by JJosephttg** [comment]
`@gluestack-style/react` version 1.0.32 reintroduced this issue. I am now noticing this issue without any theme config changes
