### ISSUE TITLE
Tooltip gives error on docs

### ISSUE THREAD

**Issue by Ali-Aref** [gluestack/gluestack-ui#838]
### Description

Tooltips gives error on docs

### gluestack-ui Version

latest

### Additional Information

When I go to the glustack ui docs [tooltip](https://ui.gluestack.io/docs/components/overlay/tooltip) and hover the button it gives the `Application error: a client-side exception has occurred (see the browser console for more information).`

**Comment by Viraj-10** [comment]
Hey @Ali-Aref, Thanks for reporting the issue. We will have a look.

**Comment by jj-dominguez** [comment]
It's pretty straightforward  if you look at the actual error, just a self-closing tag instead of an end tag for the Tooltip.Content:

```_app-67ff8e93f9a415be.js:128 Error! prettier failed:  SyntaxError: JSX element 'Tooltip.Content' has no corresponding closing tag. (17:6)
  15 | export default () => (
  16 |   <Tooltip>
> 17 |     <Tooltip.Content >
     |      ^
  18 |      <Tooltip.Text />
  19 |      <Tooltip.Content />
  20 |   </Tooltip>```

**Comment by sandeepgeeky** [comment]
Hi ,  thank you for reporting .
We are working on improving the api so this might change all together .
As of now i am closing this issue .
