### ISSUE TITLE
Docs should explain downloading and updating glue stack

### ISSUE THREAD

**Issue by Seanmclem** [gluestack/gluestack-ui#842]
### Description

Installation instructions, make mention of installing, but not updating. When installing, it seems to download many directories of components, while also installing packages. It is unclear how these get updated, or why they download them this way instead of just using packages installed. Is it so I can modify them manually if I want to? And wouldn’t doing so make them difficult to download/install updates if I’ve modified them? I don’t really see any explanation about this.

### Problem Statement

See description

### Proposed Solution or API

Have explainers about why they download in this way, and make mention on installation, instructions regarding updating instructions

### Additional Information

Individual components seem to make mention of individually updating them. More globally, applicable update reference might make sense on other installation pages like expo.

mentions individually updating component https://ui.gluestack.io/docs/components/typography/text

Doesn’t mention globally updating at all https://ui.gluestack.io/docs/getting-started/install-expo

**Comment by makkarMeenu** [comment]
@Seanmclem Thanks for the feedback. We are working on the smooth onboarding of an app using gluestack-ui.
To help you a bit, the commands to update all the components and few others are listed on https://ui.gluestack.io/docs/advanced/gluestack-ui-cli.

**Comment by Seanmclem** [comment]
> @Seanmclem Thanks for the feedback. We are working on the smooth onboarding of an app using gluestack-ui.
> 
> To help you a bit, the commands to update all the components and few others are listed on https://ui.gluestack.io/docs/advanced/gluestack-ui-cli. 

Thanks! I should have, but never really thought to look at the CLI documentation

**Comment by selique** [comment]
this url its down (404) https://ui.gluestack.io/docs/advanced/gluestack-ui-cli

**Comment by selique** [comment]
este url está desativado (404) https://ui.gluestack.io/docs/advanced/gluestack-ui-cli



> @SeanmclemObrigado pelo feedback. Estamos trabalhando na integração suave de um aplicativo usando gluestack-ui. Para te ajudar um pouco, os comandos para atualizar todos os componentes e alguns outros estão listados em https://ui.gluestack.io/docs/advanced/gluestack-ui-cli .


este url está desativado (404)
