### ISSUE TITLE
Button.Text not inheriting styles from sx prop on Button

### ISSUE THREAD

**Issue by reggieofarrell** [gluestack/gluestack-ui#843]
### Description

Button.Text not inheriting styles from sx prop on Button

### Steps to reproduce

1. Create a custom button component that extends the GlueStack UI Button component
2. Attempt to style the text in `Button.Text` via the `sx` prop on the Button

I'm trying to migrate our components that were built with NativeBase to GlueStack. The `Button.Text` component doesn't seem to be inheriting styles passed in the `sx._text` prop of the `Button`. The GlueStack UI docs aren't clear about this particular pattern, but it seems like this should work...

```typescript
import {Button} from '@/components/gluestack'

type TButtonProps = React.ComponentProps<typeof Button>

interface SolidButtonProps extends TButtonProps {
  Icon?: React.ReactNode
}

export const SolidButton = ({
  children,
  Icon,
  ...otherProps
}: SolidButtonProps) => {
  return (
    <Button
      my={10}
      borderRadius="$full"
      sx={{
        _text: {
          fontFamily: '$body',
          fontWeight: '$bold',
          fontSize: '$xs',
          color: '$red500',
          ':disabled': {
            color: '$grey',
          },
          lineHeight: '$sm',
        },
        ':disabled': {
          opacity: 1,
          bg: '#DFDFDF',
        },
      }}
      variant="solid"
      size="lg"
      {...otherProps}
    >
      <Button.Text>
        {children}
      </Button.Text>
      {Icon && <Button.Icon as={Icon} ml={10} />}
    </Button>
  )
}
```

What does work is directly styling the `Button.Text` component like this...

```typescript

<Button.Text
  fontFamily="$body"
  sx={{
    fontWeight: '$bold',
    fontSize: '$xs',
    color: '$red500',
    ':disabled': {
      color: '$grey',
    },
    lineHeight: '$sm',
  }}
>
  {children}
</Button.Text>
```

But what I'm trying to achieve here is our own `SolidButton` component that can be further modified as needed by passing different style props to it such as a different text color or fontFamily, etc.  The `sx` prop on the `Button.Text` component also doesn't seem to accept the `fontFamily` property although the typings suggest it does. It just doesn't work. `fontFamily` does work as a direct prop of `Button.Text` though.

Is this a bug or am I completely missing the mark here?

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by sandeepgeeky** [comment]
Hey @reggieofarrell , Thanks for reporting the issue. We will have a look.

**Comment by reggieofarrell** [comment]
@sandeepgeeky FYI, I also tried building my own button component from scratch with gluestack-style and ran into a possibly related bug...

https://github.com/gluestack/gluestack-style/issues/314

**Comment by makkarMeenu** [comment]
Hey @reggieofarrell , please upgrade the `@gluestack-style/react` version to `0.2.1` . It should solve the above issue. Let us know if it still persists with minimal reproducible issue in [this](https://snack.expo.dev/@gluestack/gluestack-ui-todos-example?platform=web&theme=dark) snack.

**Comment by reggieofarrell** [comment]
@makkarMeenu @sandeepgeeky  I did the update and the issue still persists. I tried to create a Snack for you, but it crashes anytime I add style props to the Button that is exported from `@gluestack-ui/themed`...

https://snack.expo.dev/@reggiegovside/gluestack-ui-overrides-bug

I can confirm that the issue still persists in my codebase though. The latest version `0.2.3` also did not fix the issue I filed in the `@gluestack-style/react` repo that I believe is related to this...

https://github.com/gluestack/gluestack-style/issues/314

I was able to create a working Snack for that issue which I left in the comments there.

**Comment by reggieofarrell** [comment]
@makkarMeenu @sandeepgeeky Can we please re-open this issue?

**Comment by reggieofarrell** [comment]
This appears to be fixed with the latest GlueStack Style version `2.0.11`

**Comment by aminta** [comment]
Same issue here.

package.json:

```
  "dependencies": {
    "@gluestack-ui/themed": "latest",
    "@gluestack-ui/utils": "^0.1.8",
    "@gluestack-ui/react": "*",
    "@types/react-native": "0.72.2",
    "@gluestack-style/react": "latest",
    "expo": "^49.0.0",
    "expo-font": "~11.4.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-svg": "^13.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-native-svg-transformer": "^1.1.0",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
```
