### ISSUE TITLE
Unable to install on existing Expo project

### ISSUE THREAD

**Issue by speedhawk21** [gluestack/gluestack-ui#845]
### Description

When running the install command `npx gluestack-ui@latest` on an existing project, I receive an error stating `npm ERR! could not determine executable to run`.

### Steps to reproduce

Manual
If you wish to install gluestack-ui into your existing project, you can proceed with the following steps:

Step 1: Installation and Initial Setup

First, install the latest version of gluestack-ui in your project. This can be done using the following command:
npx gluestack-ui@latest

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

0 verbose cli [
0 verbose cli   '/Users/briansc/.nvm/versions/node/v16.14.1/bin/node',
0 verbose cli   '/Users/briansc/.nvm/versions/node/v16.14.1/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'gluestack-ui@latest'
0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.1

29 http fetch GET 200 https://registry.npmjs.org/gluestack-ui 343ms (cache revalidated)
30 timing command:exec Completed in 355ms
31 verbose stack Error: could not determine executable to run
31 verbose stack     at getBinFromManifest (/Users/briansc/.nvm/versions/node/v16.14.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
31 verbose stack     at exec (/Users/briansc/.nvm/versions/node/v16.14.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:115:15)
31 verbose stack     at async module.exports (/Users/briansc/.nvm/versions/node/v16.14.1/lib/node_modules/npm/lib/cli.js:66:5)
32 verbose pkgid gluestack-ui@0.4.10-alpha.0
33 verbose cwd /Users/briansc/projects/flipper/mobile
34 verbose Darwin 22.5.0
35 verbose argv "/Users/briansc/.nvm/versions/node/v16.14.1/bin/node" "/Users/briansc/.nvm/versions/node/v16.14.1/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "gluestack-ui@latest"
36 verbose node v16.14.1
37 verbose npm  v8.5.0
**38 error could not determine executable to run**
39 verbose exit 1
40 timing npm Completed in 842ms
41 verbose code 1
42 error A complete log of this run can be found in:
42 error     /Users/briansc/.npm/_logs/2023-08-08T19_36_53_648Z-debug-0.log

**Comment by andragh83** [comment]
Having the same issue - I think it is because there's a dependency conflict where gluestack-ui@"0.4.10-alpha.0" requires "react-native": "^0.80" (latest rn version is 0.72.3) so probably a typo?

**Comment by OmarFaruk-0x01** [comment]
@speedhawk21  you need to specify the exact version tag instead of the latest. something like this `npx gluestack-ui@0.4.10 init`

**Comment by ameyarumbleon** [comment]
Hi I am getting an error , command not found: gluestack-ui, I have an expo project .

**Comment by vidhi499** [comment]
The above issue is fixed in version 0.4.11, try using `npx gluestack-ui@latest` and feel free to reach out to us if there are any issues.
