### ISSUE TITLE
Types names should be more consistant

### ISSUE THREAD

**Issue by Nooka10** [gluestack/gluestack-ui#848]
### Description

Hi,

I'm using Gluestack with typescript and I found that the types names are a bit inconsistant.
Sometimes, you use `IntefaceXProps`, some other, it's `IXProps`. Sometimes there is a `InterfaceXProps` and a `IXProps` exported...
I think you should choose one way or another but use and export only one when you use both in your code, and it should be always the same everywhere.

Here are some examples:
InterfaceButtonProps (exported despite there is also a IButtonProps, is that normal?)
IButtonGroupProps

InterfaceFormControlProps (exported despite there is also a IFormControlProps, is that normal?)
IFormControlLabelProps

InterfaceModalProps
IModalContentProps

### Problem Statement

It's confusing and make the types hard to find to use multiple types name conventions...

### Proposed Solution or API

I think you should decide to use either `InterfacexProps` or `IXProps` and use (or at least export) only types following this name convention.

**Comment by makkarMeenu** [comment]
@Nooka10 We will consider this and try to be uniform throughout.

**Comment by likeSo** [comment]
I need this too! In Native Base, i use `IPressableProps` and i can extends this type.
But in gluestack, i cannot find a type suck like that...

**Comment by surajahmed** [comment]
Thanks for reporting this.
`@gluestack-ui/themed` exports React components. If you need component props typing, you can do something like this.
```
import {Button} from '@gluestack-ui/themed';
type ButtonProps = React.ComponentProps<typeof Button>;
```
