### ISSUE TITLE
Tooltip not working on site

### ISSUE THREAD

**Issue by N0N4T0** [gluestack/gluestack-ui#851]
### Description

Tooltip hover threw an error.

### Steps to reproduce

1. Go to [Tooltip Docs](https://ui.gluestack.io/docs/components/overlay/tooltip)
2. Find the  component **Hover on me!** . 
3. Hover the component **Hover on me!** .   
4. Select any **placement**
5. See error

### gluestack-ui Version

0

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

Site

### Additional Information

![tooltip](https://github.com/gluestack/gluestack-ui/assets/39486464/5a918627-3030-4c98-a2c8-f7d26f9997a3)

**Comment by sandeepgeeky** [comment]
Hey @N0N4T0  , Thanks for reporting the issue. We will have a look.

**Comment by sandeepgeeky** [comment]
Hi , thank you for reporting .
We are working on improving the api so this might change all together .
As of now i am closing this issue .
