### ISSUE TITLE
Headers for React Native installation are swapped

### ISSUE THREAD

**Issue by LuizCristino** [gluestack/gluestack-ui#860]
### Description

The title of the installation process for React Native are swapped

### Steps to reproduce

1. Go to https://ui.gluestack.io/docs/getting-started/install-rn
2. Read the titles and then their descriptions

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by makkarMeenu** [comment]
@LuizCristino Thanks for reporting, will fix this asap.
