### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager

### ISSUE THREAD

**Issue by thalesgaldino** [gluestack/gluestack-ui#868]
### Description

When I add Icons to the input it crashes

### Steps to reproduce

Issue in this repo: https://github.com/thalesgaldino/demoapp

I you go to src/SearchHeader.tsx and in line 33 you add:

```
<InputIcon pl="$3">
    <Icon as={SearchIcon} />
  </InputIcon>
```

then, icons will break: Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager

seems to be related to this: https://github.com/software-mansion/react-native-svg/issues/2101

### gluestack-ui Version

0.1.3

### Platform

- [X] Android
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by secreter** [comment]
mark

**Comment by Konseyy** [comment]
Managed to get it working by installing `react-native-svg@13.4.0`

**Comment by thalesgaldino** [comment]
> Managed to get it working by installing `react-native-svg@13.4.0`

That is the current default default version in gluestack, which I tried initially and had the same issue. Then, I bumped to newer version but no luck. Do you mean you installed manually that version?

**Comment by makkarMeenu** [comment]
This is a duplicate issue for https://github.com/gluestack/gluestack-ui/issues/995. Updates are being provided on that one.
