### ISSUE TITLE
【BUG】Type '{ w: string; h: string; bg: string; }' is not assignable to type 

### ISSUE THREAD

**Issue by ryuji-orca** [gluestack/gluestack-ui#873]
### Description

Type error occurs

### Steps to reproduce

Set up as documented and copy and paste the Box.

```
<Box w="$20" h="$20" bg="$blue500" />
```

The given error translates to.

Type '{ w: string; h: string; bg: string; }' is not assignable to type 'IntrinsicAttributes & Omit<ViewProps, never> & Partial<ComponentProps<StyleProp<ViewStyle>, unknown, ViewProps>> & Partial<...> & { ...; } & RefAttributes<...>'.
I was expecting a type matching IntrinsicAttributes & Omit<ViewProps, never> & Partial<ComponentProps<StyleProp<ViewStyle>, unknown, ViewProps>> & Partial<...> & { ...; } & RefAttributes<...>, but instead you passed { w: string; h: string; bg: string; }.

Property 'w' does not exist on type 'IntrinsicAttributes & Omit<ViewProps, never> & Partial<ComponentProps<StyleProp<ViewStyle>, unknown, ViewProps>> & Partial<...> & { ...; } & RefAttributes<...>'.
You're trying to access w on an object that doesn't contain it. Learn more.

Type '{ w: string; h: string; bg: string; }' is not assignable to type 'IntrinsicAttributes & Omit<ViewProps, never> & Partial<ComponentProps<StyleProp<ViewStyle>, unknown, ViewProps>> & Partial<...> & { ...; } & RefAttributes<...>'.
  Property 'w' does not exist on type 'IntrinsicAttributes & Omit<ViewProps, never> & Partial<ComponentProps<StyleProp<ViewStyle>, unknown, ViewProps>> & Partial<...> & { ...; } & RefAttributes<...>'

### gluestack-ui Version

^0.1.3

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by AshwiniKumar007** [comment]
Hey @ryuji-orca ,
Thanks for reporting. We will check this

**Comment by ryuji-orca** [comment]
> Thats great. Let me know if I can close this issue if its resolved.

Sorry I forgot to close.
I'll close it now that it's resolved.
