### ISSUE TITLE
createInput is not passing "type" property down to custom input component

### ISSUE THREAD

**Issue by vyobukhov** [gluestack/gluestack-ui#887]
### Description

createInput is not passing "type" property down to custom input component

### gluestack-ui Version

0.1.1

### Platform

- [X] Android
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

I have a custom Input with mask and this input uses `type` property for predefined masks like date, currency, etc. 

Inside @gluestack-ui/input/src/Input.tsx you extract `type` and some other keys from `props` but not pass it back to <StyledInput /> later. So custom input looses it's `type`.

**Comment by AshwiniKumar007** [comment]
Hey @vyobukhov ,
Thanks for reporting. We will check this.

**Comment by makkarMeenu** [comment]
I hope I understood your use-case correctly. 
You want to use `<InputField type="date" /> `.
Actually, we are extending React Native TextInput component which does not accept `type` property. So, it will not work on Input from `@gluestack-ui/themed` . 
But, if you are just using the unstyled version of gluestack i.e. `@gluestack-ui/input`  and passing that custom input to the styled. I will make the changes to the creator function.

**Comment by makkarMeenu** [comment]
@vyobukhov I hope I understood your use-case correctly. 
You want to use `<InputField type="date" /> `.
Actually, we are extending React Native TextInput component which does not accept `type` property. So, it will not work on Input from `@gluestack-ui/themed` . 
But, if you are just using the unstyled version of gluestack i.e. `@gluestack-ui/input`  and passing that custom input to the styled. I will make the changes to the creator function.

**Comment by vyobukhov** [comment]
> But, if you are just using the unstyled version of gluestack i.e. @gluestack-ui/input and passing that custom input to the styled. I will make the changes to the creator function.

Yes, this is exactly what I do. I pass this custom input to `styled`
https://github.com/akinncar/react-native-mask-text

```ts
const StyledMaskedTextInput = styled(
  MaskedTextInput, // imported from react-native-mask-text
  {...},
);

export const MaskedInput = createInput({
  Root: Input,
  Icon: InputIcon,
  Input: StyledMaskedTextInput,
});
```

But because the problem I described above, `type` got lost

**Comment by makkarMeenu** [comment]
@vyobukhov I have passed down the `type` prop to the `InputField` component. Also, we have changed the Input API a bit.
 from
```
<Input>    //View
 <InputField />   //TextInput
 <InputIcon>  //Pressable
    <Icon as={} />  //icon
</InputIcon>
</Input>
```
to

```
<Input>  //View
 <InputField />  //TextInput
 <InputSlot> //Pressable
     <InputIcon as={}/> //Icon
 </InputSlot>
</Input>
```

Let us know if you face any issue.
