### ISSUE TITLE
TypeScript Intellisense in VSCode Slows When Importing GlueStackUi in React Native

### ISSUE THREAD

**Issue by Bikash9609** [gluestack/gluestack-ui#903]
### Description

Happens in react native. When importing packages into any component, Visual Studio Code's (VSCode) suggestions feature experiences a significant slowdown. In certain instances, the suggestions might take an extended period to load or might not load at all. This issue was investigated by employing the following steps:  Initially, all imports in the component were commented out, and VSCode was reloaded. One by one, each import was uncommented, and the IntelliSense speed was tested after each enabling. Notably, upon enabling the import for gluestack, a project-wide slowdown was observed in import-related IntelliSense. The slowdown in intellisense impacts productivity and responsiveness during coding sessions.

### Steps to reproduce

1. Open Visual Studio Code (VSCode).
2. In react-native. Create a new component that requires multiple package imports.
3. Temporarily disable all these imports within the code. 
4. Reload VSCode.
5. Re-enable one of the imports, excluding `@gluestack-ui/themed`. For instance, `choose react-native-vector-icons`.
6. Attempt to test IntelliSense by hovering over code elements or invoking IntelliSense with Ctrl + Option (on Mac) or the appropriate shortcut on your system.
7. Finally, introduce an import for gluestack. Observe any changes in speed or performance.

### gluestack-ui Version

0.1.1

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Used vscode. Tried both on Mac and Windows. Both of the OS in latest versions

**Comment by AshwiniKumar007** [comment]
Hey @Bikash9609,
This shouldn’t happen. We will check this.

**Comment by Bikash9609** [comment]
I was going to use this for a project but it happened so much and interfered with my work so much that I had to switch to some other UI library. Somehow I think there is some kind of loop, which affects performance. All my devices were getting a performance hit somehow. As I work daily, I know the difference clearly. Switching between apps became laggy. 

Now, I am trying the same source code with a different UI library and it works very fine. Mostly, the problem seems to be that Typescript intellisense is not able to cache the types inside the package correctly somehow.

Hope that helps. Thanks already @AshwiniKumar007

**Comment by lucasasalmins** [comment]
I have also been experiencing the last couple of days, specifically with the `ActionSheet` and the `Select`. Other components are working fine. 
I'm using expo 49, vscode, typescript, react native

**Comment by ankit-tailor** [comment]
Hey @lucasasalmins @Bikash9609, Can you try the latest version?

**Comment by lucasasalmins** [comment]
Hey @ankit-tailor , thanks for looking into this. I just tested the action sheet out on the new version. It works! However, there is definitely still some lagging behaviour going on - it seems to take a 5-10 seconds for the intellisense to resolve in this file, but it does eventually.

**Comment by sankyag** [comment]
Same for me

**Comment by jack-pearson** [comment]
Same for me

**Comment by PieroNarciso** [comment]
First time trying using this library on a new project. Happened to me today, I thought was Neovim and tsserver configuration because was using a huge amount of memory ram.

**Comment by ankit-tailor** [comment]
Hi everyone, We'll fix this issue in upcoming releases. We have added it to roadmap.

**Comment by suhaotian** [comment]
@ankit-tailor Some information with `--diagnostics`:


```sh
tsc --diagnostics --noEmit
```

Memory Used Gigabytes≈2.794

```
Files:              1445
Lines:           2284478
Identifiers:     2157416
Symbols:         2605009
Types:             40573
Instantiations:  4896317
Memory used:    2932120K
I/O read:          0.29s
I/O write:         0.00s
Parse time:        8.37s
Bind time:         4.20s
Check time:        5.42s
Emit time:         0.00s
Total time:       17.99s
```



Before migrate:

Memory Used Gigabytes≈0.246

```
Files:             1347
Lines:           215572
Identifiers:     230229
Symbols:         170460
Types:            10625
Instantiations:   34211
Memory used:    258534K
I/O read:         0.16s
I/O write:        0.00s
Parse time:       1.07s
Bind time:        0.24s
Check time:       0.38s
Emit time:        0.00s
Total time:       1.69s
```

**Comment by ankit-tailor** [comment]
Hi Everyone, sorry for the delay. We have improved the typescript performance in the latest version. Closing the issue for now feel free to re-open it if you face any issues.

**Comment by suhaotian** [comment]
Hi, @ankit-tailor thanks hard working!

I update the libs to latest version, then run again:

```sh
tsc --noEmit --diagnostics
```

The diagnostics result show the memory used bigger than previous, and total time still take long time(>15s)

```
Files:              1511
Lines:           2557161
Identifiers:     2361287
Symbols:         2722624
Types:             38027
Instantiations:   776369
Memory used:    3159497K
I/O read:          0.42s
I/O write:         0.00s
Parse time:        9.05s
Bind time:         3.98s
Check time:        2.36s
Emit time:         0.04s
Total time:       15.43s
```

**Comment by ankit-tailor** [comment]
Hey @suhaotian, We are working on this. You can track the issue here #1663.

**Comment by DavidAmyot** [comment]
@ankit-tailor I still have this issue with all the latest versions of gluestack. Just importing  something like `import { Box, Fab, FlatList, Heading, Text } from "@gluestack-ui/themed";` drastically makes it so the intellisense takes about 4-5 seconds to popup compared to instantly when the import is commented out.

**Comment by abubakar2000** [comment]
Any update on this. This is such a good project and love it but only thing is keeping me from using it is this slowing down behaviour. I have so many projects coming up that I plan to use this library in. But slowing down is going to be a deal breaker sadly. :(

**Comment by suhaotian** [comment]
@abubakar2000 what version you use

**Comment by abubakar2000** [comment]
> @abubakar2000 what version you use

    "@gluestack-style/react": "^1.0.56",
    "@gluestack-ui/config": "^1.1.18",
    "@gluestack-ui/themed": "^1.1.28"
Here you go

**Comment by suhaotian** [comment]
No issue for me, it's fast:


```
Files:             1208
Lines:           203290
Identifiers:     231585
Symbols:         135351
Types:              193
Instantiations:       0
Memory used:    235546K
I/O read:         0.14s
I/O write:        0.00s
Parse time:       0.88s
Bind time:        0.18s
Check time:       0.00s
Emit time:        0.02s
Total time:       1.09s
```

You can run `tsc --noEmit --diagnostics` to get the result

**Comment by mysmaily** [comment]
it still slows down my vscode today

**Comment by khajimatov** [comment]
for those who are still wondering about the reason why intellisense is running slow, the answer may be - if you have added this regex from docs(https://gluestack.io/ui/docs/home/getting-started/tooling-setup) to the `./vscode/settings.json` file:
``` json
slow
{
  "tailwindCSS.experimental.classRegex": [
    ["tva\\((([^()]*|\\([^()]*\\))*)\\)", "[\"'`]([^\"'`]*).*?[\"'`]"]
  ]
}
```
this regex slows down the tailwind autocomplete, and as a result it gets stuck.
the temporary solution I found is to refactor the regex expression:
``` json
{
  "tailwindCSS.experimental.classRegex": [
    ["tva\\(([^)]*)\\)", "{?\\s?[\\w].*:\\s*?[\"'`]([^\"'`]*).*?,?\\s?}?"]
  ]
}
```
