### ISSUE TITLE
[Theme] Variants not appearing as option

### ISSUE THREAD

**Issue by JoseCWise** [gluestack/gluestack-ui#913]
### Description

Created project with nextjs, and put glueStackProvider around. The build on android  and expo is applying styles without error but on vsCode is appearing errors that the variant doesn't exist.

### Steps to reproduce

1. Created project with template expo
2.  In _layout.tsx
```
 <GluestackUIProvider config={extendedConfig}>
      <QueryClientProvider client={queryClient}>
        <Stack>
          <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
        </Stack>
      </QueryClientProvider>
    </GluestackUIProvider>
```
 3. Edited config.theme
 
```
 import { createConfig, config } from '@gluestack-ui/themed';

export const extendedConfig = createConfig({
  ...config.theme,
  components: {
    Button: {
      theme: {
        variants: {
          variant: {
            ghost: {
              bg: '$red500',
            },
          },
        },
      },
    },
  },
});
```

5. Tried to call variant
<img width="670" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/108409218/58e3f526-aa41-48f7-a5f8-a632574eedca">

### gluestack-ui Version

0.1.10

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by AshwiniKumar007** [comment]
Hey @JoseCWise , 
Thanks for reporting. We will look into this

**Comment by JoseCWise** [comment]
> Hey @JoseCWise , Thanks for reporting. We will look into this

Hey just a thing i noticed, i think it's a typescript typing problem, when i use javascript it works fine. On the variants on components probably need to add a string typing for custom variants. Not really sure tho

**Comment by Viraj-10** [comment]
Hey @JoseCWise, We can fixed this issue in our latest version.
Please follow our updated documentation on [customizing components](https://ui.gluestack.io/docs/theme/customizing-components).
