### ISSUE TITLE
Modal components making typescript intellisense slower in VSCode

### ISSUE THREAD

**Issue by CarlosSLoureiro** [gluestack/gluestack-ui#927]
### Description

When I try to use the example of modal component my VSCode intellisense for typescript makes VERY slow to load tips

### Steps to reproduce

Just try to apply the example of modal component:

https://ui.gluestack.io/docs/components/overlay/modal

### gluestack-ui Version

0.1.10

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hey @CarlosSLoureiro, Can you try latest version?

**Comment by jack-pearson** [comment]
I was really, really slow in version 1.0. Force me to use this awesome ui library in a way

**Comment by surajahmed** [comment]
I understand this can be frustrating. We are actively addressing the issue, and we would appreciate it if you could update your typescript version to the latest in your project.

**Comment by ankit-tailor** [comment]
Duplicate of #903.
