### ISSUE TITLE
Menu with placement top doesn't work

### ISSUE THREAD

**Issue by lhguerra** [gluestack/gluestack-ui#984]
### Description

I could get the menu component to work fine with placement bottom, but when trying to change it to top, which is the requirement I'm dealing with right now, it disappears. I press the trigger, there is a fast blink in the screen and then nothing happens.

### gluestack-ui Version

@gluestack-ui/themed@0.1.18

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Here's my implementation:
```
<Menu
      placement="top"
      trigger={({ ...triggerProps }) => (
        <Button
          {...triggerProps}
          sx={{
            alignItems: "center",
            backgroundColor: "transparent",
            flexDirection: "column",
          }}
        >
          <Image
            source={smileFace}
            width={32}
            height={32}
            alt="reaction icon"
          />
          <ButtonText
            sx={{
              color: "$green.90",
              fontSize: "$2xs",
              fontWeight: "$medium",
            }}
          >
            Reagir
          </ButtonText>
        </Button>
      )}
    >
      <MenuItem key="like" textValue="like">
        <Text>like</Text>
      </MenuItem>
      <MenuItem key="dislike" textValue="dislike">
        <Text>dislike</Text>
      </MenuItem>
    </Menu>
```

**Comment by makkarMeenu** [comment]
@lhguerra  Please upgrade the `@gluestack-ui/themed` to `0.1.33`. It will resolve the issue.

**Comment by lhguerra** [comment]
Worked like a charm! Thanks a lot for the quick response <3

**Comment by mohammadmansour200** [comment]
What if I was using `@gluestack-ui/menu` instead of `@gluestack-ui/themed`? @makkarMeenu
