### ISSUE TITLE
Typescript issue with Box and View components

### ISSUE THREAD

**Issue by genesy** [gluestack/gluestack-ui#996]
### Description

Component works but shows issues with ts

### Steps to reproduce

<img width="836" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/1282480/0de11f6f-2e7f-4beb-9ec8-d7d070b9c274">

Just testing out the library and getting this when trying out base components

### gluestack-ui Version

0.1.16

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by genesy** [comment]
```import { GluestackUIProvider, config } from '@gluestack-ui/themed';
import { Text, Box, View } from '@gluestack-ui/themed';

export default function HomeScreen() {
  return (
    <GluestackUIProvider config={config.theme}>
      <View>
        <Text>Test Screen</Text>
      </View>
      <Box>
        <Text>Test Screen</Text>
      </Box>
    </GluestackUIProvider>
  );
}```

**Comment by makkarMeenu** [comment]
We couldn't reproduce it with the snack you provided. Can you share the repo, so that we can dig into the issue?

**Comment by ore-craftman** [comment]
I'm having same issue right now, happens with, VStack, HStack, Box, FormControlLabel, Input, FormControlHelper, FormControlHelper and FormControlErrorIcon

![Screen Shot 2023-09-09 at 9 06 12 AM](https://github.com/gluestack/gluestack-ui/assets/72739364/9bdfbde2-64b5-4079-83d5-65574a13671d)


to reproduce, just create a new expo react native project using expo router using typescript

**Comment by GabCostaSilva** [comment]
Having the same issue with VStack. I was using NativeBase, but now I'm migrating to Gluestack. 
![Screenshot 2023-09-13 at 22 32 05](https://github.com/gluestack/gluestack-ui/assets/40161412/033f61ad-82b4-4eb4-b9f0-72a1d299b46c)
![Screenshot 2023-09-13 at 22 32 26](https://github.com/gluestack/gluestack-ui/assets/40161412/da697ed1-8622-4368-bb16-2f3d170895c3)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-13 at 22 32 58](https://github.com/gluestack/gluestack-ui/assets/40161412/d6d84343-ccc3-45f9-a846-678a3911fab0)

**Comment by thecogmel** [comment]
Same issue here! I started new project using expo and gluestack following docs and i haved this typescript error 

![image](https://github.com/gluestack/gluestack-ui/assets/30555537/b15ea9bb-44d5-44e8-950e-c64908ec6f25)

**Comment by EgorKrasno** [comment]
Same issue, pretty much every component expects a string?

**Comment by Georgerowberry** [comment]
Can confirm same is happening on versions:
@gluestack-style/react@0.2.51
 @gluestack-ui/themed@0.1.49

**Comment by Georgerowberry** [comment]
The issues was with the tsconfig - managed to get type checking working with the below conf:

`
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@gluestack-ui/themed": ["../../packages/themed/src"]
    },
    "emitDeclarationOnly": true,
    "noEmit": false,
    "declaration": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["esnext", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "esnext"
  }
}
`

**Comment by surajahmed** [comment]
Can you please try updating the latest versions of `@gluestack-style/react`, `@gluestack-ui/themed`?
